### ISSUE TITLE
Could I install DirectXTK without UWP Tools and ARM VC++ Libraries?

### ISSUE THREAD

**Issue by LYP951018** [Microsoft/DirectXTK#102]
I only write desktop programs and I don't want to install them.... (I mean the DirecXTK vsix）

**Comment by walbourn** [comment]
There's no particular requirement for DirectXTK to need these tools if you are targeting Win32 desktop. I suspect you are actually talking about the [directx-vs-templates](https://github.com/walbourn/directx-vs-templates) VISX package for VS 2017 which does require these. The templates in the VSIX (including the Win32 desktop versions) make use of a class wizard that is part of the UWP tooling. That means with VS 2015 you have to include the "Windows Tools for UWP", and for VS 2017 you must have the UWP workload for any of the templates to work.
