### ISSUE TITLE
DGSL Editor

### ISSUE THREAD

**Issue by blippyblips** [Microsoft/DirectXTK#106]
Hello,

I wasn't at all sure where to direct this request but you(Chuck Walbourne; in case more people contribute to this) seemed quite involved with the use and documentation of the DGSL/Shader Designer that comes with Visual Studio.

I was wondering if it would be possible for you/Microsoft to open source the editor both as a learning tool/sample of how to create such extensions to Visual Studio but also so it can be more easily extended.

At this time it's of very limited use with the restricted naming, "buffers" that you're allowed to interact with and what functions are available but it could be a really nice tool if it was available to extend.

Thanks in advance

**Comment by walbourn** [comment]
I've passed your request on to the Visual Studio team.
