### ISSUE TITLE
capture desktop image to memory instead writing to file 

### ISSUE THREAD

**Issue by peererror** [Microsoft/DirectXTK#113]
HI all,
How can I copy the captured image in gbra bitmap into memory  using ScreenGrab instead writing to file .

**Comment by walbourn** [comment]
The ScreenGrab module is intended for simple 'screenshot' scenarios which is why it doesn't support a 'ToMemory' option. I do have a SaveToMemory function, however, in [DirectXTex](https://github.com/Microsoft/DirectXTex)

**Comment by notes365** [comment]
> 
> 
> The ScreenGrab module is intended for simple 'screenshot' scenarios which is why it doesn't support a 'ToMemory' option. I do have a SaveToMemory function, however, in [DirectXTex](https://github.com/Microsoft/DirectXTex)

hi,I did not find the SaveWICTextureTo`(Memory)`function in [Microsoft/DirectXTex](https://github.com/Microsoft/DirectXTex), what is the name of the related function

**Comment by walbourn** [comment]
DirectXTex is intended for content tools so it's organized differently than ScreenGrab which does the capture & write in one function call.

First call [CaptureTexture](https://github.com/microsoft/DirectXTex/wiki/CaptureTexture).

Then call [SaveToWICMemory](https://github.com/microsoft/DirectXTex/wiki/WIC-I-O-Functions)

See [the wiki](https://github.com/microsoft/DirectXTex/wiki/DirectXTex)
