### ISSUE TITLE
How to write a SkyBox/Cubemap with DirectXTK

### ISSUE THREAD

**Issue by ghost** [microsoft/DirectXTK#116]
Hi, I am new to Directx11 and DirectXTK is great to help me build an app. I am looking for a method to make a SkyBox/Cubemap with DirectXTK but I cannot figure it out. Is there any way to make that with DirectXTK? Please tell me if exist or I have to use the original API. That is pitty :(

**Comment by walbourn** [comment]
I already have a DirectX 12 version [here](https://github.com/microsoft/Xbox-ATG-Samples/tree/master/Kits/ATGTK/Skybox). The real problem is that for DirectX 11 it would either require hardware Feature Level 10.0 or better, or would have to use a different technique/shader for Shader Model 9.x

**Comment by aaronstackpole** [comment]
I'm not sure I understand what the issue would be, you've got an example already of a square room with a texture printed on the inside, shouldn't it be possible to just set the room to transform in relation to the camera?

**Comment by walbourn** [comment]
We already have a DXTK12 solution I linked above. The issue is to update it with support for DX11. The key issue is that the DX11 version requires ``D3D_FEATURE_LEVEL_10_0`` or better to utilize the ability to access a cubemap as six 2D texture arrays.

**Comment by aaronstackpole** [comment]
I'm pretty sure I was drawing a skybox in the background of my games in DOOM. Pretty sure you don't need to "access a cubemap as six element 2D texture array" to draw a skybox.

**Comment by walbourn** [comment]
You can of course create six individual 2D textures for the skybox, and then use the same images loaded into a cubemap for an environment map. The issue here is for a helper that shows to re-use the same cubemap for both.

**Comment by walbourn** [comment]
I'm working on a lesson writing a Skybox. It has the final version of the shader files & .h/.cpp if you want to use it now.

https://github.com/microsoft/DirectXTK/wiki/Authoring-an-Effect
