### ISSUE TITLE
How to make a SkyBox/Cubemap with DirectXTK?

### ISSUE THREAD

**Issue by wimi9u0** [Microsoft/DirectXTK#117]
Hi, I am new to Directx11 and DirectXTK is great to help me build an app. I am looking for a method to make a SkyBox/Cubemap with DirectXTK but I cannot figure out it. Is there any way to make that with DirectXTK? Please tell me if exist or I have to use the original API. That is a pitty. :(

**Comment by wimi9u0** [comment]
I tried to create a box with EnvironmentMapEffect but failed.

**Comment by walbourn** [comment]
Cubemaps are usually used to capture 'environments' surrounding a scene. The cubemap can be used to color in reflections, which is what the ``EnvironmentMapEffect`` achieves as seen in [this tutorial](https://github.com/Microsoft/DirectXTK/wiki/Using-advanced-shaders).

To make the effect more convincing in outdoor scenes, you often want to make the 'skybox' surrounding a scene reflect the cubemaps used for reflections.  For older Direct3D hardware feature levels, that's usually done with six individual 2D textures rendered inside of a 'box'. On Direct3D hardware feature level 10.0 or better, you can treat the same cubemap as an array of 2D textures for this. A DirectX 12 implementation can be see in [this sample code](https://github.com/Microsoft/Xbox-ATG-Samples/tree/master/Kits/ATGTK/Skybox) but can be easily applied to DirectX 11 as well as long as you require Direct3D hardware feature level 10.0 or better.
