### ISSUE TITLE
Suggestion to add Keyboard::GetPressedKeyCode() or something similar

### ISSUE THREAD

**Issue by robertanthony02** [Microsoft/DirectXTK#12]
For the TextBox control I created, I needed the ability to handle key down events to do all the things textboxes do.  Getting the keyboard state is the first step, but that's just a snapshot of the entire array of virtual keys.  Being able to simply query for which virtual key was pressed was important to me, so I created the following method.  If there is a more elegant solution or a method using the existing API I'd like to know and I'll ditch this approach-- which hopefully isn't too embarrassing!

Thanks!

```
	INT BInput::Keyboard::GetPressedKeyCode()
	{
		auto pState = reinterpret_cast<uint32_t*>(&BInput::KeyboardTracker->pressed);

		for (INT i = 0; i < 8; i++)
		{
			if (*pState != 0)
			{
				auto pStateChunk = reinterpret_cast<uint8_t*>(pState);

				for (INT j = 0; j < 4; j++)
				{
					if (*pStateChunk != 0)
					{
						for (INT k = 0; k < 8; k++)
						{
							if (*pStateChunk & (1 << k))
								return (32 * i) + (8 * j) + k;
						}
					}

					pStateChunk++;
				}
			}

			pState++;
		}

		return 0;
	}
```

**Comment by walbourn** [comment]
The goal of the ``Keyboard`` class for DirectX Tool Kit is to make it easier to write "keyboard is a controller" style stuff for games that works across desktop and UWP. For text edit fields and the like, you should look at the specific platform solutions instead of using a wrapper over my wrapper over the platform.

Note I mention this in the [docs](https://github.com/Microsoft/DirectXTK/wiki/Keyboard) in **Remarks**.

**Comment by robertanthony02** [comment]
Okay, that makes sense.  Thanks!



On Jun 30, 2015, at 5:59 PM, Chuck Walbourn <notifications@github.com> wrote:

The goal of the Keyboard class for DirectX Tool Kit is to make it easier to write "keyboard is a controller" style stuff for games that works across desktop and UWP. For text edit fields and the like, you should look at the specific platform solutions instead of using a wrapper over my wrapper over the platform.

Note I mention this in the docs in Remarks.
