### ISSUE TITLE
Mastering limiter boosting quiet sounds

### ISSUE THREAD

**Issue by PeteHuf** [Microsoft/DirectXTK#127]
(Based on #95, feel free to dupe. I didn't see a way to reopen #95.)

I hooked up the AUDIO_ENGINE_FLAGS::AudioEngine_UseMasteringLimiter. It is doing a good job of preventing clipping for loud sounds, but it also has an unexpected (and unwanted) effect: it seems to be boosting the volume of quiet sounds.

I have a weapon sound effect which starts loud and has a soft trail-off finish. When using the mastering limiter, the initial loud sound is the same volume as without the limiter (this sound doesn't clip even without the limiter), but the trail-off finish is louder. I expected the limiter to only make loud sounds quieter, not soft sounds louder.

I've noticed this with other sounds too. I have a consistently quiet wind sound which is boosted to be too loud when the limiter is on. I suspect something isn't configured properly, but I have no idea where to look. A Bing search hasn't given me any clues,--just people lamenting how little documentation there is about XAudio. :)

I'm using XAudio2_7.dll and XAPOFX1_5.dll.

I put together this a little demo project which demonstrates the issue: https://1drv.ms/u/s!AhmO0u3HJ7RHjoFUNArr6hFd9K_Epg

The demo runs the wind sound and a sci-fi weapon firing sound. It starts with the limiter off. Clicking the mouse toggles the limiter. When the limiter is on, the wind is louder and the firing sound gets a little quieter.

**Comment by walbourn** [comment]
The first thing to try is to build using XAudio2_8 (or 2.9) and see if it repros.

**Comment by PeteHuf** [comment]
I just tested them, and I get the same behavior with 2.8 and 2.9.

**Comment by walbourn** [comment]
I'll pass this report along to the audio team, but it's not likely an issue in the _DirectX Tool Kit_ itself.

**Comment by PeteHuf** [comment]
Thanks, Chuck. If the issue is with DirectX, is there a public place where I can track the issue?
