### ISSUE TITLE
Error in the Wiki page about DynamicSoundEffecetInstance

### ISSUE THREAD

**Issue by datoml** [Microsoft/DirectXTK#129]
There's an error in the Wiki page about the [DynamicSoundEffecetInstance](https://github.com/Microsoft/DirectXTK/wiki/DynamicSoundEffectInstance).

```
std::unique_ptr<DynamicSoundEffectInstance> effect;

// PCM 44100 Hz, 16-bit, 1 channel
effect = std::unique_ptr<DynamicSoundEffectInstance>( audEngine.get(),
    [](DynamicSoundEffectInstance*)
    {
        // 'Buffer needed' event handler
    },
    44100, 1 );
```

This part
```effect = std::unique_ptr<DynamicSoundEffectInstance>( audEngine.get(),```
should be
```effect = std::make_unique<DynamicSoundEffectInstance>( audEngine.get(),```

I have no idea how I could add a pull request for the wiki page so I created this issue here.

Edit:

Also the part for Audio data submission is outdated.
```int count = effect->PendingBufferCount();```
should be changed to
```int count = effect->GetPendingBufferCount();```

Greetings :).

**Comment by walbourn** [comment]
Thanks. I found a number of similar problems in the DirectXMesh wiki. I had written the docs originally for VS 2012 that didn't support ``std::make_unique`` then went back to clean it up...
