### ISSUE TITLE
Suggestion: Move ConstantBuffer.h from Src into Inc

### ISSUE THREAD

**Issue by trojanfoe** [microsoft/DirectXTK#130]
I find your ContantBuffer class very useful for managing constant buffers in my game but as it's located in Src (implying it's internal use only?), I have to add that directory to my include paths.

I think it would be better in Inc, signalling that it can be freely used by all.

**Comment by walbourn** [comment]
See [this PR](https://github.com/microsoft/DirectXTK/pull/220)
