### ISSUE TITLE
XWBTool Access violation (Windows 7)

### ISSUE THREAD

**Issue by CorySanin** [Microsoft/DirectXTK#131]
When trying to pack XWB files, I get the following error on my Windows 7 machine when trying to write the output file.

`Exception thrown at 0x756BE024 (KernelBase.dll) in XWBTool.exe: 0xC0000005: Access violation writing location 0x00000000.`

XWBTool works as expected on my Windows 10 VM. I'm not entirely sure it's OS related.

**Comment by walbourn** [comment]
Can you try it with a debug version of ``xwbtool.exe`` under the debugger? What line of code is throwing the exception?

**Comment by CorySanin** [comment]
Line 1544 of xwbtool.cpp
![screenshot](https://user-images.githubusercontent.com/2897351/38703301-83a78618-3e68-11e8-8ad8-5b7109915bf8.png)

**Comment by walbourn** [comment]
What version of Visual C++ are you using? I don't see any particular reason for this failure unless you are hitting a compiler codegen bug.

**Comment by CorySanin** [comment]
I'm using Visual C++ 2017. But I don't believe it's compiler related since the binary in [this release](https://github.com/Microsoft/DirectXTK/releases/tag/dec2017) crashes during the writing phase on my machine, also.

**Comment by walbourn** [comment]
What is the command-line you are using to invoke the tool?

**Comment by CorySanin** [comment]
I've tried `-o test.xwb F:\Cory\Downloads\unxwb\out\*.wav`, as well as explicitly naming a few wav files without the wildcard. The output shows that the intended files are getting processed. Once it gets to writing the output, it crashes.

**Comment by walbourn** [comment]
I just tried ``-o test.xwb c:\Windows\media\*.wav`` and it worked fine for me. Can you verify that works for you as well?

If so there must be either an issue with the specific ``wav`` files you are using. Can you provide the console output from your failing case? It might give me a hint as to what is happening.

**Comment by walbourn** [comment]
Nevermind. I found the problem per MSDN:

    lpNumberOfBytesWritten [out, optional] 

> A pointer to the variable that receives the number of bytes written when using a synchronous hFile parameter. WriteFile sets this value to zero before doing any work or error checking. Use NULL for this parameter if this is an asynchronous operation to avoid potentially erroneous results.

> **This parameter can be NULL only when the lpOverlapped parameter is not NULL.**

**Comment by walbourn** [comment]
Fixed in [this commit](https://github.com/Microsoft/DirectXTK/commit/18c9c94bf515ee2c27667b8c96b9f838b3eca925)
