### ISSUE TITLE
Compilation issues with Intel C++ 18 compiler

### ISSUE THREAD

**Issue by walbourn** [Microsoft/DirectXTK#137]
When building with latest Intel C++ compiler, you get some warnings:

> WAVFileReader.cpp(26): warning #1899: multicharacter character literal (potential portability problem)

> WAVFileReader.cpp(27): warning #1899: multicharacter character literal (potential portability problem)

> WAVFileReader.cpp(28): warning #1899: multicharacter character literal (potential portability problem)
    
> WAVFileReader.cpp(29): warning #1899: multicharacter character literal (potential portability problem)

>  WAVFileReader.cpp(30): warning #1899: multicharacter character literal (potential portability problem)

> WAVFileReader.cpp(31): warning #1899: multicharacter character literal (potential portability problem)

> WAVFileReader.cpp(32): warning #1899: multicharacter character literal (potential portability problem)

> WAVFileReader.cpp(33): warning #1899: multicharacter character literal (potential portability problem)
   
> WAVFileReader.cpp(34): warning #1899: multicharacter character literal (potential portability problem)

> WaveBankReader.cpp(350): message #2557: comparison between signed and unsigned operands

> DGSLEffectFactory.cpp(313): message #2557: comparison between signed and unsigned operands

> Geometry.cpp(1160): message #2557: comparison between signed and unsigned operands

> SpriteBatch.cpp(299): message #2557: comparison between signed and unsigned operands

> SpriteBatch.cpp(892): message #2557: comparison between signed and unsigned operands

> xwbtool.cpp(89): warning #1689: invalid use of access specifier is ignored

>xwbtool.cpp(95): warning #1689: invalid use of access specifier is ignored

**Comment by walbourn** [comment]
The Intel C++ 18 compiler (Update 1) seems to have some internal bugs with ``std::make_unique`` that needs fixed before the code will safely compile.

**Comment by tuan-a-tran** [comment]
I got the same internal bugs with std::make_unique with Intel C++ 19 compiler (19.0.1.144). I got an error
error: ‘make_unique’ is not a member of ‘std’

**Comment by walbourn** [comment]
@tuan-a-tran   What version of Visual C++ are you using with Intel C++? Intel C++ doesn't include it's own copy of the C/C++ Runtime.

**Comment by tuan-a-tran** [comment]
@walbourn I use Parallel Studio XE 2019 Cluster Studio edition. Any suggestion? Do I have to explicitly link to gnu version support C++14?
