### ISSUE TITLE
SaveDDSTextureToFile doesn't save cubemaps.

### ISSUE THREAD

**Issue by comeradealexi** [Microsoft/DirectXTK#141]
Hi!

We're converting some legacy D3D9 code which used D3DXCreateCubeTextureFromFileEx and D3DXSaveTextureToFile to resize certain textures and we're now using DirectXTK and using CreateDDSTextureFromFile with SaveDDSTextureToFile.

However it appears SaveDDSTextureToFile doesn't work with cube maps. Our texture is a Texture2D with an array size of 6 but after calling SaveDDSTextureToFile, this information appears to be lost.

Is this a bug or is support for this simply not there? I can't see anywhere where it writes out to the DirectX header the information it needs to detect it as a cube map.

Thanks!

**Comment by walbourn** [comment]
This is covered in the [wiki](https://github.com/Microsoft/DirectXTK/wiki/ScreenGrab)

> These writers do not support array textures, 1D textures, 3D volume textures, or cubemaps. Mipmaps are also ignored. For those scenarios, use the DirectXTex library functionality. The ScreenGrab module is really designed to make a quick and light-weight solution for capturing screenshots at runtime.

**Comment by comeradealexi** [comment]
Thanks Walbourn! I'll use DirectXTex instead :)

It would be good if it made this more aware to the end user with a log message or something similar. I only used the function as it was recommend from this article here as the conversion: https://blogs.msdn.microsoft.com/chuckw/2013/08/20/living-without-d3dx/

Anyway, thanks for the quick reply!

Alex

**Comment by walbourn** [comment]
I mentioned both in that article as well, but it really depends on what you were doing with it. D3DX suffered from having too many usage scenarios. DirectX Tool Kit is mostly focused on 'runtime' usage in games and apps, while DirectXTex is for content processing & tools. Most games only *write* textures for screenshots. I'll see about adding a code comment to ScreenGrab to point it out...
