### ISSUE TITLE
Why Matrix.Forward right-handed?

### ISSUE THREAD

**Issue by Ziriax** [Microsoft/DirectXTK#144]
Given that DirectX uses a left-handed coordinate system, why is `Matrix.Forward ` right-handed?

**Comment by walbourn** [comment]
**TL;DR:** SimpleMath is intended to match the XNA Game Studio math library which uses Right-handed, row-major matrices. See [wiki](https://github.com/Microsoft/DirectXTK/wiki/SimpleMath#enter-simplemath).

DirectXMath itself which you can use directly or interop easily with SimpleMath supports both LH and RH forms, and most of the Win32 desktop samples from the legacy DirectX SDK use DirectXMath, Left-handed, row-major matrices. See [docs](https://docs.microsoft.com/en-us/windows/desktop/dxmath/pg-xnamath-getting-started#matrix-convention)
