### ISSUE TITLE
Can't use Anything from DirectxTK (Reference problem I think)

### ISSUE THREAD

**Issue by Besnarb** [Microsoft/DirectXTK#145]
Hi,

I'm pretty new to directx11 trying to do this tutorial : https://github.com/Microsoft/DirectXTK/wiki/Rendering-a-model

I followed it from the beginning, using this other one (https://blogs.msdn.microsoft.com/chuckw/2015/01/06/direct3d-win32-game-visual-studio-template/) to transform my Directx11 Xaml template to a compliant project.

At this point I'm having a light blue empty window.

Then I'm adding by a project-to-project reference DirectxTK (Adding the Inc folder to the Other Include Folders)

At this point I'm just trying to add `DirectX::SimpleMath::Matrix m_world;` in my Game.h and I'm getting following errors : 

- C2039 'SimpleMath'  : is not a member of  'DirectX'
- C3083	'SimpleMath' : the symbol to the left of a '::' must be a type
- C2039	'Matrix' : is not a member of  'DirectX'
- C3646	'm_world' : unknown override specifier
- C4430	missing type specifier - int assumed. Note: C++ does not support default-int

I'm pretty sure I messed something up in the reference but I can't find what =/

Does someone have an idea ?

Many thanks

**Comment by Besnarb** [comment]
I put it in pch.h
Like it's said in the tutorial

**Comment by walbourn** [comment]
It may be how you have your pch configured, but that would be pretty odd. 

Anyhow, glad you made it work for now.
