### ISSUE TITLE
SDL - banned API memcpy

### ISSUE THREAD

**Issue by tosmolka** [Microsoft/DirectXTK#146]
Hi, we noticed that DirectX Tool Kit in few places uses functions (e.g. `memcpy`) that we try to globally ban in our projects. In case of `memcpy` it seems that parts of the kit already uses `memcpy_s`, can you please prioritize transforming the rest? Thank you.

**Comment by tosmolka** [comment]
Hi Chuck, our SDL tooling is flagging only `memcpy` in [WICTextureLoader.cpp](https://github.com/Microsoft/DirectXTK/blob/master/Src/WICTextureLoader.cpp). I think usage there is fine but since it's just couple of places, would be nice to avoid it if possible. Thanks.

**Comment by walbourn** [comment]
Seems legit to use ``memcpy_s`` for file parsing code, so sure.

**Comment by walbourn** [comment]
Yeah, it seems odd to do ``memcpy_s`` when the parameter for both ``DestinationSize`` and ``SourceSize`` is the same thing. It does make sense if they are two different things...

**Comment by walbourn** [comment]
See [this commit](https://github.com/Microsoft/DirectXTK/commit/31b326ef91ed19134cc7a99a5fd074162ae7ccf7).

Also looking at other GitHub projects.

**Comment by tosmolka** [comment]
Thanks Chuck, I agree `memcpy` was fine in this case - thanks anyway for the change.
