### ISSUE TITLE
 DirectXTK draw transparent text

### ISSUE THREAD

**Issue by Sabrond** [Microsoft/DirectXTK#149]
How can I draw a transparent text?

**Comment by walbourn** [comment]
What have you tried?

See [Drawing Text](https://github.com/Microsoft/DirectXTK/wiki/Drawing-text), [SpriteBatch](https://github.com/Microsoft/DirectXTK/wiki/SpriteBatch), and [SpriteFont](https://github.com/Microsoft/DirectXTK/wiki/SpriteFont)

**Comment by Sabrond** [comment]
Thanks.
Solution: [DirectXTK draw transparent text](https://github.com/Microsoft/DirectXTK/wiki/SpriteBatch).
Code: 
```
CommonStates states(device);
spriteBatch->Begin(SpriteSortMode_Deferred, states.NonPremultiplied() );
```

**Comment by walbourn** [comment]
``MakeSpriteFont`` defaults to using premultipled alpha, and so ``SpriteBatch`` does as well. if you create your ``SpriteBatch`` using ``NonPremultiplied``, then you either need to submit your ``SpriteFont`` drawing in a different ``Begin`` / ``End`` block with out it, or you need to generate your ``spritefont`` with ``/NoPremultiply``.
