### ISSUE TITLE
At high resolutions, XMMatrixScaling misaligns textures drawn with multiple sprite batch draw calls

### ISSUE THREAD

**Issue by bbfe** [Microsoft/DirectXTK#151]
If I use XMMatrixScaling with fractional numbers, various textures are misaligned. 

All I want to do is make draw calls to a low resolution and then scale the result up. I don't see how to accomplish this with spritebatch. I can't seem to get a texture from sprite batch that I can pass to another sprite batch and then render to a RECT, for example.

This is the misalignment I'm talking about:

https://i.imgur.com/PEXUQKq.png

**Comment by walbourn** [comment]
The simplest solution is to explicitly set the viewport on the ``SpriteBatch`` to your 'logical' resolution and then it will scale up to the actual render target's ``RSSetViewport``'.

For example, if you were rendering at 4k (3840 x 2160) and but had laid out your UI for 1080p (1920 x 1080), then you can use:

    auto vp1080 = CD3DX11_VIEWPORT( 0, 0, 1920, 1080 );
    m_sprite->SetViewport(vp1080);

**Comment by bbfe** [comment]
Yes, that's what I'm currently doing, but it does result in the image with misaligned pixels when the scaling ends up being a non integer multiplier.

I sort of resolved it by creating another Texture2D, rendering that one to a render target integer ratios, and then rendering that in the sprite batch at the native monitor resolution. It works, but I'm not sure whether there's a better way to handle it.

This is an awesome framework, by the way. I'm not joking when I say that it changed my life.

**Comment by walbourn** [comment]
If you need better filtering, it sounds like your approach is best (render to a smaller render target, then upscale via a texture blit).

Glad the project has been useful to you. I've been keeping at it for years, so it's nice to hear success stories.
