### ISSUE TITLE
Why does the color change,use spritebatch

### ISSUE THREAD

**Issue by zhaokaixs** [Microsoft/DirectXTK#156]
![image](https://user-images.githubusercontent.com/7833585/51010689-5b22ec00-1590-11e9-8139-93742f25811c.png)

**Comment by walbourn** [comment]
This is likely sRGB vs. Linear color. If you are loading a ``.PNG` it is probably marked as sRGB resulting in an ``_DXGI_*_SRGB`` format, but you have your rendering set up to be non-linear, or alternatively if you are loading it as a ``.DDS`` then you might need to use ``forceSRGB``.

[Linear-Space Lighting (i.e. Gamma)](http://filmicworlds.com/blog/linear-space-lighting-i-e-gamma/)

[Chapter 24. The Importance of Being Linear](https://developer.nvidia.com/gpugems/GPUGems3/gpugems3_ch24.html), GPU Gems 3

[Gamma-correct rendering](https://blog.molecular-matters.com/2011/11/21/gamma-correct-rendering/)

**Comment by zhaokaixs** [comment]
if i want support SRGB and other texture format(texture source is not img file),how can i do it,thanks

**Comment by walbourn** [comment]
It depends on:

(a) If your source image file is in sRGB/gamma 2.2 space or linear

(b) What your render target/format is as to whether or it needs converted back to sRGB/gamma 2.2

**Comment by walbourn** [comment]
Since you are using ``.JPG``, I don't believe this is an issue with [straight vs. premultiplied alpha](http://www.shawnhargreaves.com/blogindex.html#premultipliedalpha), but you should also keep that in mind when using [SpriteBatch](https://github.com/Microsoft/DirectXTK/wiki/SpriteBatch).
