### ISSUE TITLE
Model error

### ISSUE THREAD

**Issue by dudedude1234** [Microsoft/DirectXTK#157]
I'm setting up LoadModel

`void Boxer::LoadModel()
{

	auto device = m_deviceResources->GetD3DDevice();
	m_states = std::make_unique<CommonStates>(device);

	m_fxFactory = std::make_unique<EffectFactory>(device);

	m_model = Model::CreateFromCMO(device, L".cmo", *m_fxFactory);

	m_world = Matrix::Identity;

	m_swing = std::make_unique<SoundEffect>(m_audEngine.get(), L".wav");
	m_lightPunch = std::make_unique<SoundEffect>(m_audEngine.get(),
		L".wav");
	m_mediumPunch = std::make_unique<SoundEffect>(m_audEngine.get(), L".wav");
	m_heavyPunch = std::make_unique<SoundEffect>(m_audEngine.get(),
		L".wav");
	m_pain = std::make_unique<SoundEffect>(m_audEngine.get(), L".wav");

	auto iskin = dynamic_cast<IEffectSkinning*>(effect.get());
	if (iskin)
	{
		iskin->SetBoneTransforms(bones.get(), boneCount);
	}

	// Simple time-based uniform scaling
	float s = 1 + sin(timer * 1.7f) * 0.5f;
	XMMATRIX scale = XMMatrixScaling(s, s, s);

	for (size_t j = 0; j < boneCount; ++j)
	{
		bones[j] = scale;
	}

	effect->SetBoneTransforms(bones.get(), boneCount);

}`

with this

`DX::StepTimer m_timer;`

I keep getting errors

**Comment by walbourn** [comment]
What errors?

**Comment by walbourn** [comment]
You aren't actually including any filenames for your data files:

    m_model = Model::CreateFromCMO(device, L".cmo", *m_fxFactory);

``.CMO`` is just the file extension. What's the file name?

    m_swing = std::make_unique<SoundEffect>(m_audEngine.get(), L".wav");

``.WAV`` is just the file extension. What's the file name?

**Comment by walbourn** [comment]
``timer`` is a class object, not a value.

    float s = 1 + sin(timer * 1.7f) * 0.5f;

You need to call one of it's methods to get a time value. For exampe,

    float time = timer.GetTotalSeconds();
    float s = 1 + sin(time * 1.7f) * 0.5f;

See [StepTimer](https://github.com/Microsoft/DirectXTK/wiki/StepTimer).
