### ISSUE TITLE
Menu error

### ISSUE THREAD

**Issue by dudedude1234** [Microsoft/DirectXTK#162]
I'm making a menu

'enum Menu
{
	FightNow,
	Career,
	BeatdownLive,
	Help,
	Options
};'

'void MainMenu::LoadMenu()
{
	auto context = m_deviceResources->GetD3DDeviceContext();
	auto device = m_deviceResources->GetD3DDevice();
	m_spriteBatch = std::make_unique<SpriteBatch>(context);

	ComPtr<ID3D11Resource> resource;
	DX::ThrowIfFailed(
		CreateWICTextureFromFile(device, L"cat.png",
			resource.GetAddressOf(),
			m_texture.ReleaseAndGetAddressOf()));

	ComPtr<ID3D11Texture2D> logo;
	DX::ThrowIfFailed(resource.As(&logo));

	CD3D11_TEXTURE2D_DESC logoDesc;
	logo->GetDesc(&logoDesc);

	m_origin.x = float(logoDesc.Width / 2);
	m_origin.y = float(logoDesc.Height / 2);

	while (gameOn != false) {
		
		
		cout << DX::ThrowIfFailed(
			CreateWICTextureFromFile(device, L"cat.png",
				resource.GetAddressOf(),
				m_texture.ReleaseAndGetAddressOf())); ;
		cout << DX::ThrowIfFailed(
			CreateWICTextureFromFile(device, L"cat.png",
				resource.GetAddressOf(),
				m_texture.ReleaseAndGetAddressOf()));
		cout << DX::ThrowIfFailed(
			CreateWICTextureFromFile(device, L"cat.png",
				resource.GetAddressOf(),
				m_texture.ReleaseAndGetAddressOf()));
		cout << DX::ThrowIfFailed(
			CreateWICTextureFromFile(device, L"cat.png",
				resource.GetAddressOf(),
				m_texture.ReleaseAndGetAddressOf()));
		

		cin >> mode;

		while (true)
		{
			switch (mode)
			{
			case FightNow:

				break;
			}
		}
	}
}'

I keep getting these errors

E0349	no operator "<<" matches these operands	
E0349	no operator ">>" matches these operands

**Comment by walbourn** [comment]
This construct doesn't make any sensE:

    cout << DX::ThrowIfFailed(...);

You can't output the result of the C++ exception throwing helper to a stream. Remove the ``cout <<`` part.

**Comment by walbourn** [comment]
cout << endl;

**Comment by dudedude1234** [comment]
Its for each menu entry

**Comment by dudedude1234** [comment]
I fixed up the menu like this:

MainMenu::MainMenu()
{
	

		
		


}

MainMenu::~MainMenu()
{
}

void MainMenu::Update()
{
	switch (menu) 
	{
	case 1:
		
		break;
	case 2:
		
		break;
	case 3:
		
		break;
		cin >> menu;

	}
}

void MainMenu::LoadMenu()
{
	auto context = m_deviceResources->GetD3DDeviceContext();
	auto device = m_deviceResources->GetD3DDevice();
	m_spriteBatch = std::make_unique<SpriteBatch>(context);

	ComPtr<ID3D11Resource> resource;
	DX::ThrowIfFailed(
		CreateWICTextureFromFile(device, L"cat.png",
			resource.GetAddressOf(),
			m_texture.ReleaseAndGetAddressOf()));

	ComPtr<ID3D11Texture2D> logo;
	DX::ThrowIfFailed(resource.As(&logo));

	CD3D11_TEXTURE2D_DESC logoDesc;
	logo->GetDesc(&logoDesc);

	m_origin.x = float(logoDesc.Width / 2);
	m_origin.y = float(logoDesc.Height / 2);




}

void MainMenu::Render()
{
	m_spriteBatch->Begin();

	m_spriteBatch->Draw(m_texture.Get(), m_screenPos, nullptr, Colors::White,
		0.f, m_origin);

	const wchar_t* cout << "1 - Start game\n";
	const wchar_t* cout << "2 - Options\n";
	const wchar_t* cout << "3 - Quit\n";
	const wchar_t* cout << "Selection: ";
	cin >> menu;

	Vector2 origin = m_font->MeasureString(cout) / 2.f;

	m_font->DrawString(m_spriteBatch.get(), cout,
		m_fontPos + Vector2(1.f, 1.f), Colors::Black, 0.f, origin);
	m_font->DrawString(m_spriteBatch.get(), cout,
		m_fontPos + Vector2(-1.f, 1.f), Colors::Black, 0.f, origin);
	m_font->DrawString(m_spriteBatch.get(), cout,
		m_fontPos + Vector2(-1.f, -1.f), Colors::Black, 0.f, origin);
	m_font->DrawString(m_spriteBatch.get(), cout,
		m_fontPos + Vector2(1.f, -1.f), Colors::Black, 0.f, origin);

	m_font->DrawString(m_spriteBatch.get(), cout,
		m_fontPos, Colors::White, 0.f, origin);

	m_spriteBatch->End();
}

I keep getting these errors:


Error (active)	E0065	expected a ';'

**Comment by walbourn** [comment]
Rather than look at the "Error List". What errors do you see in the Output Window set to Build?

**Comment by dudedude1234** [comment]
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\unknwnbase.h(109): message :  see declaration of 'IUnknown'
1>E:\Beatdown\Beatdown\Mechanics\Controller.h(16,2): error C3987:  '{ctor}': signature of public member contains native type 'IUnknown *'
1>E:\Beatdown\Beatdown\Mechanics\GameInfoOverlay.h(59,55): error C3646:  'm_app': unknown override specifier
1>E:\Beatdown\Beatdown\Mechanics\GameInfoOverlay.h(59,55): error C1003:  error count exceeds 100; stopping compilation

**Comment by walbourn** [comment]
You are missing the required include headers to build your files. Consider making a ``pch.h`` for global system headers. See [Microsoft Docs](https://docs.microsoft.com/en-us/cpp/build/creating-precompiled-header-files?view=vs-2019)

**Comment by dudedude1234** [comment]
I redid the menu based on this tutorial:
https://eangogamedevelopment.blogspot.com/2017/01/part-22-making-game-menu.html?m=1

`
#include <iostream>

#include "MenuState.h"



MenuState::MenuState(Game* game)
{
    this->game = game;

    for (int i = 0; i < NUM_BUTTONS; i++)
    {
        button.push_back(m_font);
        button[i](m_fontPos.x, m_fontPos.y);
    }
}

void MenuState::LoadMenu()
{

    auto context = m_deviceResources->GetD3DDeviceContext();
    auto device = m_deviceResources->GetD3DDevice();
    m_spriteBatch = std::make_unique<SpriteBatch>(context);

    




}

void MenuState::loadgame()
{

    switch (m_menu)
    {
    case FightNow:
        game->pushState(new PlayState(game));
        break;


    }
}

void MenuState::handleInput()
{



}

void MenuState::OnDeviceLost()
{
    m_spriteBatch.reset();
}

bool MenuState::isTextClicked()
{
    return false;
}

void MenuState::update(const float dt)
{
    switch (menu) {

    case FightNow:
        
        break;
    }
}

void MenuState::draw(const float dt)
{

    const int button[0] = L"Fight Now";
    m_spriteBatch->Begin();

    Vector2 origin = m_font->MeasureString(button) / 2.f;

    m_font->DrawString(m_spriteBatch.get(), button,
        m_fontPos, Colors::White, 7.f, origin);

    m_spriteBatch->End();


}


`
I keep having this error:
"The size of the array must be greater than zero"

**Comment by walbourn** [comment]
As I've said, I think you would be well-served by looking at basic tutorials on C/C++.

The following is not valid C/C++ code:

```
const int button[0] = L"Fight Now";
```

It would work if it was:

```
const int button[] = L"Fight Now";
```

**Comment by dudedude1234** [comment]
I managed to fix some errors: 

`
std::unique_ptr<DirectX::SpriteFont>                          m_font;
std::vector<const char>                                       menuButton;


MainMenu::MainMenu(Game* game)
{
	this->game = game;

	for (int i = 0; i < NUM_BUTTONS; i++)
	{
		menuButton.push_back;
		menuButton[i].setPosition(m_fontPos.x, m_fontPos.y + i * 100);
	}

	menuButton[0].ToString = "";



}`

Yet I keep getting this error:

Error (active)	E0109	expression preceding parentheses of apparent call must have (pointer-to-) function type

**Comment by dudedude1234** [comment]
I managed to fix some of the errors

`std::unique_ptr<DirectX::SpriteFont>                          m_font;
std::vector<std::wstring>                                     menuButton;

MainMenu::MainMenu(Game* game)
{
	this->game = game;

	for (int i = 0; i < NUM_BUTTONS; i++)
	{
		menuButton.push_back;
		menuButton[i].assign(m_fontPos.x, m_fontPos.y + i * 100);
	}

	menuButton[0] = std::wstring(L"Hello");



}

void MainMenu::Render(const float dt)
{




	m_spriteBatch->Begin();
	Vector2 origin = m_font->MeasureString(menuButton) / 2.f;

	m_font->DrawString(m_spriteBatch.get(), menuButton,
		m_fontPos, Colors::White, 0.f, origin);

		m_spriteBatch->Draw(m_background.Get(), m_fullscreenRect);

		m_spriteBatch->Draw(m_texture.Get(), m_screenPos, nullptr, Colors::White,
			0.f, m_origin);

		m_spriteBatch->End();
}

`

Yet I keep getting this error

Error (active)	E0304	no instance of overloaded function "DirectX::SpriteFont::MeasureString" matches the argument list	
Error (active)	E0304	no instance of overloaded function "DirectX::SpriteFont::DrawString" matches the argument list

**Comment by walbourn** [comment]
``std::vector<std::wstring> menuButton`` is a vector of strings. There is no overload of ``DrawString`` or ``MeasureString`` which takes a vector of strings.

You need to use ``menubutton[0].c_str()`` where 0 is whatever index you want to use in your vector.
