### ISSUE TITLE
XYZ help

### ISSUE THREAD

**Issue by dudedude1234** [Microsoft/DirectXTK#165]
I'm arranging the models in my software using this

m_player = ref new Sphere(XMFLOAT3(0.0f, -1.3f, 4.0f), 0.2f);

Is the left X, the middle Y and the right Z?

**Comment by walbourn** [comment]
Yes the order is ``x``, ``y``, ``z``, but what that actually means depends on your world and view transformations. For example, if you are using _left-handed viewing coordinates_, then ``+Z`` is farther away in the front, while with _left-handed viewing coordinates_, then ``-Z`` is further away in the front.

See [this blog post](http://www.realtimerendering.com/blog/left-handed-vs-right-handed-viewing/) for more information, or really any text on 3D graphics will cover the basics of viewing coordinates.
