### ISSUE TITLE
Drawing transparent text/geometry/texture on transparent window

### ISSUE THREAD

**Issue by Sabrond** [Microsoft/DirectXTK#166]
Hello, 
Problem: i drawing transparent text on transparent window, transparency does not work on transparent windows for all elements, texture, text, geometry. _Thanks for any help._

**RGBA(255, 255, 255, **25**)**

![image](https://user-images.githubusercontent.com/28992047/53546407-10fcc680-3b4e-11e9-8d4f-a63dba8ba036.png)

`MakeSpriteFont.exe "Roboto Mono"robotoMono.spritefont /Sharp /FontSize:11 /TextureFormat:Rgba32 /characterregion:0x20-0x7E /characterregion:0x400-0x4FF /NoPremultiply`

**Result:**
![1](https://user-images.githubusercontent.com/28992047/53545776-69cb5f80-3b4c-11e9-8d93-09fb3da7c411.png)

**Begin:**
![image](https://user-images.githubusercontent.com/28992047/53546308-cbd89480-3b4d-11e9-8665-4ff8c7b739a6.png)

**End:**
![image](https://user-images.githubusercontent.com/28992047/53546330-d7c45680-3b4d-11e9-9ed2-0135f72cd7bb.png)

**DrawText:**
![image](https://user-images.githubusercontent.com/28992047/53546867-4e158880-3b4f-11e9-978f-32a7ea7f6922.png)

**Comment by walbourn** [comment]
The problem is that the render target you are using does not contain any of the background... it's blank.

You probably should use Direct2D/DirectWrite for this scenario rather than ``SpriteFont``.
