### ISSUE TITLE
 Player error

### ISSUE THREAD

**Issue by dudedude1234** [Microsoft/DirectXTK#167]
I'm setting up a fighting game camera
`	m_camera->SetViewParams(
		XMFLOAT3(0.0f, 0.7f, 0.0f),      // Eye point in world coordinates.
		m_playerOne->Position() +
		m_playerTwo->Position(),  // Look at point in world coordinates.
		XMFLOAT3(0.0f, 1.0f, 0.0f)      // The Up vector for the camera.`

I keep getting this error

E0135	class "Player" has no member "VectorPosition"

**Comment by shawnhar** [comment]
This is a C++ programming question, not related to DirectXTK.  StackOverflow might be a better place to get help with such things?
