### ISSUE TITLE
inline unsigned int makeVoiceKey(_In_ const WAVEFORMATEX* wfx)

### ISSUE THREAD

**Issue by morffiy** [Microsoft/DirectXTK#168]
It does not take into account the sample rate.

**Comment by walbourn** [comment]
The voice manager changes the sample rate with ``SetSourceSampleRate`` for voice re-use, which is why the key doesn't include it.

**Comment by morffiy** [comment]
@walbourn Ok, but what about nBlockAlign ?
For 8 bit waves it will be 1 but makeVoiceKey does not handle this case.

**Comment by walbourn** [comment]
8-bit waves also have a ``wBitsPerSample`` of 8 which is part of the key for ``WAVE_FORMAT_PCM`` along with the tag.

Can you provide an example of two ``WAVEFORMATEX`` structures that are "different" but have the same key value (i.e. where you are seeing a collision that is failing with source voice reuse)?

**Comment by walbourn** [comment]
Note I added some comments to the code in [this commit](https://github.com/Microsoft/DirectXTK/commit/797efe63b058462337b593e7bfcf2db04526a61b
). If there are further fixes needed here, I'm definitely interested in getting the failing test cases.

**Comment by morffiy** [comment]
@walbourn 
1.) Create first voice 

```
WAVEFORMATEX = 
{
wFormatTag	1
nChannels	1
nSamplesPerSec	44100
nAvgBytesPerSec	88200
**nBlockAlign	2**
wBitsPerSample	16
cbSize	18764
}
```
2.) Release voice and create another one

```
WAVEFORMATEX = 
{
wFormatTag	1
nChannels	1
nSamplesPerSec	22050
nAvgBytesPerSec	22050
**nBlockAlign	1**
wBitsPerSample	8
cbSize	0
}
```
The second voice will return the voice from cache and when you will try to SubmitSourceBuffer you may get an error like this:
**XAUDIO2: ERROR: AudioBytes (63873) not aligned to the audio format's block size (2)**

**Comment by walbourn** [comment]
``wBitsPerSample`` is different so they have different hash keys. Did you have any other sound playing before this? You can use ``AudioEngine::GetStatistics`` to gather some counts before you submit sounds.

**Comment by morffiy** [comment]
@walbourn sorry, it is my mistake...

**Comment by walbourn** [comment]
Glad you resolved it.
