### ISSUE TITLE
VID and PID

### ISSUE THREAD

**Issue by ahmed-t-mpc** [microsoft/DirectXTK#169]
Hi, could you please make the API expose the Vendor ID and Product ID controller information ?

**Comment by walbourn** [comment]
This information is not exposed by the XINPUT API, which is the design surface for ``GamePad``. It's also not exposed by ``Windows.Gaming.Input``.

What's your reason for wanting this information?

**Comment by ahtur** [comment]
Hi. We're exclusively developing for Windows 10 desktop (not uwp) and need this info to customize our control mapping ui according to the physical controller plugged in. Isn't it possible to get it from Windows.Gaming.Input's RawGamController (https://docs.microsoft.com/en-us/uwp/api/windows.gaming.input.rawgamecontroller) ? I admit I don't really understand ABI::Windows::Gaming::Input nor what it really contains from Windows.Gaming.Input...

**Comment by ahtur** [comment]
Do you think you can do something about this ?

**Comment by walbourn** [comment]
As I said, XINPUT doesn't provide VID/PID by design. It might be possible to cross-correlate it with DirectInput (as indicated in this [article]()) but that wouldn't work for UWP. In WGI it does have a VID/PID value but I'm not sure how to correlate a gamepad with a raw game controller.

Again, I guess my main question is still : What do you want to do with this information? I.e. why do you need it for your scenario?

**Comment by ahtur** [comment]
> Again, I guess my main question is still : What do you want to do with this information? I.e. why do you need it for your scenario?

My use is that I need a way to display to the user, on a specific screen, the names of their controller's buttons as they appear on the controller. Not A, B, X, Y, etc. all the time but, instead, the labels that are actually printed on the controller, be it a logitech gamepad, a flightstick or a steering wheel. They don't all have the same number of buttons nor the same button labels.

For that I need to differentiate between controllers according to their VID and PID, do I not ? And then I would look these VID/PID up inside my own maintained database of VID/PID and return the corresponding button labels. Does this make sense ?

**Comment by walbourn** [comment]
Generally speaking when using the XINPUT API, the only information you key off for layout hints would be the ``gamepadType`` value coming back from ``Capabilities`` (which in XINPUT is the ``XInputGetCapabilities`` return structure). You then use the 'most common layout' which for gamepads is the Xbox Common Controller gamepad--artwork can be found [here](https://github.com/SimonDarksideJ/XNAGameStudio/wiki/Xbox-360-Controller-Images). Kind of the point of XINPUT was to move away from the "every controller looks different" usage problem that plagued DirectInput.

If you need something more sophisticated, you probably should write your own input manager rather than make use of my abstraction.

**Comment by walbourn** [comment]
Note that it's technically possible with the Windows 10 (16299) or later version of ``Windows.Gaming.Input`` to get the VID/PID via RawGameController, but this information is not surfaced by any version of XINPUT.

**Comment by ahtur** [comment]
> Note that it's technically possible with the Windows 10 (16299) or later version of `Windows.Gaming.Input` to get the VID/PID via RawGameController, but this information is not surfaced by any version of XINPUT.
> 
> To do this for WGI, you'd do basically the same pattern I do [here](https://github.com/Microsoft/DirectXTK/commit/2850741095bc2fcba500bb6706cb3e4905e68557) but use `FromGameController` to get to a `RawGameController` and then call `HardwareVendorId` / `HardwareProductId`

Since we're exclusively developing for W10 desktop, that's exactly what we ended up doing, Chuck. Thanks.

**Comment by walbourn** [comment]
Implemented this in the master branch with [this commit](https://github.com/microsoft/DirectXTK/commit/e2143bfef55427e9bef70faf6c4c76d4e1b5902c)

**Comment by DJm00n** [comment]
Hi @walbourn!
Maybe you can hidden func `XInputGetCapabilitiesEx` from XInput 1.4 (comes with Windows 8):

```cpp
typedef struct _XINPUT_CAPABILITIES_EX
{
	XINPUT_CAPABILITIES Capabilities;
	WORD VendorId;
	WORD ProductId;
	WORD VersionNumber;
	WORD unk1;
	DWORD unk2;
} XINPUT_CAPABILITIES_EX, * PXINPUT_CAPABILITIES_EX;

// XInputGetCapabilitiesEx hidden function is available since Windows 8 version of XInput1_4.dll
DWORD XInputGetCapabilitiesEx(DWORD dwUserIndex, PXINPUT_CAPABILITIES_EX pCapabilitiesEx)
{
	DWORD(WINAPI* XInputGetCapabilitiesExFunc)(DWORD unk1, DWORD dwUserIndex, DWORD dwFlags, PXINPUT_CAPABILITIES_EX pCapabilities);
	XInputGetCapabilitiesExFunc = reinterpret_cast<decltype(XInputGetCapabilitiesExFunc)>(::GetProcAddress(::GetModuleHandleW(L"XInput1_4.dll"), (LPCSTR)108));

	if (!XInputGetCapabilitiesExFunc)
		return ERROR_INVALID_FUNCTION;

	return XInputGetCapabilitiesExFunc(1, dwUserIndex, 0, pCapabilitiesEx);
}

....
XINPUT_CAPABILITIES_EX caps;
popMemZeroStruct(caps);

XInputGetCapabilitiesEx(m_UserIndex, &caps);

// Fixup for Wireless Xbox 360 Controller
if (caps.ProductId == 0 && caps.Capabilities.Flags & /*XINPUT_CAPS_WIRELESS*/0x0002)
{
	caps.VendorId = 0x045E;
	caps.ProductId = 0x02A1;
}

m_VendorId = caps.VendorId;
m_ProductId = caps.ProductId;

// Known controller VID/PID list: https://github.com/libsdl-org/SDL/blob/main/src/joystick/controller_type.h
```
https://gist.github.com/DJm00n/0f0563702f6cf01e8812ebc760a78cf1#file-xinputgetcapabilitiesex-cpp

What do you think?

**Comment by walbourn** [comment]
Using an undocumented private API is always tricky long-term because of potential appcompat issues. I'll think about it some more before I commit either way.

> Also note that there are a number of legacy Xbox 360 Wireless VID/PID values, although that's probably "good enough" for many scenarios. It also won't detect the difference between Xbox 360 Wireless and Xbox One Wireless.

Note that GameInput on PC will solve this problem officially as it includes VID/PID information.

**Comment by DJm00n** [comment]
>GameInput on PC
unfortunately seems we can't use it just yet. do you know when it will be available for PC use?

>NOTE: PC support (including earlier versions of Windows) will be available in an upcoming Windows SDK.
https://docs.microsoft.com/en-us/gaming/gdk/_content/gc/input/overviews/input-overview

**Comment by walbourn** [comment]
Follow-up: GameInput supports PC in [Game Development Kit](https://github.com/microsoft/GDK) June 2022 or later.
