### ISSUE TITLE
Keyboard.h should mention to include Windows.h or include Windows.h due to UINT, WPARAM and LPARAM

### ISSUE THREAD

**Issue by nbiefeld** [Microsoft/DirectXTK#172]
If you just include Keyboard.h without a direct include for Windows.h, an error will occur stating "syntax error: identifier 'UINT'".  Searching for reasons for this error only provide responses from people saying it is due to circular include dependencies.  However, this is not the case.  You first need to include Windows.h in order for UINT to be recognized.

#include "Keyboard.h"
-> results in error "syntax error: identifier 'UINT'"

#include <Windows.h>
#include "Keyboard.h"
-> Compiles just fine

**Comment by walbourn** [comment]
The current version of the header has:

    #if !defined(WINAPI_FAMILY) || (WINAPI_FAMILY == WINAPI_FAMILY_DESKTOP_APP) && defined(WM_USER)
        static void __cdecl ProcessMessage(UINT message, WPARAM wParam, LPARAM lParam);
    #endif

Which means it should really require ``windows.h``. Any idea how it got that far for you without it?

**Comment by nbiefeld** [comment]
Hey thanks for the comment!

I think it is due to me creating my own input system, and just having #include “Keyboard.h” fails unless I also include Windows.h too. Is there a better work around for this?  I have include Windows.h in my main.cpp file, but I also had to put it in my input.cpp file for the uint error to go away. 

Sorry for any typos, typing from my phone.

**Comment by walbourn** [comment]
Generally ``windows.h`` is the kind of thing you put into your Precompiled Header so it doesn't slow down your build.

I think I see the problem. It should be:

    #if (!defined(WINAPI_FAMILY) || (WINAPI_FAMILY == WINAPI_FAMILY_DESKTOP_APP)) && defined(WM_USER)
    static void __cdecl ProcessMessage(UINT message, WPARAM wParam, LPARAM lParam);
    #endif

**Comment by walbourn** [comment]
Fixed in [this commit](https://github.com/Microsoft/DirectXTK/commit/4751611d925628d09ddfee249601f79021911da4)
