### ISSUE TITLE
vcpkg and unresolved external DirectX::Mouse::SetWindow

### ISSUE THREAD

**Issue by mediabuff** [Microsoft/DirectXTK#174]
Does this lib work with vcpkg ? I get unresolved DirectX::Mouse::SetWindow(struct ABI::Windows::UI::Core::ICoreWindow *)

**Comment by walbourn** [comment]
I don't maintain the vcpkg version, so I'm not sure what release it is. That said, are you sure you are building the right platform version? It looks like you want the UWP version?

Note I do maintain NuGet packages. See [releases](https://github.com/Microsoft/DirectXTK/releases).

**Comment by mediabuff** [comment]
I think the issue is beyond vcpkg. I figured. The code in mouse.h has to be changed as follows:

   #if (defined(WINAPI_FAMILY) && (WINAPI_FAMILY == WINAPI_FAMILY_APP)) || (defined(_XBOX_ONE) && defined(_TITLE) && (_XDK_VER >= 0x42D907D1))
        void __cdecl SetWindow(ABI::Windows::UI::Core::ICoreWindow* window);

to 
void __cdecl SetWindow(ABI::Windows::UI::Core::ICoreWindow* window)
{
      impl->SetWindow(window);
}

    #ifdef __cplusplus_winrt
        void __cdecl SetWindow(Windows::UI::Core::CoreWindow^ window)
        {
            // See https://msdn.microsoft.com/en-us/library/hh755802.aspx
            SetWindow(reinterpret_cast<ABI::Windows::UI::Core::ICoreWindow*>(window));
        }
    #endif

**Comment by walbourn** [comment]
Are you using C++/CX (``/ZW``) or C++/WinRT?

**Comment by mediabuff** [comment]
I am using C++/WinRT - and this the problem. Looking at the code C++/CX might be ok as it has the inline function.

#ifdef __cplusplus_winrt
        void __cdecl SetWindow(Windows::UI::Core::CoreWindow^ window)
        {
            // See https://msdn.microsoft.com/en-us/library/hh755802.aspx

            SetWindow(reinterpret_cast<ABI::Windows::UI::Core::ICoreWindow*>(window));
        }
#endi

**Comment by walbourn** [comment]
So the magic incantation you want is:

    mouse->SetWindow(reinterpret_cast<ABI::Windows::UI::Core::ICoreWindow*>(static_cast<::IUnknown*>(winrt::get_abi(window))));


I'll see if I can make a more intuitive helper for C++/WinRT scenarios.

**Comment by walbourn** [comment]
I add a helper for C++/WinRT in [this commit]](https://github.com/Microsoft/DirectXTK/commit/92ead37be90e3bead8f8850b0ab791071e5a8aa8) and updated the [wiki](https://github.com/Microsoft/DirectXTK/wiki/Mouse).

**Comment by walbourn** [comment]
Actually, ``get_abi`` already returns ``void*`` so you don't have to worry about the double-cast. Just do:

```cpp
mouse->SetWindow(reinterpret_cast<ABI::Windows::UI::Core::ICoreWindow*>(winrt::get_abi(window)));
```
