### ISSUE TITLE
Port C++/WRL Gamepad  to C++/WinRT

### ISSUE THREAD

**Issue by DJm00n** [microsoft/DirectXTK#179]
DirectXTK Gamepad class is used as a reference implementation of using Windows::Gaming::Input and Windows::Xbox::Input APIs by many game programmers (by me 🤣).
 
Please port Windows 10 and Xbox ONE implementations from now deprecated C++/WRL to new and shiny C++/WinRT that is officially supported now.

**Comment by walbourn** [comment]
Actually, I use WRL which means that the library doesn't actually build with C++/CX ``/ZW``. It should be compatible with both C++/CX and C++/WinRT as a result.

I recently cleaned up some integration functions in for Keyboard/Mouse to improve the C++/WinRT experience, but it doesn't impact implementation.

What issues in particular are you noticing?

**Comment by DJm00n** [comment]
Oh, sorry, you're indeed using WRL. So I mean porting code from C++/WRL to C++/WinRT. 
According to [current docs](https://docs.microsoft.com/en-us/cpp/cppcx/wrl/windows-runtime-cpp-template-library-wrl) WRL is superseded by C++/WinRT.
I just lacking official usage examples of Windows::Gaming::Input for C++/WinRT.
Will rename issue.

**Comment by walbourn** [comment]
In that case, see [this sample](https://github.com/microsoft/Xbox-ATG-Samples/tree/master/UWPSamples/System/GamepadCppWinRT_UWP).
