### ISSUE TITLE
DDSTextureLoader.cpp function CreateD3DResources ignoring Bind flags

### ISSUE THREAD

**Issue by yonisi** [microsoft/DirectXTK#180]
Hi,

Thanx for the DXTK package, very useful! :)

I've noticed a small issue that when calling DirectX::CreateDDSTextureFromFileEx with bind flags set to 0 but with a none NULL texture view pointer, the CreateD3DResources which is called internally will create a SRV even though the Bind flags variable doesn't explicitly include the D3D11_BIND_SHADER_RESOURCE (In my case 0).

I've found this bug when I tried to replace old D3DX texture loading function and use DDSTextureLoader but for loading multiple DDS textures for further use to build a texture array, hence the Bind flags were 0 for the individual textures because I only need CPU access to read them later and build the array eventually.

The bypass for this bug is to simply send a nullptr instead of the SRV, but however it is confusing and IMHO wrong that the underlying function tries to create a SRV when the Bind flags variable don't explicitly specify it.

Of course the easy fix is to check the Bind flags for D3D11_BIND_SHADER_RESOURCE before trying to create a SRV.

Thanx!
Yoni

**Comment by walbourn** [comment]
You should be getting useful error output from the Direct3D debug device in this case, but I can add an explicit validation test:

```
if (textureView && !(bindFlags & D3D11_BIND_SHADER_RESOURCE))
{
    return E_INVALIDARG;
}
```

**Comment by walbourn** [comment]
Fixed in [this pull request](https://github.com/microsoft/DirectXTK/pull/181)

> Also updated the DirectXTex library copy of these functions in [this pull request](https://github.com/microsoft/DirectXTex/pull/142)

**Comment by yonisi** [comment]
Thank you! :)
