### ISSUE TITLE
Use SimpleMath::Rectangle with SpriteBatch::Draw

### ISSUE THREAD

**Issue by aaronstackpole** [microsoft/DirectXTK#182]
Cannot use a SimpleMath::Rectangle as the 3rd parameter in SpriteBatch::Draw. It requires a &RECT object and Rectangle does not return the desired type, instead you have to use m_rectangle.operator RECT. Could we improve the Rectangle and/or the SpriteBatch class to take this object without the .operator RECT appended?

**Comment by walbourn** [comment]
Actually using ``Rectangle`` as a parameter to ``SpriteBatch`` works just fine. The problem you are encountering is because of C++ namespaces. For an operator overload to match, it needs to be in the current namespace scope.

**TL;DR:** Add ``using namespace DirectX::SimpleMath;`` to the top of your cpp file or in the local scope of your function.

**Comment by walbourn** [comment]
A similar issue happens with the DirectXMath ``XMVECTOR`` and ``XMMATRIX`` operator overloads if you don't have ``using namespace DirectX;``.

**Comment by aaronstackpole** [comment]
I have `using DirectX::SimpleMath::Rectangle` at the top of my CPP already, but tried adding the namespace as well, but it did not allow me to use the member Rectangle. It's not a huge problem, I just have a member RECT that I construct from a Rectangle argument. Perhaps it's the way I'm using it, I have a SpriteBase class that holds each of the members required for the SpriteBatch::Draw, and I have yet to figure out a way to get a Rectangle to be an acceptable reference object as an argument.

**Comment by aaronstackpole** [comment]
If I change &m_source to &m_rectangle, the Draw command does not accept the argument.
[https://cdn.discordapp.com/attachments/420586902438150145/596602413507674118/unknown.png](url)

**Comment by walbourn** [comment]
Ah, so you don't mean the Draw that takes a ``RECT const& destinationRectangle``, but rather the one that takes a ``RECT const* sourceRectangle``. Let me take a look.

**Comment by walbourn** [comment]
Directly trying to return an address of a temporary object is non-portable, so I cannot do the following--although Visual C++ will let you do this as a language extension.

```cpp
operator RECT * () { RECT rct; rct.left = x; rct.top = y; rct.right = (x + width); rct.bottom = (y + height); return &rct; }
```

Probably the best solution is to do:

```cpp
RECT srcRect = m_rectangle;
batch->Draw(...., &srcRect, ...);
```
