### ISSUE TITLE
HDR Tutorial Program Not Working

### ISSUE THREAD

**Issue by richardrobinson0924** [microsoft/DirectXTK#183]
In the HDR sample program / project, after following the documentation completely, the program compiles, however it does not run in HDR mode nor does it display the teapot image.

I am using DirectX 11 on the latest version of Windows and Visual Studio. Furthermore, I have tried both `x64` and `x86` configurations.

**Comment by walbourn** [comment]
The key issue with HDR10 on Windows is that the system has to be in an HDR mode. The program can only check to see if the current display is doing HDR10.

See [HDR and WCG color settings in Windows 10](https://support.microsoft.com/en-us/help/4040263/windows-10-hdr-advanced-color-settings)
