### ISSUE TITLE
In ToneMapPostProcess, is there any scaling / transformations applied other than the pixel shaders?

### ISSUE THREAD

**Issue by richardrobinson0924** [microsoft/DirectXTK#186]
Using a light meter, the values I measured were not in keeping with the expected results, so I was wondering if there is there anything else applied?

**Comment by walbourn** [comment]
W.r.t. to HDR10, I don't do anything else. That said, for PC there may be other adjustments you need to make on the system.  See [here](https://support.microsoft.com/en-us/help/4040263/windows-10-hdr-advanced-color-settings).
