### ISSUE TITLE
Vector3 does not Equal If use Lerp\SmoothStep

### ISSUE THREAD

**Issue by PoweredByAndrox** [microsoft/DirectXTK#190]
Hi, sorry for my bad English)
I use those functions to make a cut-scene (or smooth moving a camera by points) and it works good but if i pass less this value like 
![ScreenShot_20190914094238](https://user-images.githubusercontent.com/38520826/64900426-7bcdb380-d6d4-11e9-8337-64a64be00986.png)
then i have this result
![изображение](https://user-images.githubusercontent.com/38520826/64900472-a6b80780-d6d4-11e9-96e3-d7d4e2e6f832.png)
Of course it doesn't equal and my code looks wrong. What do I need to do with this situation?

**Comment by PoweredByAndrox** [comment]
Good results if I pass more than that value (e.g. 0.50f or 1.f)

**Comment by walbourn** [comment]
What version of Visual C++ are you using?

**Comment by PoweredByAndrox** [comment]
17

**Comment by PoweredByAndrox** [comment]
The versino of WindowsSDK is 10.0.18362.0

**Comment by walbourn** [comment]
Which update?

**Comment by PoweredByAndrox** [comment]
No, i don't think that it's true problem

**Comment by walbourn** [comment]
I can't see the result of the call in your screenshot...

So a potential problem I see is your first comparison:

```
if (CamPos != CurrentPoint.Pos)
```

Binary comparison of floating-point numbers for equality is often not what you really need. In this case you probably want to use ``XMVector3NearEqual`` instead

**Comment by PoweredByAndrox** [comment]
I check it now

**Comment by PoweredByAndrox** [comment]
Yeah, thank you but it works only for the first point (which on screenshot) but by the second point it doesn't work. I use args from your test
![изображение](https://user-images.githubusercontent.com/38520826/64901350-89d30280-d6db-11e9-910a-24e607b90a97.png)
But I have this value
![изображение](https://user-images.githubusercontent.com/38520826/64901360-a53e0d80-d6db-11e9-883e-547c7c11a9d1.png)
How do i correct that vector?

**Comment by walbourn** [comment]
Again, I still don't the return value from ``SmoothStep`` so I'm not sure what exactly you are concerned about.

Note that you may need to choose a different epsilon for the test. Perhaps ``0.0001``

**Comment by PoweredByAndrox** [comment]
The teleport function works so **XMStoreFloat3(&m_vEye, NewPos);** and (how the screenshot) i just get that vector and use in this function.
Of course thank you for support me in this situation)
I want to ask you last question. I'm using your Audio and there don't work positional 3d audio. Do you do with this? (I work on my audio but it doesn't need me). And when you'll be write other articles?

**Comment by walbourn** [comment]
I haven't written the tutorial for 3D audio (I have an open [issue](https://github.com/microsoft/DirectXTK/issues/82) for it). You can see an example of it's usage in my [Test suite](https://github.com/walbourn/directxtktest/tree/master/Audio3DTest).

**Comment by PoweredByAndrox** [comment]
Thank you for your answers I don't have any problems any more)
