### ISSUE TITLE
Game state management

### ISSUE THREAD

**Issue by dudedude1234** [microsoft/DirectXTK#191]
I'm setting up the game state management

enum Menu
{
	MainMenu,
	GameplayScreen,
	Career,
	XboxLive,
	Help,
	Options
};

// Renders Direct2D and 3D content on the screen.
namespace Game
{
	class GameMain: public DX::IDeviceNotify
	{
	public:
		GameMain(const std::shared_ptr<DX::DeviceResources>& deviceResources);
		~GameMain();
		void CreateWindowSizeDependentResources();
		void Update();
		bool Render();

		// IDeviceNotify
		virtual void OnDeviceLost();
		virtual void OnDeviceRestored();

	private:
		// Cached pointer to device resources.
		std::shared_ptr<DX::DeviceResources> m_deviceResources;

		// TODO: Replace with your own content renderers.

                 Menu                                                    m_menu;
		GameplayScreen                       m_gameplayScreen;
		MainMenu                             m_mainMenu;

		// Rendering loop timer.
		DX::StepTimer m_timer;
	};
}

// Loads and initializes application assets when the application is loaded.
GameMain::GameMain(const std::shared_ptr<DX::DeviceResources>& deviceResources) :
	m_deviceResources(deviceResources)
{
	// Register to be notified if the Device is lost or recreated
	m_deviceResources->RegisterDeviceNotify(this);

	// TODO: Replace this with your app's content initialization.
	

	// TODO: Change the timer settings if you want something other than the default variable timestep mode.
	// e.g. for 60 FPS fixed timestep update logic, call:
	/*
	m_timer.SetFixedTimeStep(true);
	m_timer.SetTargetElapsedSeconds(1.0 / 60);
	*/
}

GameMain::~GameMain()
{
	// Deregister device notification
	m_deviceResources->RegisterDeviceNotify(nullptr);
}

// Updates application state when the window size changes (e.g. device orientation change)
void GameMain::CreateWindowSizeDependentResources() 
{
	// TODO: Replace this with the size-dependent initialization of your app's content.
	switch (m_menu)
	{
	default: MainMenu:
	    m_mainMenu->CreateWindowSizeDependentResources();
		break;
	case: GameplayScreen:
		m_gameplayScreen->CreateWindowSizeDependentResources();
		break;
	}
}

// Updates the application state once per frame.
void GameMain::Update() 
{
	// Update scene objects.
	m_timer.Tick([&]()
	{
		// TODO: Replace this with your app's content update functions.
			switch (m_menu)
			{
			default: MainMenu:
				m_mainMenu->Update();
				break;
			case: GameplayScreen:
				m_gameplayScreen->Update();
				break;
			}
	});
}

// Renders the current frame according to the current application state.
// Returns true if the frame was rendered and is ready to be displayed.
bool GameMain::Render() 
{
	// Don't try to render anything before the first Update.
	if (m_timer.GetFrameCount() == 0)
	{
		return false;
	}

	auto context = m_deviceResources->GetD3DDeviceContext();

	// Reset the viewport to target the whole screen.
	auto viewport = m_deviceResources->GetScreenViewport();
	context->RSSetViewports(1, &viewport);

	// Render the scene objects.
	// TODO: Replace this with your app's content rendering functions.
	switch (m_menu)
	{
	default: MainMenu:
		m_mainMenu->Render();
		break;
	case: GameplayScreen:
		m_gameplayScreen->Render();
		break;
	}

	return true;
}

// Notifies renderers that device resources need to be released.
void GameMain::OnDeviceLost()
{
	switch (m_menu)
	{
	default:
		
		break;
	}
}

// Notifies renderers that device resources may now be recreated.
void GameMain::OnDeviceRestored()
{
	switch (m_menu)
	{
	default:

		break;
	}
	CreateWindowSizeDependentResources();
}

But I keep having these errors:

E0757	constant "GameplayScreen" is not a type name	
E0757	constant "MainMenu" is not a type name

**Comment by walbourn** [comment]
`` default: MainMenu:`` and ``case: GameplayScreen:`` are not valid C++ statements. You should take some time to review the basics of C++ coding. There are numerous tutorials online. My DirectX Tool Kit tutorials assume you already know C++. See the [wiki](https://github.com/microsoft/DirectXTK/wiki/Getting-Started#background)
