### ISSUE TITLE
Static Compiling DirectXTK Nuget Package

### ISSUE THREAD

**Issue by Itsukan0** [microsoft/DirectXTK#192]
Hello !

Thank you for the package, it is of great use to me !

Context :  

I am using DirectXTK package as a nuget package. I tried using vcpkg to get a static version but there is an error message saying there is only a dynamic version. Thus I used the Nuget Package. 
I want to use the following function : DirectX::CreateWICTextureFromFile()
Visual Studio Version : 2019
I have the include path properly set up and added the .lib to the linker entry.

Problem : 

I am trying to compile statically and the linker asks for obj files.
![errormessage](https://user-images.githubusercontent.com/44704801/65503326-0082b380-dec5-11e9-8c0b-baa51622fdf6.png)

Question :

Is there a way to compile statically while using the Nuget Package ? Since You already provide .lib and headers only .obj files are missing, maybe there is a point in linking I didn't understand.

I know I can download the DirectXTK and fully compile it myself but I'll use it as a last resort.

Thank You for your help !

**Comment by walbourn** [comment]
With NuGet, you should not need to add any .lib explicitly as it's handled automatically. You only need to add the include path for the headers per the [wiki](https://github.com/microsoft/DirectXTK/wiki/Adding-the-DirectX-Tool-Kit#nuget-package-manager).

The path you show isn't valid. The actual path that contains the lib is ``packages\DirectXTK_desktop_2015.2019.8.23.1\lib\x64\Debug\``

**Comment by Itsukan0** [comment]
Thanks for your reply !

I used another project to investigate this as for my first project I just compiled DXTK myself statically.

On this other sample project, when I set the compiling option "RunTime Library" in "Code Generation" to "MDd", it compiles just fine with the Nuget Package, but when I set it to "MTd", this error pops up : 

![errormessage2](https://user-images.githubusercontent.com/44704801/65588901-86b3fe00-df88-11e9-927c-373adc8c3068.png)

**Comment by walbourn** [comment]
I don't provide versions of my NuGet packages that link against the CRT statically. Generally you should always prefer to use the DLL version of the CRT. As you note, you can always build the code from source yourself if you have unusual requirements.
