### ISSUE TITLE
Saving texture from Desktop Duplication API to PNG leads to washed out colors.

### ISSUE THREAD

**Issue by sskodje** [microsoft/DirectXTK#193]
When using September 22, 2017 version or newer, colors are washed out on textures saved with SaveWICTextureToFile to PNG format. I traced the problem to [this code block](https://github.com/microsoft/DirectXTK/blob/master/Src/ScreenGrab.cpp#L551), that sets the gAMA to 1.0. 

From the PNG specifications, it is stated:

> It is better to write a gAMA chunk with a value that is approximately correct than to omit the chunk and force PNG decoders to guess an approximate gamma. If a PNG encoder is unable to infer the gamma value, it is preferable to omit the gAMA chunk. If a guess has to be made this should be left to the PNG decoder.

Does this not mean that if you cannot infer the gamma value, it is better to not write the gAMA chunk at all, than to assume it is 1.0? If i remove the gAMA chunk with TweakPNG and lets the decoder handle it, the screenshots render correctly.

**Comment by walbourn** [comment]
This was done to explicitly resolve other issues with PNG readers, and the fact that otherwise the PNG always has an sRGB chunk when written by WIC.

The real question is what is the source render target format you are writing...

**Comment by sskodje** [comment]
The format of the texture from Desktop Duplication is DXGI_FORMAT_R8G8B8A8_UNORM.

**Comment by walbourn** [comment]
I'll see about adding a way to force the sRGB behavior through the function. You might consider using [DirectTex](https://github.com/microsoft/DirectXTex/wiki/DirectXTex) instead which gives you more control. You can use the ``WIC_FLAGS_FORCE_SRGB`` flag in that case to force the sRGB chunk.

**Comment by sskodje** [comment]
Alright. Thanks a lot for your help! I'll go with forcing the SRGB flag.

**Comment by walbourn** [comment]
I've addded the option to ``ScreenGrab`` as well in this [pull request](https://github.com/microsoft/DirectXTK/pull/194)

**Comment by walbourn** [comment]
Same issue for [DirectX Tool Kit for DX12](https://github.com/microsoft/DirectXTK12/pull/61)
