### ISSUE TITLE
Question: What's the impact of enabling XMVECTOR overloads?

### ISSUE THREAD

**Issue by aaronstackpole** [microsoft/DirectXTK#195]
I use the XMVECTOR overloads in some of my 2D calculations, as I've merged some of the DXTK code into my own library, I'm wondering what the impact of removing #define _XM_NO_XMVECTOR_OVERLOADS_ might be on the DXTK library?

**Comment by walbourn** [comment]
The ``XM_NO_XMVECTOR_OVERLOADS`` define is there to make sure I maintain compatibility with clang/LLVM. For details on what that's about, see [this issue](https://github.com/microsoft/DirectXMath/issues/50).  If you don't care about portability to non-Microsoft Visual C++ compilers then it's fine to remove in your code.
