### ISSUE TITLE
Automatic mip map selection with SpriteBatch and Default Vertex/Pixel Shader

### ISSUE THREAD

**Issue by BenBaron1985** [microsoft/DirectXTK#196]
Hi guys,

I am trying to work my way towards understanding the rendering pipeline with the help of DirectXTK...quite a long and rocky way, to be honest. I came so far as to being able to render different sprites from a spritesheet into a texture using SpriteBatch. But then, I came to notice that the sprites start to flicker as soon as the view moves away a certain distance from the object where the texture is rendered to. The spritesheet is created as ID3D11ShaderResourceView from a .dds file and it has 12 mip levels. But it seems they simply aren't being used, yet. At least, I created different colors for the different mip levels for testing and it is definitely only displaying level 0 regardless of the view's position to the object. I had the, maybe naive, impression this should work without employing a custom shader? But, maybe I do have to use one, if I want to use the correct mip levels? I've also already experimented by passing in a custom pixel shader but whatever I do it always comes down to either only mip level 0 being used employing the Texture.Sample() method or me setting a specific mip level directly via Texture.SampleLevel(). I am under the impression something crucial is missing for automatic mip map selection to work, but I really don't know what. 

Maybe someone would be so kind to enlighten the mind of quite a novice in the jungle of rendering what might be the missing piece here. Would be highly appreciated.

Thanks very much in advance and all the best,

Benny

**Comment by walbourn** [comment]
The default sampler for ``SpriteBatch`` is the "LinearClamp`` sampler from ``CommonStates``. This does use ``D3D11_FILTER_MIN_MAG_MIP_LINEAR`` so technically it could use mips if present.

That said, the ``SpriteBatch`` class is optimized for 2D rendering, so mips are typically unused. Mips select is based on the depth. Are you providing a ``layerDepth``?

**Comment by walbourn** [comment]
If you render using a traditional 3D pipeline (like say ``GeometricPrimitive`` or ``Model``, then mips are automatically selected based on view depth. Again, this is done by the sampler being set to a mipmap [filter mode](https://docs.microsoft.com/en-us/windows/win32/api/d3d11/ne-d3d11-d3d11_filter) and the texture resource itself having defined mip levels.
