### ISSUE TITLE
Need support for downlevel XAudio 2.9

### ISSUE THREAD

**Issue by walbourn** [microsoft/DirectXTK#198]
There is now a [NuGet package](https://www.nuget.org/packages/Microsoft.XAudio2.Redist/) for using XAudio 2.9 down-level on Windows 7 Service Pack 1, Windows 8.0, and Windows 8.1. See [Microsoft Docs](https://aka.ms/XAudio2Redist) for details.

I should provide instructions and updates needed to use this configuration.

**Comment by trojanfoe** [comment]
This has been a long time coming, but well done Microsoft for making things easier for us devs!

**Comment by walbourn** [comment]
See [this PR](https://github.com/microsoft/DirectXTK/pull/203)
