### ISSUE TITLE
Support for DirectX 12

### ISSUE THREAD

**Issue by walbourn** [Microsoft/DirectXTK#2]
DirectX Tool Kit currently supports DirectX 11.x. While not everything in the tool kit is applicable to DirectX 12, a subset of the graphics functionality makes sense.

* DDSTextureLoader 
* WICTextureLoader 
* ScreenGrab 
* SpriteBatch 
* SpriteFont 
* GeometricPrimitive 
* Model

DirectX 12 has a very different approach to state and shaders, so perhaps that would be best done by implementing a PSOFactory. This would likely be used in place of CommonStates and Effects for DirectX 12. 

 DirectXHelpers12 would be a good place for the new SetDebugObjectName template and an UpdateSubResource equivalent. 

 Also a GenerateMips helper since 'auto-gen' mips is not a DX12 feature. 

 A LinearAllocator for handling communication with the GPU is also essential.

Note that you can currently use DirectX Tool Kit in DX12 apps through Direct3D 11 interop. 

 Audio, GamePad, and SimpleMath work "as is".

**Comment by vinjn** [comment]
+1

**Comment by cybereality** [comment]
Yes. DirectX 12 support and generation of mip-maps would be helpful.

**Comment by bofinbabu** [comment]
+1 for SpriteBatch & SpriteFont

**Comment by tyoungjr** [comment]
Such a great code base. Thanks! +1 from me as well!

**Comment by ChrisKing340** [comment]
+1 for SpriteBatch

**Comment by walbourn** [comment]
This will take the form of a 'fork' of the project as DirectX12 is quite different than DirectX11. ETA for release is mid-July.

**Comment by ChrisKing340** [comment]
Great news. Thank you Chuck

**Comment by walbourn** [comment]
DirectX Tool Kit for DirectX 12 is hosted on it's own [GitHub](https://github.com/Microsoft/DirectXTK12)
