### ISSUE TITLE
CMake build does not use pre-compiled headers

### ISSUE THREAD

**Issue by trojanfoe** [microsoft/DirectXTK#200]
I have started using CMake to manage my game project since seeing that DirectXTK now supports CMake, however I have noticed that DirectXTK does not use pre-compiled headers when generated using CMake, and is a bit slow to build.

I am happy to generate a PR if you're not up for it?

Merry Christmas Chuck!

**Comment by walbourn** [comment]
I tried a few ways to get it setup and it was all quite messy... I now it's eaiser with add-ons like [cotire](https://github.com/sakra/cotire). If you have a PR to do it, I'll take a look

**Comment by trojanfoe** [comment]
https://github.com/microsoft/DirectXTK/pull/201

The changes for the library were pretty clean, but the changes for xwbtool are a bit gnarly.

**Comment by walbourn** [comment]
The robust solution was to use the new CMake 3.16 support for PCH. See [this commit](https://github.com/microsoft/DirectXTK/commit/dc7c0a2ee84d08a291388e10eecfbd66c794a021).

**Comment by trojanfoe** [comment]
Indeed; it's good that cmake finally has proper support for precompiled headers.  As well as Unity builds ?!? Oh well, hack begone.
