### ISSUE TITLE
directxtk build failure for x86-uwp #9486

### ISSUE THREAD

**Issue by mediabuff** [microsoft/DirectXTK#202]
#9486

   "C:\MyDevProjects\MyProjectsThirdPartyLibs\vcpkg2\vcpkg\buildtrees\directxtk\src\dec2019-b08f6255ba\DirectXTK_Windows10_2019.sln" (Rebuild target) (1) ->
   (ValidateSolutionConfiguration target) -> 
     C:\MyDevProjects\MyProjectsThirdPartyLibs\vcpkg2\vcpkg\buildtrees\directxtk\src\dec2019-b08f6255ba\DirectXTK_Windows10_2019.sln.metaproj : error MSB4126: The specified solution configuration "Release|Win32" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the default solution configuration. [C:\MyDevProjects\MyProjectsThirdPartyLibs\vcpkg2\vcpkg\buildtrees\directxtk\src\dec2019-b08f6255ba\DirectXTK_Windows10_2019.sln]

0 Warning(s)
1 Error(s)

Build FAILED.

   "C:\MyDevProjects\MyProjectsThirdPartyLibs\vcpkg2\vcpkg\buildtrees\directxtk\src\dec2019-b08f6255ba\DirectXTK_Windows10_2019.sln" (Rebuild target) (1) ->
   (ValidateSolutionConfiguration target) -> 
     C:\MyDevProjects\MyProjectsThirdPartyLibs\vcpkg2\vcpkg\buildtrees\directxtk\src\dec2019-b08f6255ba\DirectXTK_Windows10_2019.sln.metaproj : error MSB4126: The specified solution configuration "Release|Win32" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the default solution configuration. [C:\MyDevProjects\MyProjectsThirdPartyLibs\vcpkg2\vcpkg\buildtrees\directxtk\src\dec2019-b08f6255ba\DirectXTK_Windows10_2019.sln]

0 Warning(s)
1 Error(s)

**Comment by walbourn** [comment]
I don't directly maintain the vcpkg, but it's probably an issue with the metaproj.

VS 2017 renamed "Win32" to "x86" in the interface, but I simply upgraded the projects so they still have ``Win32`` inside the vcxproj.

**Comment by walbourn** [comment]
Note I've normalized all my ``sln`` files for desktop to use "x86" in [this commit](https://github.com/microsoft/DirectXTK/commit/9cac24555395925e3c1039bcbbae306da09742ed)
