### ISSUE TITLE
Markdown appearing in code box on "Writing custom shaders" Wiki page

### ISSUE THREAD

**Issue by cyberjaxx** [microsoft/DirectXTK#205]
Referring to the tutorial "Writing custom shaders" [https://github.com/Microsoft/DirectXTK/wiki/Writing-custom-shaders](url),  Markdown was inserted into the Html.  It appears in the code box that follows the instruction: 

In **Game.cpp**, add to **Render** just before the call to `Present`:

I'd include an example but since it is rendering the raw Markdown, it turns into formatted text here.  I'm sure that you will not have any problem seeing the issue.

**Comment by walbourn** [comment]
Thanks. It was three ticks to open but only two to close :(
