### ISSUE TITLE
Where to ask questions

### ISSUE THREAD

**Issue by rafalmlody12321** [Microsoft/DirectXTK#21]
Hi can you tell me where to ask question or leave comments etc. ? can I just ask here ?
Btw. my question is regarding "SpriteFont"  can you please tell me how many instances of SpriteFont I can create ? Should I use one SpriteFont to render as many text sprites possible or can I create multiple SpriteFont instances ?

**Comment by walbourn** [comment]
For general Q&A, you can still use the old [CodePlex discussion threads](https://directxtk.codeplex.com/discussions). I'm likely to stop updating the CodePlex projects in favor of the GitHub versions in 2016, but they do still exist and I still monitor them.

You generally create one ``SpriteBatch`` per Direct3D 11 device context. You have one ``SpriteFont`` for each font style and point-size you want to render with. You can use multiple SpriteFont instances with the same SpriteBatch. You can also use the same SpriteFont instance with different SpriteBatch instances if desired.

See [[SpriteBatch]], [SpriteFont](https://github.com/Microsoft/DirectXTK/wiki/SpriteFont), and the [drawing text](https://github.com/Microsoft/DirectXTK/wiki/Drawing-text) tutorial lesson.
