### ISSUE TITLE
GeometricPrimitive vertices order differs from default

### ISSUE THREAD

**Issue by rednewt** [microsoft/DirectXTK#210]
I was using the GeometricPrimitive class to get vertices/indices data for drawing some primitives instead of using built-in Draw functions but turns out that the order of vertices for Front Facing Triangles differs by the default type direct3d expects. I had to do this for it to work normally:

   ```
        CD3D11_DEFAULT def;
        CD3D11_RASTERIZER_DESC rasdesc(def);
	rasdesc.FrontCounterClockwise = TRUE;

	Microsoft::WRL::ComPtr<ID3D11RasterizerState> state;
	m_Device->CreateRasterizerState(&rasdesc, state.ReleaseAndGetAddressOf());

	m_ImmediateContext->RSSetState(state.Get());
```

Might want to look into this or is this already intended behavior?

**Comment by shawnhar** [comment]
My guess is you are using a left handed coordinate system?  See the "coordinate systems" section of https://github.com/Microsoft/DirectXTK/wiki/GeometricPrimitive

**Comment by rednewt** [comment]
> My guess is you are using a left handed coordinate system? See the "coordinate systems" section of https://github.com/Microsoft/DirectXTK/wiki/GeometricPrimitive

Yes I use left handed coordinate system and I am following the Introduction to 3D Programming using DirectX 11 by Frank Luna. I didn't knew these were based on XNA which uses right handed, thanks for that. The book has made me believe that left-handed coordinate system is the default one for DirectX so shouldn't the library return left-handed coordinates by default?

**Comment by rednewt** [comment]
Update: I changed the rhscoords parameter to = false and now I just get a blank screen instead of that crazy cube:
	`GeometricPrimitive::CreateCube(vertices, indices, false);`

**Comment by rednewt** [comment]
My god, I am stupid. I was setting size=false instead of rhscoords=false. Forgive me.
