### ISSUE TITLE
Windows desktop app using VS 2017 or VS 2019 for Windows 10(directxtk_desktop_win10)

### ISSUE THREAD

**Issue by sgf** [microsoft/DirectXTK#211]
what does the win10 mean?the development  OS enviroment? or the release target OS enviroment?

**Comment by sgf** [comment]
i got that from the blog https://walbourn.github.io/github-2020/
thanks

**Comment by walbourn** [comment]
It's also documented here on the [wiki](https://github.com/microsoft/DirectXTK/wiki/DirectXTK#using-project-to-project-references)
