### ISSUE TITLE
How to create multiple models with different .dds textures?

### ISSUE THREAD

**Issue by duplicate-vegetable** [microsoft/DirectXTK#213]
I‘m trying to create multiple Model class instances each with a different .dds texture using Model::CreateFromCMO, but then I got confused about that even the code runs fine (without any exceptions thrown) when drawing models, it always uses the .dds texture referenced in the first .cmo file loaded. How to make the textures correspond to the models?

**Comment by walbourn** [comment]
You should really try to share the model data as much as possible to save memory, so I'd suggest creating the 'master model' from the CMO, then clone it and modify the effects used (which is where the textures come from).

**Comment by duplicate-vegetable** [comment]
Thanks for the advice. I have solved the problem. After diving into EffectFactory's code, I found something that might be a bug: the effect caching use the texture name in the .cmo file, but multiple .cmo may use the same texture name for different texture file, which will prevent the loading of other materials.

**Comment by walbourn** [comment]
Generally you want to share textures between models. It's critical for overall memory usage. The most common way to do that is shared material names. You can of course turn off this sharing by using the ``SetSharing(false);`` method on an ``EffectFactory``.
