### ISSUE TITLE
Focus to object

### ISSUE THREAD

**Issue by WindowsNT** [microsoft/DirectXTK#214]
It's great, I could load the cup model correctly in my code. However what happens if the object is out of the projection area.

Is there a way to automatically "center" the object in question?

**Comment by walbourn** [comment]
Typically that's done by using a sphere radius bound of [the object (one is computed by the mesh loader) and using that to set view distance. See [DirectX Tool Kit Model Viewer](https://github.com/walbourn/directxtkmodelviewer)
