### ISSUE TITLE
Materials with the same name overwrite each other

### ISSUE THREAD

**Issue by alekasm** [microsoft/DirectXTK#230]
I've noticed that when I export to an obj/mtl combination and use the DirectX Mesh Convert tool to create the cmo, materials with the same name overwrite each other.

Example 1:
A.obj -> A.mtl
A.mtl has newmtl _2, newmtl_3

B.obj -> B.mtl
B.mtl has newmtl _2, newmtl_3

When I import the objects into my game the materials from A or B overwrite each other.

This is what the object looks like in Blender:
![image](https://user-images.githubusercontent.com/45739284/92862359-a118fe80-f3c8-11ea-9875-83e3c98ad82a.png)

Here is what it looks like in-game:
![image](https://user-images.githubusercontent.com/45739284/92862458-bc840980-f3c8-11ea-93a0-67b5c52a5e97.png)

Here is what other objects I have with deconflicted material names look like:
![image](https://user-images.githubusercontent.com/45739284/92862508-cad22580-f3c8-11ea-95a0-03c8976a1bad.png)

**Comment by walbourn** [comment]
Material "sharing" is an important strategy for controlling memory resource usage, so a common practice is to 'merge' all materials with the same name.

That said, you can easily turn this off by setting a flag on the ``IEffectFactory`` you are using. See [the wiki](https://github.com/microsoft/DirectXTK/wiki/EffectFactory#sharing).
