### ISSUE TITLE
Does this code contain alternatives to D3DXCreateTextureFromFileEx, D3DXCreateTextureFromFileInMemoryEx, D3DXCreateTexture, and D3DXCreateSprite?

### ISSUE THREAD

**Issue by AraHaan** [microsoft/DirectXTK#231]
I have some extra old code that I would love to port to dx11 (it uses mfc as well sadly and also oddly enough compile errors at ``wincodec.h`` from being included in the mfc headers)

the old code seems to include:
``d3d9.h``, ``d3dx9.h``, ``d3dx9math.h``, and ``DXErr9.h``.

The current found used types from ``d3dx9.h`` or from ``d3dx9math.h`` is: ``D3DXVECTOR4``, ``D3DXVECTOR3``, ``D3DXVECTOR2``, ``D3DXMATRIX``, ``D3DXCOLOR``.

It also uses ``D3DXCreateTextureFromFileEx``, ``D3DXCreateTextureFromFileInMemoryEx``, ``D3DXCreateTexture``, and ``D3DXCreateSprite``.

There is also dependency on these as well that I would love to figure out on changing to dx11 as well:
```cpp
#define D3DGENERALIZE(interf,pointer,ver) \
    typedef interf##ver interf; \
    typedef struct interf##ver  *LP##pointer, *P##pointer;

D3DGENERALIZE( IDirect3D, DIRECT3D, 9 )
D3DGENERALIZE( IDirect3DBaseTexture, DIRECT3DBASETEXTURE, 9 )
D3DGENERALIZE( IDirect3DCubeTexture, DIRECT3DCUBETEXTURE, 9 )
D3DGENERALIZE(IDirect3DDevice, DIRECT3DDEVICE, 9 )
D3DGENERALIZE( IDirect3DIndexBuffer, DIRECT3DINDEXBUFFER, 9 )
D3DGENERALIZE( IDirect3DPixelShader, DIRECT3DPIXELSHADER, 9 )
D3DGENERALIZE( IDirect3DQuery, DIRECT3DQUERY, 9 )
D3DGENERALIZE( IDirect3DResource, DIRECT3DRESOURCE, 9 )
D3DGENERALIZE( IDirect3DStateBlock, DIRECT3DSTATEBLOCK, 9 )
D3DGENERALIZE( IDirect3DSurface, DIRECT3DSURFACE, 9 )
D3DGENERALIZE( IDirect3DSwapChain, DIRECT3DSWAPCHAIN, 9 )
D3DGENERALIZE( IDirect3DTexture, DIRECT3DTEXTURE, 9 )
D3DGENERALIZE( IDirect3DVertexBuffer, DIRECT3DVERTEXBUFFER, 9 )
D3DGENERALIZE( IDirect3DVertexDeclaration, DIRECT3DVERTEXDECLARATION, 9 )
D3DGENERALIZE( IDirect3DVertexShader, DIRECT3DVERTEXSHADER, 9 )
D3DGENERALIZE( IDirect3DVolume, DIRECT3DVOLUME, 9 )
D3DGENERALIZE( IDirect3DVolumeTexture, DIRECT3DVOLUMETEXTURE, 9 )
typedef D3DADAPTER_IDENTIFIER9  D3DADAPTER_IDENTIFIER;
typedef D3DCAPS9                D3DCAPS;
typedef D3DCLIPSTATUS9          D3DCLIPSTATUS;
typedef D3DLIGHT9               D3DLIGHT;
typedef D3DMATERIAL9            D3DMATERIAL;
typedef D3DVIEWPORT9            D3DVIEWPORT;
```

Sorry to ask about these functions and conversion from dx9 -> 11 here I simply do not know dx much really.

I just really want to modernize my program to use (if possible) the Windows sdk, and possibly the things from this github repository and eliminate the project's local version of the outdated dxsdk that might be a thing causing compile conflicts in the code (especially when targeting c++20).

**Comment by walbourn** [comment]
See [this blog post](https://walbourn.github.io/living-without-d3dx/)
