### ISSUE TITLE
Post processing helpers spams warnings when using MSAA enabled SRVs as source texture

### ISSUE THREAD

**Issue by IronicallySerious** [microsoft/DirectXTK#235]
Without MSAA, the post-processing works correctly. With MSAA, the post-processing works correctly too, however, it sends out a warning every time `Process()` is called:

```
D3D11 ERROR: ID3D11DeviceContext::Draw: The Shader Resource View dimension declared in the shader code (TEXTURE2D) does not match the view type bound to slot 1 of the Pixel Shader unit (TEXTURE2DMS).  This mismatch is invalid if the shader actually uses the view (e.g. it is not skipped due to shader code branching). [ EXECUTION ERROR #354: DEVICE_DRAW_VIEW_DIMENSION_MISMATCH]
```
I am using `BasicPostProcess` first so I caught this after the draw call in `BasicPostProcess::Impl::Process()`.

I suspect this might be because of `BasicPostProcess::SetSourceTexture()` not going over the MS versions of the texture format of the incoming SRV.

**Comment by walbourn** [comment]
So in a typical rendering with post-process pipeline, you resolve MSAA *before* you perform post-processing:

    Render w/ MSAA -> Resolve render target -> PostProcess -> SwapChain (non-MSAA)

You should avoid creating your swapchain with MSAA as this just creates an additional layer of swapchains not under your control. See the SimpleMSAA samples on [GitHub](https://github.com/microsoft/Xbox-ATG-Samples/tree/master/UWPSamples/IntroGraphics).

**Comment by IronicallySerious** [comment]
Thanks! I was able to fix this by following your advice on resolving the MSAA texture before post-processing. It also added a small performance bump as well probably because all the render targets are suddenly not 4x large
