### ISSUE TITLE
Wiki: CommonStates > Sampler State > Typical usage: a typo in Anisotropic (Ansiotropic)

### ISSUE THREAD

**Issue by Marat-Tanalin** [microsoft/DirectXTK#238]
There is a typo (swapped i and s) in the Anisotropic word in the first sentence in the “[Sampler State → Typical usage](https://github.com/microsoft/DirectXTK/wiki/CommonStates#typical-usage-3)” section of the “CommonStates” wiki article.

> For improved mipmap filtering quality use the **Ansiotropic** settings.

Didn’t find a way to create a pull request for a wiki page.

**Comment by walbourn** [comment]
Thanks for the report. Fixed.

> I used to edit the docs with the website, but now use Atom to I get spellcheck :)
