### ISSUE TITLE
Abort() has been called when trying to run the exe in windows 10 visual studio 2019 

### ISSUE THREAD

**Issue by ssshammi** [microsoft/DirectXTK#239]
![image](https://user-images.githubusercontent.com/2300969/96804487-0cfa7800-1407-11eb-8acc-47e86bb942f1.png)
Hi when i try to run the exe from the bin folder Debug x64 and win32 It will abort, I did migrate the project to visual studio 2019. I am using windows 10 home.

**Comment by walbourn** [comment]
This mostly likely means that an assert has triggered.

**Comment by ssshammi** [comment]
@walbourn thanks it was because of a font file that I did not include in the debug folder. And the exe would abbort. Is there a way to duplicate the entries while release or debug so the executable contains all the files with dependency I'm using visual studio 2019.

**Comment by walbourn** [comment]
Win32 desktop development doesn't have a notion of 'packaging' like UWP or Xbox. Desktop apps are usually developed 'in place' and then later repacked as part of some kind of installer.

For examples of coping with this see [ReadData.h](https://raw.githubusercontent.com/wiki/microsoft/DirectXTK/ReadData.h) and [FindMedia.h](https://github.com/microsoft/Xbox-ATG-Samples/blob/master/Kits/ATGTK/FindMedia.h).
