### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by nlguillemot** [Microsoft/DirectXTK#24]
I'd like a simple list of steps to add this library to an existing project. I'm not sure what I'm supposed to do with all this code and all these project files.

**Comment by shawnhar** [comment]
Start here:  https://github.com/Microsoft/DirectXTK/wiki/Adding-the-DirectX-Tool-Kit

**Comment by nlguillemot** [comment]
That article is spot on! I recommend putting a link to it in the README or in an INSTALL file, that's what I was looking for. Or maybe there should be a link to the "Getting Started" page.

**Comment by nlguillemot** [comment]
I see there's already a link to the documentation in README, so maybe it's just me that missed it. :)
