### ISSUE TITLE
ThrowIfFailed and COM ptr removal question

### ISSUE THREAD

**Issue by aaronstackpole** [microsoft/DirectXTK#241]
Have the VSIX project templates been updated to support the removal of the wrl/client components? The template that I have still tries to call ThrowIfFailed, could use some examples of how to get these things working on the newer DXTK.

**Comment by walbourn** [comment]
``wrl\client.h`` supports Win32 desktop on older versions of Windows, UWP, and Xbox. More specifically I use it consistently for  the``Microsoft::WRL::ComPtr`` smart-pointer in all my code to manage the "COM lite" aspects of DirectX. See [Microsoft Docs](https://docs.microsoft.com/en-us/windows/win32/prog-dx-with-com) and [the wiki](https://github.com/Microsoft/DirectXTK/wiki/ComPtr). There really isn't any other COM smart-pointer that is as ubiquitous in all the platforms I target.

I use ``ThrowIfFailed`` for fast-fail scenarios in all my code as well. For the [directx-vs-templates](https://github.com/walbourn/directx-vs-templates) it's always implemented in the ``pch.h`` and it's implemented using standard C++ exception handling. See [ThrowIfFailed](https://github.com/Microsoft/DirectXTK/wiki/ThrowIfFailed).

**Comment by aaronstackpole** [comment]
Thanks, I found the updated samples repo with the newer DeviceResources, I haven't updated this for a while so my older code still was calling that, looks like you just started throwing the exception on the spot in the code when needed. The new pch I imported didn't seem to have the function in it, I still have it in my old one, I suppose it probably still works...

I was actually very happy to see the removal of the wrl/client when I was doing this update last weekend!
