### ISSUE TITLE
not able to make audio work in directx11.1  and windows 10 

### ISSUE THREAD

**Issue by ssshammi** [microsoft/DirectXTK#244]
hi i am using windows 2015 desktop sdk. the audio is not playing in windows 10. do i need to enable a flag. or #ifdef DXTK_AUDIO? Please help

**Comment by walbourn** [comment]
It sounds like you may be looking at and older version of the DirectXTK Simple Sample. The latest one is on [GitHub](https://github.com/walbourn/directxtk-samples)

**Comment by ssshammi** [comment]
@walbourn thank you it works with the older version as well and just the flag needed to be defined DXTK_AUDIO. I am working on the older one as this in the one I worked on during my lab work. Also I am looking to implement animation some models come with animation and rigged. So wanted to know if we have any learning resources for that. Or examples. Thanks a tone. I have to complete my coursework before Christmas.
