### ISSUE TITLE
[Question] XMA2WAVEFORMATEX packing

### ISSUE THREAD

**Issue by flibitijibibo** [microsoft/DirectXTK#256]
Hey there!

I'm working on something that uses the XMA2 format, and when looking up the data types I noticed that the struct for XMA2WAVEFORMATEX is tightly packed in this project:

https://github.com/microsoft/DirectXTK/blob/5fec479daffcb2a4e13c5fd248d296c8e994b0ec/XWBTool/xwbtool.cpp#L66-L92

This makes sense to me at least, considering every WAVEFORMATEX has always been packed (as far as I know, anyway) but when looking at the original xma2defs.h type, there's no sign of packing anywhere:

https://github.com/hrydgard/minidx9/blob/master/Include/xma2defs.h

Are we missing a pragma somewhere? Or has the packing changed since the last DXSDK released?

**Comment by walbourn** [comment]
I may have made a mistake in xwbtool. Let me check

**Comment by walbourn** [comment]
So the key thing is that the structure is 52 bytes. pack(1), pack(4), pack(8), pack(16) all produce the same layout for x86 and x64, so really the pack statements in xwbtool are misleading.

**Comment by walbourn** [comment]
Updated code in [this commit](https://github.com/microsoft/DirectXTK/commit/924dd33fba3bef3dc824ca4e98d76bc7c6fe42db)

**Comment by flibitijibibo** [comment]
Excellent, thanks for the help!
