### ISSUE TITLE
UML Diagram of Effect Classes

### ISSUE THREAD

**Issue by Jakeman893** [Microsoft/DirectXTK#26]
I think it would be very useful for the wiki to include a UML diagram of all the Effect classes. I have been learning about the connections between the effect interfaces through the current wiki articles as well as reading the code and it has been an encumbrance.

I feel that a proper UML diagram would go a long way in helping those like me that would like to expand upon the Effect classes present.

**Comment by walbourn** [comment]
Is [this](https://raw.githubusercontent.com/wiki/Microsoft/DirectXTK/images/effectsuml.PNG) useful?

**Comment by Jakeman893** [comment]
Yes! This is great, thanks

**Comment by walbourn** [comment]
I'll add the link to the page on Effects.
