### ISSUE TITLE
[Documentation] Just a lacking round bracket

### ISSUE THREAD

**Issue by raphasanori** [microsoft/DirectXTK#261]
Hi!

I found a minuscule problem in the Wiki~

**Page:** https://github.com/microsoft/DirectXTK/wiki/Simple-rendering#drawing-a-triangle
**Location:** Code under `Optional: You can simplify the last part using DirectXHelpers:`

```C++
DX::ThrowIfFailed(
    CreateInputLayoutFromEffect<VertexType>(m_d3dDevice.Get(), m_effect.get(),
        m_inputLayout.ReleaseAndGetAddressOf()
    ); // <- [Problem location]
```

Just needs an extra round bracket to close **DX::ThrowIfFailed**!

Thanks for your attention!

**Comment by walbourn** [comment]
Thanks for the report. Fixed.
