### ISSUE TITLE
[Documentation] Typo

### ISSUE THREAD

**Issue by raphasanori** [microsoft/DirectXTK#262]
Hi!

Just reporting another typo.

**Page:** https://github.com/microsoft/DirectXTK/wiki/Model#initialization
**Location:** Code under `See the Visual Studio 3D Starter Kit for details (Windows 8.1, Windows 8.0).`

> _**--**_ m_fx = std::make_un**qi**ue<DGSLEffectFactory>(device);
> _**++**_ m_fx = std::make_un**iq**ue<DGSLEffectFactory>(device);

**Comment by walbourn** [comment]
Fixed. Thanks.
