### ISSUE TITLE
Mouse has jerky movement at higher sensitivities

### ISSUE THREAD

**Issue by jkinz3** [microsoft/DirectXTK#267]
Using the mouse state deltas directly works but is slow. If you scale the deltas up, diagonal movement is jerky. It seems like this is a result of the deltas being stored as integers. Is this intentional? If it is, how can I make mouse movement smoother?

![diag_2](https://user-images.githubusercontent.com/6319937/123530016-99a6b580-d6bb-11eb-8179-aa25303fb12e.gif)

**Comment by walbourn** [comment]
This is for the projects [here](https://github.com/walbourn/directxtkmodelviewer) and [here](https://github.com/walbourn/directxtk12modelviewer) rather than the *DirectX Tool Kit* itself...

Looking at the code, part of the problem is I think I used elapsedTime too many times:

```
            Vector3 delta;
            if (kb.LeftShift || kb.RightShift)
            {
                delta = Vector3(0.f, 0.f, -float(mouse.y) * handed) * m_distance * elapsedTime;
            }
            else
            {
                delta = Vector3(-float(mouse.x), float(mouse.y), 0.f) * m_distance * elapsedTime;
            }
...
    m_cameraFocus += delta * elapsedTime;
```

**Comment by jkinz3** [comment]
Apologies for submitting this on the wrong project. I wasn't paying enough attention. 
However, the reason I used the model viewer project in the gif was to show that it wasn't a problem specific to my project. This occurs in my project as well.
Thank you for responding so quickly! I really appreciate it
