### ISSUE TITLE
2D Primitives?

### ISSUE THREAD

**Issue by aaronstackpole** [microsoft/DirectXTK#271]
I see Direct2D has some basic geometries, is it possible to use Direct2D at the same time as sprite batch? If not, is there something similar for 2D primitives?

**Comment by walbourn** [comment]
If you need "presentation graphics" like filled circles, rounded rectangles, etc. then you should use Direct2D. Interop with Direct3D 11 is covered on [Microsoft Docs](https://docs.microsoft.com/en-us/windows/win32/direct2d/direct2d-and-direct3d-interoperation-overview).

**Comment by aaronstackpole** [comment]
What I was meaning was it might be helpful to have a set of wrapper classes that present easy to use 2D vector graphics options. As an example, perhaps a DirectX::Line2D(Vector2 start, Vector2 end) that could be rendered in the same layer as the spritebatch/spritefont. What I'm getting at here is some simple UI drawing controls. Right now, I'm just using a square black texture, but it seems overkill for doing simple things like drawing lines on the screen, for example, to highlight the edges of a box. Just a thought while working through building a UI system using what we have in DXTK for graphics options.

**Comment by walbourn** [comment]
For basic drawing of single-pixel points, lines, triangles, quads, and n-gons, that's what [PrimitiveBatch](https://github.com/Microsoft/DirectXTK/wiki/PrimitiveBatch) is designed to do.

You can actually do a lot of drawing of 'filled rectangles' using just ``SpriteBatch`` by using a single-pixel white texture and then using the tinting controls. I used this technique in my [SampleGUI](https://github.com/microsoft/Xbox-ATG-Samples/tree/master/Kits/ATGTK) helper to try to keep drawing as simple as possible. It's functional, but certainly is a long-way from a professional-looking UI.

**Comment by aaronstackpole** [comment]
I suppose it's about time for me to just get my head wrapped around the transform you're using to put things on the "2D" plane. AKA, time to put on my big boy shoes and actually learn the math ;)

**Comment by walbourn** [comment]
I try to sum it up [here](https://github.com/microsoft/DirectXTK/wiki/Simple-rendering#pixel-vs-normalized-coordinates).

In short: The coordinates actually used by Direct3D to render are 'normalized': -1 to 1 in x, -1 to 1 in y, with 0,0 in the dead center.

```
+-------------------------------+
| -1,1                       1,1|
|                               |
|            0,0                |
|                               |
|-1,-1                      1,-1|
+-------------------------------+
```

All that the 2D transform is doing is flipping the y, sliding it over by -1, and scaling everything by 2.

That means you feed in data that looks like a simple 'pixel coordinate system' like below:

```
+-------------------------------+
| 0,0                    width,0|
|                               |
|                               |
|                               |
|0,height           width,height|
+-------------------------------+
```

and the transform puts it into the 'normalized' range so it ends up in the right place in your actual screen. This of course only works if you set up the transform to match up with the render target's actual size and set the viewport via ``SetViewport``--the hardware always converts the normalized -1,-1 to 1,1 range into pixels based on the viewport. In fact, if you created a transform based on the size of a 1080p render target (1920×1080) and set the viewport via ``SetViewport`` to 1080p, then it everything would be relatively laid out the same place if your render target was actually 4k (3840 × 2160)--although the individual things you drew would of course be twice as many pixels in each dimension.

**Comment by aaronstackpole** [comment]
That's awesome, so, several years ago I did actually go through all of those demos and was able to get all of that working, but it's easy to just monkey-see monkey-do, I'm now going through this stuff knowing what I'm doing writing code and designing software, and it's just shaking loose all the cobwebs now :)

And after that explanation it's almost obvious as water is wet. Thanks!

**Comment by walbourn** [comment]
The only tricky bit to the transform matrices used by 2D and 3D graphics really is the idea of *homogenous coordinates*. This is why for 2D you use 3x3 matrices and for 3D you use 4x4 matrices. This is also why you explicitly or implicitly use ``[x y 1]`` and ``[ x y z 1]`` for 2D and 3D vectors respectively.

This "math trick" lets you put translation into the same matrix as rotation and scale. In fact, this lets you put projection in as well all into the same matrix (but in the case of projection, you need to need to divide the result by the final value to ensure it ends up back at 1 to have physical meaning).

> Honestly, in 30 years of graphics work, the math I've used most often has just been the matrix stuff. In the end, most of the super-fancy math solutions for advanced things like Spherical Harmonics or Physically-Based Rendering get all factored around so in the end, it's just a bunch of dot-products :)
