### ISSUE TITLE
NormalMapEffect DDSTextureLoader E_INVALIDARG

### ISSUE THREAD

**Issue by alekasm** [microsoft/DirectXTK#276]
I don't intend to use this issue section as a tech help section, but I believe I've ran into an issue with either DirectXTK or the documentation. When I revert back to BasicEffect, everything works as intended (obviously, since the issue is with the texture loading).

I've used these two as references:
https://github.com/microsoft/DirectXTK/wiki/NormalMapEffect
https://github.com/microsoft/DirectXTK/wiki/Using-advanced-shaders

Attached is my normalMap.dds (in a zip since I cant attach a dds). which was created from a 1x1 single white pixel. Then I followed the instructions for loading the texture. 
[normalMap.zip](https://github.com/microsoft/DirectXTK/files/6950007/normalMap.zip)

From the high level:
![image](https://user-images.githubusercontent.com/45739284/128616189-83755699-9fbf-46b2-a46e-bd9e7c67f4f3.png)

Then the actual debugging:

![image](https://user-images.githubusercontent.com/45739284/128616190-ab607a98-bba6-4f24-89a5-b0431f567dfe.png)

**Comment by alekasm** [comment]
Just to be clear, the issue stems from E_INVALID arg being thrown by DirectX11 CreateTexture2D which is called from within the DDSTextureLoader helper.

**Comment by walbourn** [comment]
You can't create a 1x1 Block Compressed Texture in Direct3D. It has to be 4x4 in pixel size if it's BC, which is why it fails to create. For mipmapped BC formats, there's some special handling for 4x1, 4x2, 2x1, 1x1 case, etc. but the 'top level' must still be 4x4.

You can use an RGB format instead for a 1x1. 

You can also create a 1x1 texture with code:

```cpp
static const uint32_t s_pixel = 0xffffffff;

D3D11_SUBRESOURCE_DATA initData = { &s_pixel, sizeof(uint32_t), 0 };

CD3D11_TEXTURE2D_DESC texDesc(DXGI_FORMAT_R8G8B8A8_UNORM, 1, 1, 1, 1, D3D11_BIND_SHADER_RESOURCE, D3D11_USAGE_IMMUTABLE);

ComPtr<ID3D11Texture2D> tex;
DX::ThrowIfFailed(device->CreateTexture2D(&texDesc, &initData, tex.GetAddressOf()));
DX::ThrowIfFailed(device->CreateShaderResourceView(tex.Get(), nullptr, m_defaultTex.ReleaseAndGetAddressOf()));
```
