### ISSUE TITLE
Compile the fx file

### ISSUE THREAD

**Issue by xiaoyang-git** [Microsoft/DirectXTK#28]
I have change something in a fx file, and I try to compile it by the ComplieShaders.cmd but failed.
please tell me how to compile the fx file ?

**Comment by walbourn** [comment]
You need to run CompileShaders.cmd from a Visual Studio Command Prompt since FXC.EXE must be in the path.

This is covered in the [wiki](https://github.com/Microsoft/DirectXTK/wiki/DirectXTK#hlsl-shaders)

**Comment by xiaoyang-git** [comment]
Thank you very much ! The problem is resovled
