### ISSUE TITLE
Rendering a model Tutorial - Meshconverter FAILED with an unspecified error

### ISSUE THREAD

**Issue by MasterDrake** [microsoft/DirectXTK#288]
Hi, I was reading the tutorial about how to load an render a model with this TK using the provided files and I run into this problem.
No matter what file I've tried or how many times I tried, it always fails at loading the .obj file with an unhelpful error (80004005)

![image](https://user-images.githubusercontent.com/51087997/139106030-d59db660-f866-438a-bc3d-c6a69494c7d0.png)

According to the source code, it fails at the LoadFromOBJ function, where the WaveFrontReader doesn't read the vertices/indices:
(  
  if (wfReader.indices.empty() || wfReader.vertices.empty())
        return E_FAIL;
)

But how and why?
What am I doing wrong?
I've tried with other .obj files as well with no luck...

Thanks for you time and sorry to bother you!

**Comment by walbourn** [comment]
Fixed in the November 2021 release

https://github.com/microsoft/DirectXMesh/releases/tag/nov2021
