### ISSUE TITLE
Windows 7 and CreateFile2.

### ISSUE THREAD

**Issue by nikitablack** [Microsoft/DirectXTK#29]
Somehow on my machine with Windows 7 `_WIN32_WINNT` is `0x0603` and `_WIN32_WINNT_WIN8` is `0x0602`. This is used in `DDSTextureLoader.cpp` and causes problems because `CreateFile2()` function is available starting from Windows 8.

**Comment by shawnhar** [comment]
These settings are determined by your project file, not by what computer you build the code on.  If you don't explicitly define them, they will default to whatever version of the Windows SDK you are using to compile against.

If you want to target a specific version of Windows that's older than the SDK you are using, you should explicitly set _WIN32_WINNT in your project settings.

**Comment by nikitablack** [comment]
Thank you.

**Comment by walbourn** [comment]
See [MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/aa383745.aspx)
