### ISSUE TITLE
The tutorial "Using skinned models" lacks some Code to update the animation model

### ISSUE THREAD

**Issue by pupymk1** [microsoft/DirectXTK#290]
Hi there!
I found in the tutorial [Using skinned models](https://github.com/microsoft/DirectXTK/wiki/Using-skinned-models)

Within this section:
```
In Game.cpp, add to the TODO of Update:

float time = float(timer.GetTotalSeconds());
m_world = XMMatrixRotationY(time);
```

I guess there should be `m_animation.Update(elapsedTime);` to compute the current animation time.
BTW I really appreciate you for writing the whole tutorial, Good Job!

**Comment by walbourn** [comment]
You are quite right. Cut & paste error :(

Fixed.

```
m_animation.Update(elapsedTime);

float time = float(timer.GetTotalSeconds());
m_world = XMMatrixRotationY(time);
```

**Comment by walbourn** [comment]
Same problem in the DirectX 12 tutorial fixed [there](https://github.com/microsoft/DirectXTK12/wiki/Using-skinned-models) as well.
