### ISSUE TITLE
SaveDDSTextureToFile doesn't return

### ISSUE THREAD

**Issue by YueLu0116** [microsoft/DirectXTK#291]
Today I used `SaveDDSTextureToFile` to dump frames every 1min for debugging, but after saving 2~3 images, this function didn't return and the thread was blocked by it. Does anyone has experience on how to solving this issue? I checked the logs, but no information was printed by it.

**Comment by walbourn** [comment]
As with all uses of ``ID3D11DeviceContext`` this function is *not* thread-safe. You need to make sure you are not continuing to use the immediate context while this function is running.
