### ISSUE TITLE
Win32 mouse input issue: WM_MOUSEWHEEL and WM_MOUSEHWHEEL

### ISSUE THREAD

**Issue by Demonese** [microsoft/DirectXTK#294]
WM_MOUSEWHEEL and WM_MOUSEHWHEEL using screen coordinate system:

> lParam
> The low-order word specifies the x-coordinate of the pointer, relative to the upper-left corner of the screen.
> The high-order word specifies the y-coordinate of the pointer, relative to the upper-left corner of the screen.

but other mouse messages are:

> lParam
> The low-order word specifies the x-coordinate of the cursor. The coordinate is relative to the upper-left corner of the client area.
> The high-order word specifies the y-coordinate of the cursor. The coordinate is relative to the upper-left corner of the client area.

so it is wrong:

```c++
    if (pImpl->mMode == MODE_ABSOLUTE)
    {
        // All mouse messages provide a new pointer position
        int xPos = static_cast<short>(LOWORD(lParam)); // GET_X_LPARAM(lParam);
        int yPos = static_cast<short>(HIWORD(lParam)); // GET_Y_LPARAM(lParam);

        pImpl->mState.x = static_cast<int>(static_cast<float>(xPos) * pImpl->mScale);
        pImpl->mState.y = static_cast<int>(static_cast<float>(yPos) * pImpl->mScale);
    }
```

in my application, I specialize WM_MOUSEWHEEL and WM_MOUSEHWHEEL message:

```c++
	case WM_MOUSEHWHEEL:
		if (_event)
		{
			POINT pos = { GET_X_LPARAM(arg2), GET_Y_LPARAM(arg2) };
			MapWindowPoints(NULL, window, &pos, 1); // should always succeed
			_event->onPointerWheel(f32x2(0.0f, (f32)GET_WHEEL_DELTA_WPARAM(arg1) / (f32)WHEEL_DELTA), f32x2(pos.x, pos.y));
		}
		return 0;
	case WM_MOUSEWHEEL:
		if (_event)
		{
			POINT pos = { GET_X_LPARAM(arg2), GET_Y_LPARAM(arg2) };
			MapWindowPoints(NULL, window, &pos, 1); // should always succeed
			_event->onPointerWheel(f32x2(0.0f, (f32)GET_WHEEL_DELTA_WPARAM(arg1) / (f32)WHEEL_DELTA), f32x2(pos.x, pos.y));
		}
		return 0;
```

**Comment by walbourn** [comment]
The documentation on Microsoft Docs for both [WM_MOUSEHWHEEL](https://docs.microsoft.com/en-us/windows/win32/inputdev/wm-mousewheel) and [WM_MOUSEHWHEEL](https://docs.microsoft.com/en-us/windows/win32/inputdev/wm-mousehwheel) state the exact same thing for the coordinates:

> The low-order word specifies the x-coordinate of the pointer, relative to the upper-left corner of the screen.

> The high-order word specifies the y-coordinate of the pointer, relative to the upper-left corner of the screen.

I also see no difference at all in your code for handling these messages. Both cases are identical.

In any case, I don't currently expose the horizonal scroll wheel through the ``Mouse`` abstraction since it's not a common feature on most mice. If I ever get a mouse that supports it, I'll try it out.

**Comment by walbourn** [comment]
I have a new mouse with the HWHEEL, so I'll try that out now...

**Comment by walbourn** [comment]
I did find a bug where in the UWP implementation of Mouse, I was merging the Vertical and Horizonal scroll wheel together, but that shouldn't impact your Win32 scenario.
