### ISSUE TITLE
DXGI_COLOR_SPACE_TYPE is undefined.

### ISSUE THREAD

**Issue by doncot** [Microsoft/DirectXTK#30]
I'm trying to use DDSTextureLoader.
When I include DDSTextureLoader.h, Visual Studio complains that "DXGI_COLOR_SPACE_TYPE" is missing at "c:\program files (x86)\windows kits\10\include\10.0.10586.0\um\d3d11_1.h(2680)".
Logically, I can force to compile this by adding my own DXGI_COLOR_SPACE_TYPE definition before the include macro, but I want to run it without the obnoxious hack.
What gives?

**Comment by shawnhar** [comment]
Check your include path - I suspect you are pulling in files from more than one different version of the DirectX headers, or perhaps you've manually copied DirectX headers into your project or to some unusual place on your machine?

DXGI_COLOR_SPACE_TYPE is defined by dxgitype.h, which is include by dxgi.h , which is included by dxgi1_2.h, which is included by d3d11.1.h.  To be missing that definition, you must somehow be pulling in a wrong version of one of those files.

**Comment by walbourn** [comment]
Most likely you are mixing the Windows 8.x SDK and the legacy DirectX SDK incorrectly. See [MSDN](https://msdn.microsoft.com/en-us/library/windows/desktop/ee663275.aspx). The _DirectX Tool Kit_ does not require any use of the legacy DirectX SDK *except* when using XAudio 2.7 on Windows 7. See [The Zombie DirectX SDK](https://blogs.msdn.microsoft.com/chuckw/2015/03/23/the-zombie-directx-sdk/) and [XAudio2 and Windows 8](https://blogs.msdn.microsoft.com/chuckw/2012/04/02/xaudio2-and-windows-8/)

**Comment by doncot** [comment]
Thanks for the advise. Actually, my include path was fine (I think) and I wasn't using legacy DirectX.
After some working around, I was able to solve the problem by re-targeting the platform sdk version to 10.0.10586.0 in the project's context menu and things started to be fine.
Dunno exactly why it worked though.
