### ISSUE TITLE
VertexPositionColor is not coloring

### ISSUE THREAD

**Issue by aaronstackpole** [microsoft/DirectXTK#306]
I'm running into a strange problem where I'm following the Simple Rendering tutorial and the triangle is drawing in white instead of yellow or colored. I am also running the 2D sprite batch at the same time, I'm wondering if this might be impacting the primitive batch somehow in this simple example?

This image shows my code, my engine systems make some of these calls simpler.
![image](https://user-images.githubusercontent.com/8165121/156279851-e0794c32-beda-4a5e-a4ba-d2f63ec3ea5b.png)

When running, the triangle (is drawing white)
![image](https://user-images.githubusercontent.com/8165121/156279942-0e2afe29-a989-43dd-98eb-a6084936212f.png)

**Comment by walbourn** [comment]
Many of the effects use different shaders (and therefore different input layouts) depending on the options set. The 'default' shader for BasicEffect does *not* have per-vertex color enabled, so it won't use "color" in VertexPositionColor.

You need to do:

```
m_effect  = std::make_unique<VertexType>(...);
m_effect->SetVertexColorEnabled(true);

CreateInputLayoutFromEffect<VertexType>(..., m_effect.get(), ...);
```

**Comment by aaronstackpole** [comment]
Thanks, Chuck. Was easy enough fix, guess I missed transcribing that line ;)

![image](https://user-images.githubusercontent.com/8165121/156360891-c89e1db3-d938-48ea-aa60-86c12ad0f767.png)
