### ISSUE TITLE
Clarify how to use CreateFromVBO

### ISSUE THREAD

**Issue by aaronstackpole** [microsoft/DirectXTK#307]
I have a component VoxelFarm that generates data in a VBO format (vertices in trios of floats) but I've been unable to figure out how to use CreateFromVBO function, I'm not sure what is exactly wrong, but I think I'm not giving it the IEffect correctly?

![image](https://user-images.githubusercontent.com/8165121/156780695-503f8fdd-d215-4811-b36a-c36b5b1d96eb.png)

Any guidance on what CreateFromVBO (non-file override) is expecting would be helpful, thanks Chuck!

**Comment by aaronstackpole** [comment]
![image](https://user-images.githubusercontent.com/8165121/156784939-a758674c-cad0-4e40-a8d1-66399e5e9b14.png)
Is the straight buffer code, which _seemed_ to work, although I was not able to actually see anything on the screen, but there is an explanation for that, so I'm less worried. When the Draw is commented out the app chugs on each Draw call, so I'm assuming it's doing... something :D

**Comment by aaronstackpole** [comment]
Digging a bit deeper into the CreateFromVBO non-file override, it goes in there and makes basically the same buffer I'm making, so I might be on the right track to figuring out what the function call needs. I have tried so many things lol that red squiggle just won't relent ;)

**Comment by aaronstackpole** [comment]
I think I figured it out, the VBO is looking to make VertexPositionNormalTexture, this buffer contains VertexPosition only, would it be possible to templateize CreateFrom* functions to be able to specify the vertex type? Feature request, basically.

**Comment by walbourn** [comment]
The ``VBO`` format is super simple, so it only supports the one vertex layout and only supports 16-bit indexes.
