### ISSUE TITLE
About CreateWICTextureFromFileEx decoding heif image taken by iphone

### ISSUE THREAD

**Issue by ByteYIFFF** [microsoft/DirectXTK#313]
There is a color difference between the texture extracted in CreateWICTextureFromFileEx and the image data decoded by libheif. For heif format images taken by iphone, does CreateWICTextureFromFileEx process the icc profile internally?

**Comment by walbourn** [comment]
Generally speaking, WIC assumes sRGB for all formats with bits-per-pixel of 8 or less, so I would guess yes.
