### ISSUE TITLE
Point Light and shader extension

### ISSUE THREAD

**Issue by MohammadMDSA** [microsoft/DirectXTK#314]
Hi
Is there any effect or techniques that I can implement point light with in the library? I search whole repo source and couldn't find any.
And also, shader files ".fx"s are so confusing and I could find out where are entrypoints and even how an Effect class create shaders from source/compiled files. Can you guide me so I can extend existing shader files to implemen unavailable features?

**Comment by walbourn** [comment]
The XNA Game Studio "BasicEffect" shaders did not implement point lights, although it's fairly easy to create a point-light shader.

For the basics of writing a custom effect, take a look at [this tutorial](https://github.com/microsoft/DirectXTK/wiki/Authoring-an-Effect).

The source for the BasicEffect shaders all came from the XNA Game Studio 4 [StockShaders](https://github.com/SimonDarksideJ/XNAGameStudio/tree/archive/Samples/StockEffectsSample_4_0/StockEffects) sample.
