### ISSUE TITLE
SoundEffectInstance documentation

### ISSUE THREAD

**Issue by cpyburn** [microsoft/DirectXTK#321]
Is there a way to reuse a SoundEffectInstance or do you have to reset the pointer and create a new SoundEffectInstance?  Documentation is not clear, and during testing it seems like this is the case, but also seems like you should be able to reuse an instance, nothing has changed except for that it was played.

**Comment by walbourn** [comment]
A `SoundEffectInstance` object is associated with a specific WAV or entry in a XMB, and owns a single XAudio2 voice. You can start it, stop it, loop it, etc. If you want to play a different sound *or* if you want more than once instance of same sound playing, you need a new `SoundEffectInstance` object.

The `SoundEffectInstance` implementation is very light-weight. All the audio data is owned by a `SoundEffect` or `WaveBank`. The XAudio2 voice is actually 'owned' by the `AudioEngine` which manages voice reuse for you.

**Comment by cpyburn** [comment]
Thanks for the clarification, just want to make sure I am using it correctly.

**Comment by walbourn** [comment]
Once GitHub puts [Mermaid](https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/) support into the GitHub wiki engine, I'll go back and some class diagrams to make this easier to see visually.

https://github.com/github/feedback/discussions/11612
