### ISSUE TITLE
Failed to compile RenderTexture.cpp

### ISSUE THREAD

**Issue by xiasun** [microsoft/DirectXTK#324]
Hi all, I was trying to use [RenderTexture.h/cpp](https://github.com/Microsoft/DirectXTK/wiki/Writing-custom-shaders#implementing-a-post-processing-effect) in my project, directxtk is properly configured (as I use some other functions like writing texture to png file )

When build with Visual Studio, it raised lots of errors like below, but I can properly go to definition in VS IDE:
```
...
'CreateRenderTargetView': is not a member of 'Microsoft::WRL::ComPtr'
'CreateShaderResourceView': is not a member of 'Microsoft::WRL::ComPtr'
...
```
If I tried to modify `m_device->` into `m_device.Get()->` inside RenderTexture.cpp slightly, this too error gone
```
/// original version
/// error: 'CreateRenderTargetView': is not a member of 'Microsoft::WRL::ComPtr'
ThrowIfFailed(m_device->CreateRenderTargetView(
    m_renderTarget.Get(),
    &renderTargetViewDesc,
    m_renderTargetView.ReleaseAndGetAddressOf()
));

/// modified version
/// no error
ThrowIfFailed(m_device.Get()->CreateRenderTargetView(
    m_renderTarget.Get(),
    &renderTargetViewDesc,
    m_renderTargetView.ReleaseAndGetAddressOf()
));
```
Can anyone tell me what's going on here?

Many thanks!

---

OS: Win 10 Pro
VS: 2019 Community
DirectX 12 enabled
DirectXTK installed via NuGet (version February 28, 2022)

**Comment by walbourn** [comment]
Do you have ``#include <d3d11_1.h>`` or something similar *before* you include ``RenderTexture.h``?

Also, what's in your ``pch.h`` file?  I'm assuming you at least include Direct3D 11 headers there.

**Comment by xiasun** [comment]
> Do you have `#include <d3d11_1.h>` or something similar _before_ you include `RenderTexture.h`?
> 
> Also, what's in your `pch.h` file? I'm assuming you at least include Direct3D 11 headers there.

ohhhh thanks!!! I truly forgot to have `#include <d3d11_1.h>` in my pch.h, I didn't figure it out since IDE has no error XD
