### ISSUE TITLE
Loading a sprite tutorial compiler error

### ISSUE THREAD

**Issue by CraftedPvP** [microsoft/DirectXTK#328]
Hi,
I'm following the DirectX11 tutorial for sprite and textures specifically the [Loading a texture](https://github.com/microsoft/DirectXTK/wiki/Sprites-and-textures#loading-a-texture)

I encountered a compiler error wherein
![image](https://user-images.githubusercontent.com/20311462/184064200-1528172e-6cb8-4b6c-9942-a7cb3d30fe8d.png)

I have added the DirectXTK via Nuget into the project and have added the long list of header files into the `pch.h` . This is the code I added into the `game.cpp`

```cpp
DX::ThrowIfFailed(CreateWICTextureFromFile(device, L"cat.png", nullptr, m_texture.ReleaseAndGetAddressOf()));
```
I'm guessing there's something wrong with the parameters but I just copied it from the tutorial.
I'm not entirely sure what to do since there's no mention about this compiler error anywhere.
How do I resolve this?

**Comment by walbourn** [comment]
Are you trying to use DirectX 11 or DirectX 12?  The output of the compiler indicates you are trying to use the ``ID3D12Device`` type but using the *DirectX Tool Kit for DX11* parameter list.

If you are following the DirectX 11 tutorial, you should be using DirectX 11. If you are using DirectX 12, use [those tutorials](https://github.com/microsoft/DirectXTK12/wiki/Getting-Started).

**Comment by walbourn** [comment]
The DirectX 11 signature is:

```
    HRESULT __cdecl CreateWICTextureFromFile(
        _In_ ID3D11Device* d3dDevice,
        _In_z_ const wchar_t* szFileName,
        _Outptr_opt_ ID3D11Resource** texture,
        _Outptr_opt_ ID3D11ShaderResourceView** textureView,
        _In_ size_t maxsize = 0) noexcept;
```

The DirectX 12 version is

```
    HRESULT __cdecl CreateWICTextureFromFile(
        _In_ ID3D12Device* d3dDevice,
        ResourceUploadBatch& resourceUpload,
        _In_z_ const wchar_t* szFileName,
        _Outptr_ ID3D12Resource** texture,
        bool generateMips = false,
        size_t maxsize = 0);
```

**Comment by CraftedPvP** [comment]
I apparently clicked the wrong project template so making it work with the DirectX11 tutorial didn't work as expected. thanks
