### ISSUE TITLE
What arguments I'm missing

### ISSUE THREAD

**Issue by dudedude1234** [microsoft/DirectXTK#329]
I'm setting up multiple animations for my model to operate through controls

`   switch (m_ModelAnimation)
    {
    default:
    DX::ThrowIfFailed(
        m_animation.Load(L"soldier.sdkmesh_anim")
    );
        break;
    }`

yet I keep getting this error saying there's too few arguments for the function call

**Comment by walbourn** [comment]
Are you using ``AnimationSDKMESH`` or ``AnimationCMO``?

**Comment by dudedude1234** [comment]
AnimationSDKMESH

**Comment by walbourn** [comment]
Please post a snippet of code that shows the ``m_animation`` declaration...

**Comment by dudedude1234** [comment]
`void Player::CreateDeviceDependentResources()
{

    auto device = m_deviceResources->GetD3DDevice();

    m_states = std::make_unique<CommonStates>(device);

    m_fxFactory = std::make_unique<EffectFactory>(device);

    m_model = Model::CreateFromSDKMESH(device, L"soldier.sdkmesh",
        *m_fxFactory,
        ModelLoader_Clockwise | ModelLoader_IncludeBones);

    
    switch (m_ModelAnimation)
    {
    default:
    DX::ThrowIfFailed(
        m_animation.Load(L"soldier.sdkmesh_anim")
    );
        break;
    }

    m_animation.Bind(*m_model);

    m_drawBones = ModelBone::MakeArray(m_model->bones.size());



 
}

    DirectX::ModelBone::TransformArray m_drawBones;

    DX::AnimationCMO m_animation;

`

**Comment by walbourn** [comment]
You declared:

```
DX::AnimationCMO m_animation;
```

You need to change it to:

```
DX::AnimationSDKMESH m_animation;
```
