### ISSUE TITLE
bounding sphere of a modal mesh 

### ISSUE THREAD

**Issue by AndreAhmed** [Microsoft/DirectXTK#33]
Hi,

I'm trying to get a bounding sphere of a modal mesh and transform it to world coordinates. but the bounding sphere without any transformation is not center at 0,0,0. 

here is how I do the transformation```

	 m_bounding = m_Tree->meshes.at(0)->boundingSphere;
	 XMMATRIX sphereTranslate = XMMatrixTranslation(m_bounding.Center.x, m_bounding.Center.y,
		 m_bounding.Center.z);
	sphereTranslate = sphereTranslate*treeTranslate;
 
	XMMATRIX boundingSphereScale = XMMatrixScaling(120.0f, 120.0f, 120.0f);
    worldSphere = boundingSphereScale*sphereTranslate;
	m_bounding.Transform(m_bounding, sphereTranslate* boundingSphereScale);

	m_BoundingSphere->Draw(worldSphere, m_Camera.ViewMatrix(), m_Camera.ProjectionMatrix());
```

**Comment by walbourn** [comment]
The first thing to do is check that your ``ModelMesh`` has a non-zero bounding volume. The modern SDKMESH exporter and CMO mesh pipeline in Visual Studio should be creating a valid sphere bound, but there are some older SDKMESH models that are missing valid bounds. Because the ``SDKMESH`` does not contain a bounding sphere, one is created at load time from the bounding box.

> Note that the center will not necessarily be (0,0,0) in model coordinates because this is not the most efficient sphere bound. The algorithm in DirectXMath's ``BoundingSphere::CreateFromPoints`` for example is from Ritter, Jack, _An Efficient Bounding Sphere_, **Graphics Gems**, Academic Press, 1990, p. 301-303, code: p. 723-725.

The code you provide is doing some really strange stuff with the center of the bounding box. All you really need to do is transform the ``BoundingSphere`` by the same transform as you use for rendering the model. If you want to do collision in world-space, that would just be the 'world' matrix, not the camera's view & projection matrices.

    XMMATRIX world = ...;
    BoundingSphere worldSphere;
    m_bounding.Transform(worldSphere, world);
   
BTW, for debugging collision geometry, you should take a look at [DebugDraw](https://github.com/Microsoft/DirectXTK/wiki/DebugDraw)

    m_batch = std::make_unique<PrimitiveBatch<VertexPositionColor>>(context);
    m_effect = std::make_unique<BasicEffect>(device);
    m_effect->SetVertexColorEnabled(true);
    {
        void const* shaderByteCode;
        size_t byteCodeLength;

        m_effect->GetVertexShaderBytecode(&shaderByteCode, &byteCodeLength);

        DX::ThrowIfFailed(
            device->CreateInputLayout(
                VertexPositionColor::InputElements, VertexPositionColor::InputElementCount,
               shaderByteCode, byteCodeLength,
                m_layout.ReleaseAndGetAddressOf()));
    }

    ...

    XMMATRIX modelWorld = ...;
    m_Tree->Draw( context, states, modelWorld, m_Camera.ViewMatrix(), m_Camera.ProjectionMatrix());

    m_batch->Begin();
    m_effect->SetView(m_Camera.ViewMatrix());
    m_effect->SetProjection(m_Camera.ProjectionMatrix());

    // Draws an outline of the bounding volume over the model
    BoundingSphere worldSphere;
    m_bounding.Transform(worldSphere, modelWorld);

    DX::Draw(m_batch.get(), worldSphere);

**Comment by AndreAhmed** [comment]
the name space DX is not defined, where should I get it ?

**Comment by walbourn** [comment]
It's in the link I gave you. [DebugDraw.h](https://github.com/Microsoft/DirectXTK/wiki/DebugDraw.h) and [DebugDraw.cpp](https://github.com/Microsoft/DirectXTK/wiki/DebugDraw.cpp).

**Comment by AndreAhmed** [comment]
I have the following code, but the sphere is translated and its not surrounding the tree. its translated behind it. 

here is how I'm rendering it


```
XMMATRIX treeTranslate = XMMatrixTranslation(100, -100, 112);

	// Convert rotation into radians.
	float angle = atan2(100 - m_Camera.Position().x, 112 - m_Camera.Position().z) * (180.0 / XM_PI);
	float treeRot = (float)angle * 0.0174532925f;
	XMMATRIX treeRotation = XMMatrixRotationY(treeRot);
	XMMATRIX treeWorld = treeRotation*treeTranslate; // THIS IS THE IMPORTANT WORLD, THE ROTATION IS IMPORTANT TO INCLUDE

	m_Tree->Draw(m_Graphics.getContext(), states, treeWorld, m_Graphics.getViewMatrix(),
		m_Camera.ProjectionMatrix());

	m_bounding = m_Tree->meshes.at(0)->boundingSphere;

	m_batch->Begin();
  
	m_bounding.Transform(m_bounding, treeWorld);

	m_effect->SetView(m_Camera.ViewMatrix());
	m_effect->SetProjection(m_Camera.ProjectionMatrix());
	Draw(m_batch.get(), m_bounding, Colors::Red);
	m_batch->End();
```

**Comment by walbourn** [comment]
What's the original values in ``m_Tree->meshes.at(0)->boundingSphere``?

**Comment by AndreAhmed** [comment]
m_bounding	{Center={x=0.00674819946 y=72.5237503 z=-0.932399750 } Radius=110.144882 }	DirectX::BoundingSphere

**Comment by walbourn** [comment]
Ok. It looks valid at least.

That said, ``m_bounding.Transform(m_bounding, treeWorld);`` means you are modifying the bounding sphere every frame you render which is not what you want to do. Make a temporary:

    BoundingSphere treeSphere;
    m_bounding.Transform(treeSphere, treeWorld);

    m_effect->SetView(m_Camera.ViewMatrix());
    m_effect->SetProjection(m_Camera.ProjectionMatrix());
    Draw(m_batch.get(), treeSphere, Colors::Red);
    m_batch->End();

**Comment by AndreAhmed** [comment]
still the sphere is in wrong place :+1:

**Comment by walbourn** [comment]
Sure, but we are getting closer.

Check the values of ``m_bounding``, ``treeSphere``, and ``treeWorld`` to make sure they make sense to you.

Also, what's the value of `` m_Tree->meshes.at(0)->boundingBox``?

What format is your model loading from?

**Comment by AndreAhmed** [comment]
I use the directx sdkmesh, converted from an obj file. 
m_bounding = {Center={x=0.00674819946 y=72.5237503 z=-0.932399750 } Radius=110.144882 }
treeSphere = {Center={x=99.1690521 y=-27.4762497 z=111.576981 } Radius=110.144882 }

tree world

![untitled](https://cloud.githubusercontent.com/assets/440842/15455910/7afbd702-2061-11e6-8406-5313ff9599f9.png)

**Comment by AndreAhmed** [comment]
Bounding box :

box = {Center={x=0.00674819946 y=72.5237503 z=-0.932399750 } Extents={x=58.6604500 y=73.0773544 z=57.8838997 } }

**Comment by AndreAhmed** [comment]
here is how I do the picking, which is incorrect due to the bounding sphere calculation is wrong, do you find a problem with it ? 

```

void GameApp::Pick(int sx, int sy, XMVECTOR & pickRayInWorldSpacePos, XMVECTOR &pickRayInWorldSpaceDir)
{
	XMVECTOR pickRayInViewSpaceDir = XMVectorSet(0.0f, 0.0f, 0.0f, 0.0f);
	XMVECTOR pickRayInViewSpacePos = XMVectorSet(0.0f, 0.0f, 0.0f, 0.0f);

	float PRVecX, PRVecY, PRVecZ;
	XMFLOAT4X4 tmp;
	XMStoreFloat4x4(&tmp, m_Camera.ProjectionMatrix());
	//Transform 2D pick position on screen space to 3D ray in View space
	PRVecX = (((2.0f * sx) / 784) - 1) / tmp.m[0][0];
	PRVecY = -(((2.0f * sy) / 562) - 1) / tmp.m[1][1];
	PRVecZ = 1.0f;  //View space's Z direction ranges from 0 to 1, so we set 1 since the ray goes "into" the screen

	pickRayInViewSpaceDir = XMVectorSet(PRVecX, PRVecY, PRVecZ, 0.0f);

	//Uncomment this line if you want to use the center of the screen (client area)
	//to be the point that creates the picking ray (eg. first person shooter)
	//pickRayInViewSpaceDir = XMVectorSet(0.0f, 0.0f, 1.0f, 0.0f);

	// Transform 3D Ray from View space to 3D ray in World space
	XMMATRIX pickRayToWorldSpaceMatrix;
	XMVECTOR matInvDeter;   //We don't use this, but the xna matrix inverse function requires the first parameter to not be null

	pickRayToWorldSpaceMatrix = XMMatrixInverse(&matInvDeter, m_Camera.ViewMatrix());   //Inverse of View Space matrix is World space matrix

	pickRayInWorldSpacePos = XMVector3TransformCoord(pickRayInViewSpacePos, pickRayToWorldSpaceMatrix);
	pickRayInWorldSpaceDir = XMVector3TransformNormal(pickRayInViewSpaceDir, pickRayToWorldSpaceMatrix);
	pickRayInWorldSpaceDir = XMVector3Normalize(pickRayInWorldSpaceDir);

	float dist;
	if (m_bounding.Intersects(pickRayInWorldSpacePos, pickRayInWorldSpaceDir, dist) == true)
	{
		m_Picked++;
	}

}
```

**Comment by AndreAhmed** [comment]
its fixed, I was not applying the effect. 
![untitled](https://cloud.githubusercontent.com/assets/440842/15457562/d3fc77c4-208b-11e6-9fe5-af64ff66ee07.png)

but I have another problem, as shown in the image  the sphere is large and doesn't surround the tree, how would I scale it ?

**Comment by walbourn** [comment]
That makes more sense :)

The issue here is that the bounding sphere is not a particularly tight bound because of the way it is created. Try picking against the ``boundingBox`` instead (there's a DebugDraw for the box) and see if that's a better bound for your model.
