### ISSUE TITLE
App and DeviceResources

### ISSUE THREAD

**Issue by dudedude1234** [microsoft/DirectXTK#336]
Is it okay to delete this because DeviceResources for UWP doesn't have anything form this

`void App::OnDpiChanged(DisplayInformation^ sender, Object^ args)
{
	// Note: The value for LogicalDpi retrieved here may not match the effective DPI of the app
	// if it is being scaled for high resolution devices. Once the DPI is set on DeviceResources,
	// you should always retrieve it using the GetDpi method.
	// See DeviceResources.cpp for more details.
	m_deviceResources- (sender->LogicalDpi);
	game->CreateWindowSizeDependentResources();
}

void App::OnOrientationChanged(DisplayInformation^ sender, Object^ args)
{
	m_deviceResources->GetOrientationTransform3D(sender- );
	game->CreateWindowSizeDependentResources();
}`

**Comment by walbourn** [comment]
See the **directx-vs-template** for examples of how to handle this:

https://github.com/walbourn/directx-vs-templates/blob/main/d3d11game_uwp_dr/Main.cpp
