### ISSUE TITLE
Gamepad stops working after reconnecting

### ISSUE THREAD

**Issue by brukwa** [microsoft/DirectXTK#337]
## Problem
Gamepad class stops working after specific sequence of events. 
Moreover it can cause crash on calling it's destructor. Now hold on... after application is restarted gamepad still does not work until **dmw.exe** process is restarted! 😨

## Environment
OS: Windows 10 21H2 (OS Build 19044.2075)
Controller: Xbox Series S/X Controller or Xbox One Controller (tested on both) **connected with usb cable**
DirectXTK: https://github.com/microsoft/DirectXTK/releases/tag/jul2022

## Experiment: Preparation
I have created simplest Win32 application and changed the main loop to include some traces
``` cpp
    MSG msg;
    // Create GamePad instance
    auto pGamepad = std::make_unique<DirectX::GamePad>();

    // Main message loop:
    do
    {
        // Pump some messages
        while (TRUE == ::PeekMessage(&msg, NULL, 0, 0, PM_REMOVE))
        {
            if (msg.message == WM_QUIT)
            {
                return 0;
            }

            ::TranslateMessage(&msg);
            ::DispatchMessage(&msg);
        }
        
        // Read Gamepad current state and trace to outpu info that 'A' button has been pressed
        auto state = pGamepad->GetState(0);
        if (state.buttons.a)
        {
            ::OutputDebugStringA("Pressed\n");
        }
    }
    while (true);
```
I have also included a simple trace to **Gamepad::OnGameInputDevice** 

``` cpp
        std::string trace = "Callback " + std::to_string(currentStatus) + "\n";
        OutputDebugStringA(trace.c_str());
```

## Experiment: Execution
1. Start the application with one controller connected
_It is traced as connected:_ `Callback 7`: ✔
2. Disconnect controller
_It is traced as disconnected:_ `Callback 0`: ✔
> ℹ This is just a control check to see that the disconnection event is reported
3. Reconnect controller
_It is traced as connected:_ `Callback 7`: ✔
4. Press 'A' button
_It is traced as pressed event a few times:_ `Pressed` : ✔
5. Disconnect controller
_There is no disconnection event reported_: ❌
6. Reconnect controller
_There is no connection event reported_: ❌
8. Press 'A' button
_There is no button press event reported_: ❌

Now to make things even worse
1. Restart the whole application **with controller connected**
_There is a stream of traces reporting connection and disconnection of a controller that goes on and on_ ❌
![image](https://user-images.githubusercontent.com/5063161/191867078-e061c0f3-4ff8-4736-aff1-fc2857fa2e90.png)
2. Press 'A' button
_There is no button press event reported_: ❌
3. Close main window (graceful shutdown)
_Application crashes and the Access Violation error is reported_ ❌
![image](https://user-images.githubusercontent.com/5063161/191867457-5ea652c0-520e-461a-9907-385601056998.png)
Callstack:
![image](https://user-images.githubusercontent.com/5063161/191867618-07b276bd-9796-44b7-9d0b-a36137f5da0e.png)

⚠ I have to close the `dwm.exe` process to make the application report controller events.

## 😨

I think this might be a problem with dmw.exe or GameInput library from GDK, but I have no idea how to diagnose it.
What can I do to find the source of this problem?

**Comment by walbourn** [comment]
Which version of the Microsoft GDK are you using?

**Comment by brukwa** [comment]
June 2022 Update 2 (220602). Currently it od the latest o e

**Comment by brukwa** [comment]
I have noticed one more weird thing, trying to get input using **Game Input** API from GDK.

Code below gets current gamepad input readings 
``` cpp
        ComPtr<IGameInputReading> pReading;
        HRESULT hr = m_pInput->GetCurrentReading(GameInputKindGamepad, nullptr, &pReading);
```

1. Disonnect gamepad and the `hr` equals `GAMEINPUT_E_READING_NOT_FOUND`. Fine.
2. Connect gamepad and the `hr` equals `S_OK`. Fine
3. Press some buttons and disconnect Gamepad. The `hr` is still `S_OK`.
Moreover, after restarting whole application it is still `S_OK` for disconnected gamepad untill dwm.exe process is restarted.

It seems like Game Input has some problems with handling gamepad disconnections.
Is there anything I can do to help in diagnosing this behavior?

**Comment by walbourn** [comment]
Can you try out the October 2022 release from https://github.com/microsoft/GDK/tree/2210_OCTOBER

**Comment by brukwa** [comment]
Almost good news. I did manage to install 'June 2022 Update 4 Public Release' (https://github.com/microsoft/GDK/releases/tag/June_2022_Update_4) **and the problem seems to be gone**.

I am not able to install the October update :(

I get an error and I do not how to install this from git repository.
> Unable to verify integrity of downloaded content. It might be corrupted. Please check your network connection and try again.

![image](https://user-images.githubusercontent.com/5063161/199221844-d159ab27-9c43-4600-a911-7475828e8042.png)

I think we can close this issue, since it is a problem with GDK. 

BTW do you have any hint how to install October version from git repository?

**Comment by walbourn** [comment]
Sorry, I should've mentioned that the GDK repository uses [git-lfs](https://git-lfs.github.com/).

In any case, sounds like it's fixed in newer GDK builds which is great.
