### ISSUE TITLE
delete ID3D11ShaderResourceView

### ISSUE THREAD

**Issue by Spuckwaffel** [microsoft/DirectXTK#339]
Hey there, 
I'm using the CreateWICTextureFromMemory function to create a Texture from a buffer in memory. It works fine but i see a large increase of memory when creating many textures. The 80 textures have a resolution of 1920x1080 and on disk the application is 3MB large and every file buffer is around 15000 bytes. Upon creating the texture with the ``CreateWICTextureFromMemory`` I save the ``ID3D11ShaderResourceView**`` into a vector with all the other textures. The memory usage of the program goes up to 600MB but i dont see any way how to delete the Texture again after ive used it. 
Any ideas?

**Comment by walbourn** [comment]
You need to do the proper AddRef/Release behavior for the COM object lifetime. A good solution is to use ``std::vector<Microsoft::WRL::ComPtr<ID3D11ShaderResourceView*>>`` which will keep the reference counts up to date.

See [Microsoft Docs](https://learn.microsoft.com/windows/win32/prog-dx-with-com) and [the wiki](https://github.com/Microsoft/DirectXTK/wiki/ComPtr).
