### ISSUE TITLE
Wrong Measurements from MeasureString

### ISSUE THREAD

**Issue by yaocatez** [Microsoft/DirectXTK#34]
Hi Developers,

I have notice that the MeasureString returns a wrong size. The string "W" is used to measure the string size. The spritefont file is generated using MakeSpriteFont tool. The font setting is 
- FontName: Arial
- FontStyle: Bold 
- FontSize: 185

The returned result for the width and the height are 233 and 283.642578 respectively. "W" is placed at (0,0) I have edited Image 1 to include a black dotted line and marked a red circle to indicate the position where my mouse positioned which reflects the values shown in the Window Title. Clearly, there is a big difference between the Vector2 returned and the size which I had measured.

Image 1:
![image 1](https://cloud.githubusercontent.com/assets/6721794/15455491/3329a388-2088-11e6-80f8-f33ffa5e4af1.PNG)

In addition, when I used SpriteBatch to draw "W" on the screen (0,0) using origin (0,0), it does not draw at the correct place. Instead, there is some sort of spacing as shown in Image 2.

Image 2:
![image 2](https://cloud.githubusercontent.com/assets/6721794/15455493/33309b84-2088-11e6-8f71-e5147cbc589a.PNG)

To test it further, I have used SpriteBatch to draw "W" on the screen at the bottom left (i.e. making it right justified) of the screen using the origin calculated via MeasureString, but it does not draw at the correct place as shown in Image 3. Instead, it is lifted and cut off.

Image 3:
![image 3](https://cloud.githubusercontent.com/assets/6721794/15455492/332e8b46-2088-11e6-860d-a7c9e61de5df.PNG)

**Comment by walbourn** [comment]
Which version of DirectX Tool Kit are you using? There was a bug with ``MeasureString`` that was [fixed](https://github.com/Microsoft/DirectXTK/commit/1c03978b507852e5fab78d291be7f48401037ca9) in the [Febraury 2016](https://github.com/Microsoft/DirectXTK/releases/tag/feb2016) release.

**Comment by yaocatez** [comment]
I am using:
Id: directxtk_windowsstore_8_1
Version: 2016.2.23.1

For your additional information:
I am developing Win32 application using Visual Studio 2013, but instead I am using directxtk_windows_8_1 (Version: 2016.2.23.1) as using the directxtk_desktop_2013 (Version: 2016.4.26.1) gives me error LNK1104:cannot open file 'x3daudio.lib'

**Comment by walbourn** [comment]
The different NuGet packages for DirectX Tool Kit are built for specific platforms, and make different assumptions. If you are writing a "classic" Win32 desktop application, you should **not** use the ``directxtk_windowsstore_8_1`` NuGet package.

For Windows Store 8.1, the application requires Windows 8.1 or later, and so ``directxtk_windowsstore_8_1`` makes use of XAudio 2.8 in the Windows  8.1 SDK. Similarly for UWP, the application requires Windows 10, and so ``directxtk_uwp`` makes use of XAudio 2.9 in the Windows 10 SDK. If you are making a Win32 classic desktop application, then I assume you are wanting Windows 7 compatibility. Therefore, if you use the ```directxtk_desktop_201x`` NuGet package, any use of _DirectX Tool Kit for Audio_ requires the legacy DirectX SDK. If you want specifically to write a Win32 classic desktop application that requires Windows 8 or later and thus uses XAudio 2.8, you can do so but you should use project-to-project references--this is a rare scenario, so I don't have a NuGet package specifically for this one. This is covered in detail on the [wiki](https://github.com/Microsoft/DirectXTK/wiki/Audio).

**Comment by walbourn** [comment]
In any case I'm able to repro your issue and I'm investigating.

**Comment by walbourn** [comment]
I think [this](https://github.com/Microsoft/DirectXTK/commit/1c03978b507852e5fab78d291be7f48401037ca9) was a bad fix, but I need to go back and figure out why I needed this change to make other things work.

**Comment by yaocatez** [comment]
Chuck Walbourn, thanks for the explanations. Actually, I am shifting from DirectX9 to DirectX11 and happened to found DirectXTK. At the same time, I am not going to use the legacy SDK (June 2010) to support my game engine even though it is only used for building very simple 2D games. Using DirectXTK makes the conversion easier as I am not very technical or familiar with the Pipeline related knowledge/experience. 

I do have the intention of converting it to Windows Store App style instead of Win32. However, based on my research, I found that I may also have to pick up C++/CX. Currently, I decided to convert it from DirectX9 (Win32) to DirectX11 (Win32) using DirectXTK first before I further my research on Windows Store App and the Pipeline. This may explains why my 2D Game Engine (Win32) uses `directxtk_windowsstore_8_1` instead of `directxtk_desktop_2013` for DirectXTK's Audio as it works for [this code snippet](https://directxtk.codeplex.com/wikipage?title=Audio).

Another question aside from `Audio `and `Spritefont `is: Do you have the intention of making DirectXTK's documentation similar to the MSDN style or is it advisablefor us to cross reference [DirectXTK ](https://github.com/Microsoft/DirectXTK/wiki/PrimitiveBatch#effect-and-input-layout)with [XNA](https://msdn.microsoft.com/en-us/library/microsoft.xna.framework.graphics.vertexpositioncolor.aspx)?

As for the SpriteFont, I will wait for you to fix it.

**Comment by yaocatez** [comment]
Hi Chuck,

Has the said issue been resolve?

**Comment by walbourn** [comment]
I'm wrapping a robust fix this weekend. You can download the library and make the source edit yourself as well.

**Comment by yaocatez** [comment]
Ok noted, in that case, i will wait for you to release all the fix at one go. Thanks,

**Comment by walbourn** [comment]
Sync to the master branch to pick up the fixes. Reverted ``MeasureString`` to old behavior, and added ``MeasureDrawString``.

    RECT MeasureDrawBounds(_In_z_ wchar_t const* text, XMFLOAT2 const& position) const;
    RECT XM_CALLCONV MeasureDrawBounds(_In_z_ wchar_t const* text, FXMVECTOR position) const;

**Comment by yaocatez** [comment]
Can you roughly estimate when will this fix be pushed to the NuGet Package?

**Comment by walbourn** [comment]
I generally wait until enough work has accumulated to justify a full release, but I can accelerate a publish to NuGet if that's required. I'll look at doing one this week.

**Comment by yaocatez** [comment]
alright, noted with thanks.

**Comment by yaocatez** [comment]
reminder for NuGet release. Thanks.

**Comment by walbourn** [comment]
Now that June 2016 is done, I'll be doing all the NuGet publishing for it tomorrow.

**Comment by walbourn** [comment]
Published to NuGet:


This version is also available on NuGet as version 2016.6.30.1
* [Universal Windows Platform apps using Windows Tools 1.4 (10586)](https://www.nuget.org/packages/directxtk_uwp/2016.6.30.1)
* [Windows desktop app using VS 2013 Update 5](https://www.nuget.org/packages/directxtk_desktop_2013/2016.6.30.1)
* [Windows desktop app using VS 2015 Update 3](https://www.nuget.org/packages/directxtk_desktop_2015/2016.6.30.1)
* [Windows 8.1 Store](https://www.nuget.org/packages/directxtk_windowsstore_8_1/2016.6.30.1)
* [Windows phone 8.1](https://www.nuget.org/packages/directxtk_windowsphone_8_1/2016.6.30.1)

**Comment by yaocatez** [comment]
yes thanks!

**Comment by yaocatez** [comment]
Hi Chuck,

I am getting this error message: "This project references NuGet package(s) that are missing on this computer. Enable NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is packages\directxtk_windowsstore_8_1.2016.4.26.1\build\native\directxtk_windowsstore_8_1.targets."

The solution I had discovered is to remove the lines that contains the April NuGet release. This is what is being removed:
 <Import Project="packages\directxtk_windowsstore_8_1.2016.4.26.1\build\native\directxtk_windowsstore_8_1.props" Condition="Exists('packages\directxtk_windowsstore_8_1.2016.4.26.1\build\native\directxtk_windowsstore_8_1.props')" />

    <Import Project="packages\directxtk_windowsstore_8_1.2016.4.26.1\build\native\directxtk_windowsstore_8_1.targets" Condition="Exists('packages\directxtk_windowsstore_8_1.2016.4.26.1\build\native\directxtk_windowsstore_8_1.targets')" />
    <Error Condition="!Exists('packages\directxtk_windowsstore_8_1.2016.4.26.1\build\native\directxtk_windowsstore_8_1.props')" Text="$([System.String]::Format('$(ErrorText)', 'packages\directxtk_windowsstore_8_1.2016.4.26.1\build\native\directxtk_windowsstore_8_1.props'))" />
    <Error Condition="!Exists('packages\directxtk_windowsstore_8_1.2016.4.26.1\build\native\directxtk_windowsstore_8_1.targets')" Text="$([System.String]::Format('$(ErrorText)', 'packages\directxtk_windowsstore_8_1.2016.4.26.1\build\native\directxtk_windowsstore_8_1.targets'))" />

Is there a better way to do it rather than editing it manually in the *****.vcxproj?

**Comment by walbourn** [comment]
As I said earlier in this thread, you shouldn't be using ``directxtk_windowsstore_8_1`` for a Windows desktop project. In my experience, the NuGet Manager is able to do the Update as long you have restored the old package.
