### ISSUE TITLE
Jittery mouse movement with higher mouse sensitivities

### ISSUE THREAD

**Issue by jkinz3** [microsoft/DirectXTK#349]
So I've been using the toolkit for a while now for my personal education in graphics programming and one thing that's always annoyed me is how jittery the mouse movement is when you increase the sensitivity. I discovered this because I followed the tutorial for mouse input on the wiki but the mouse rotation was far too slow. Due to the low sensitivity, the issue is present but not nearly as noticeable.
For example, here is how the mouse behaves currently when you multiply the inputs to increase mouse sensitivity. See how jittery it is? It's hard to describe but I am moving my mouse diagonally and it feels like it is either moving horizontally or vertically but never both at the same time.

https://user-images.githubusercontent.com/6319937/210378140-9d349906-6e7c-4b54-8773-f7617fffd5ec.mp4

Good news though! It took a while but I tracked down the cause to Mouse.cpp at 1304        
```
                if (!(raw.data.mouse.usFlags & MOUSE_MOVE_ABSOLUTE))
                {
                    pImpl->mState.x = raw.data.mouse.lLastX;
                    pImpl->mState.y = raw.data.mouse.lLastY;

                    ResetEvent(pImpl->mRelativeRead.get());
                }
```

The problem is that the WM_INPUT message from windows can fire off multiple times in between frames of the application. That means that by the time your `Tick() ` function runs, there have been multiple WM_INPUT messages received by the mouse singleton.
It is extremely common for any individual WM_INPUT message to have either x or y be 0. That's why during diagonal mouse movement, it felt like only horizontal or vertical movement was being registered but never both.

### The Cause
The issue is caused by the fact that we are **assigning** the delta to mState.x and mState.y instead of **accumulating** it. That means we are basically throwing away all inputs that windows throws at us except for the one it happens to receive before the application is ticked.

### The solution
```
                    pImpl->mState.x = raw.data.mouse.lLastX;
                    pImpl->mState.y = raw.data.mouse.lLastY;
```

becomes 
```
                    pImpl->mState.x += raw.data.mouse.lLastX;
                    pImpl->mState.y += raw.data.mouse.lLastY;
```
I would've done this as a pull request but this creates some issues due to how the class is designed and I didn't feel comfortable making deep changes to the API. The issue this creates is that the mState.x and mState.y **must** be cleared at the end of the application frame. It probably isn't the best idea to force any user to call some `OnEndFrame()` function because that will place an undue burden on any existing applications.
However, the existing implementation requires that during relative mouse movement, `GetState()` should only be called once. I propose that when `GetState()` is called, we pass the state by value rather than by reference and then clear the internal state.

Here is what it looks like when the WM_INPUT message are accumulated and then cleared at the end of the application frame.

https://user-images.githubusercontent.com/6319937/210389857-287dfb0c-a084-4e00-97c5-d04371a6d9bb.mp4

**Comment by walbourn** [comment]
Thanks for tracking this down. I'll take a look.

**Comment by walbourn** [comment]
Please take a quick look at : https://github.com/microsoft/DirectXTK/pull/359

**Comment by walbourn** [comment]
The more I think about the implications, the more I realize the 'auto-reset' in **GetState** is not going to work. I was really wanting a solution that didn't change the public interface, but I'm not sure I have any other choice to know when the relative dx/dy accumulate should be reset in a general scenario.

**Comment by walbourn** [comment]
After much angst, I've decided to do as follows:

1. Changed the relative modes to accumulate change per your requested change.
2. By default **GetState** will reset the accumulator each time you call expecting 'one per frame' usage.
3. Alternatively, client code can call a new method **EndOfInputFrame** which will disable the auto-reset in **GetState** and instead do it in this call.

This will hopefully minimize breaking impacts to existing clients, while supporting the enhanced scenario. Still a good idea to call this new method if you make use of relative movement.

**Comment by walbourn** [comment]
In other words, all the instructions for using mouse in the wiki are still accurate with one additional recommended integration point:

```
void Game::Tick()
{
    m_timer.Tick([&]()
    {
        Update(m_timer);
    });

    m_mouse->EndOfInputFrame();

    Render();
}

```
