### ISSUE TITLE
getting the vertices and the indices 

### ISSUE THREAD

**Issue by AndreAhmed** [Microsoft/DirectXTK#35]
Hi chuck,

is it possible to access the vertices and the indices of a directxtk sdkmesh model ?

**Comment by AndreAhmed** [comment]
when its possible to load skinning modal files ?

**Comment by walbourn** [comment]
The implementation of Model puts the VB/IB data into ``DEFAULT`` pool buffers, so they are not accessible by the CPU. This is the most efficient method. If you want to do face-level picking, then you really need to keep another copy of the data in CPU memory. Note built-in support for this is covered by [this issue](https://github.com/Microsoft/DirectXTK/issues/5).

Both SDKMESH and CMO models with skinning are loaded using the SkinnedEffect. There's not currently support for loading and playing back animations, which is covered by [this issue](https://github.com/Microsoft/DirectXTK/issues/7).
