### ISSUE TITLE
Windows not sending 'KSCATEGORY_AUDIO' notification for audio devices

### ISSUE THREAD

**Issue by siradam7th** [microsoft/DirectXTK#351]
I noticed that  `KSCATEGORY_AUDIO` isn't being sent by Windows to WndProc in `WM_DEVICECHANGE`, but instead `DEVINTERFACE_AUDIO_RENDER` is received when a playback device is inserted.

**Test setup**
Platform: Windows 10
Windows SDK version: 10.0.22000
Tested using both a Headset & Earbuds (front and back panel).

**Solution:**
Assuming this is the actual behaviour on other systems, I suggest this wiki page to be updated to filter for `DEVINTERFACE_AUDIO_RENDER` and handle receiving it, maybe even alongside  `KSCATEGORY_AUDIO` (just in case)
the Wiki page in question: ["Adding audio to your project"](https://github.com/microsoft/DirectXTK/wiki/Adding-audio-to-your-project)

Changes:
```cpp
// for DEVINTERFACE_AUDIO_RENDER 
#include <Mmdeviceapi.h>

DEV_BROADCAST_DEVICEINTERFACE filter = {};
        filter.dbcc_size = sizeof( filter );
        filter.dbcc_devicetype = DBT_DEVTYP_DEVICEINTERFACE;
        filter.dbcc_classguid = DEVINTERFACE_AUDIO_RENDER ;

        hNewAudio = RegisterDeviceNotification( hwnd, &filter,
            DEVICE_NOTIFY_WINDOW_HANDLE );
```
and
``` cpp
case WM_DEVICECHANGE:
    if ( wParam == DBT_DEVICEARRIVAL )
    {
        auto pDev = reinterpret_cast<PDEV_BROADCAST_HDR>( lParam );
        if( pDev )
        {
            if ( pDev->dbch_devicetype == DBT_DEVTYP_DEVICEINTERFACE )
            {
                auto pInter = reinterpret_cast<
                    const PDEV_BROADCAST_DEVICEINTERFACE>( pDev );
                if ( pInter->dbcc_classguid == DEVINTERFACE_AUDIO_RENDER)
                {
                    if (game)
                        game->OnNewAudioDevice();
                }
            }
        }
    }
    return 0;
```

**Sidenote:**
In order to get `KSCATEGORY_AUDIO` definition you must also include `ks.h` before `ksmedia.h` for it to compile.
``` cpp
// for KSCATEGORY_AUDIO
#include <Dbt.h>
#include <ks.h>
#include <ksmedia.h>
```

**Comment by walbourn** [comment]
Thanks for the follow-up. All audio devices are *supposed* to use `KSCATEGORY_AUDIO` as well, so maybe it's a driver bug?

What driver is it?

**Comment by siradam7th** [comment]
Realtek High Definition Audio, version 6.0.8945.1

**Comment by walbourn** [comment]
Are you using the default audio device when creating the XAudio2 mastering graph, or are you enumerating a specific device?

**Comment by siradam7th** [comment]
I have confirmed that this is a driver bug.
Since uninstalling the `Realtek HD Audio Driver` and reverting back to the standard Windows 10 driver solves this problem (still a realtek driver, but the one that ships with Windows), it sends an `KSCATEGORY_AUDIO` as expected.
But once the `Realtek HD Audio Driver (tested versions: 6.0.9225.1, 6.0.8945.1)` is installed, it no longer receives it, and instead starts receiving `DEVINTERFACE_AUDIO_RENDER`.

**Proposition:**
Since this bug might affect other systems causing inconsistent behaviour based on the audio driver, I suggest to also register notifications for `DEVINTERFACE_AUDIO_RENDER` so that even systems with an audio driver with this behaviour can get notifications as expected.

**Comment by walbourn** [comment]
Thanks for the follow-up.

If you use the default device for XAudio2 instead of enumerate a specific device, on Windows 10+ you won't actually get a graph error for changing end-points as `OnCriticalError`. This relies on WASAPI virtualized client. In that case, you don't really need this notification.

**Comment by siradam7th** [comment]
Yes, it is best to handle this using Audio apis rather than rely on `WM_DEVICECHANGE`.
Anyways, I hope this issue will be helpful to anyone that runs into this bug as I couldn't find anything about it.
