### ISSUE TITLE
Add Quaternion.Angle, RotateTowards, LookRotation, and FromToRotation to SimpleMath

### ISSUE THREAD

**Issue by walbourn** [microsoft/DirectXTK#36]
Unity script offers ``Quaternion.Angle``, ``Quaternion.RotateTowards``, ``Quaternion.LookRotation`` and ``Quaternion.FromToRotation`` that might be helpful to add to SimpleMath.

**Comment by gyakoo** [comment]
Just a question, is it something 'achievable' by:
1. Create lookAt matrix (with the forward, up vectors they provide in LookRotation)
2. Convert that matrix to quaternion
?
Or making a faster version?

**Comment by walbourn** [comment]
You can do this a number of ways. I just noted that Unity had a way to do it in a simple helper

**Comment by walbourn** [comment]
DX12 PR: https://github.com/microsoft/DirectXTK12/pull/116
