### ISSUE TITLE
xaudio2 XAUDIO2_E_DEVICE_INVALIDATED HRESULT not handled

### ISSUE THREAD

**Issue by star69rem** [microsoft/DirectXTK#366]
If you're using the DirectXTK AudioEngine, and another program takes over your device in exclusive mode, AudioEngine will bomb out because of this.

**Comment by walbourn** [comment]
What function is returning this hresult?

**Comment by star69rem** [comment]
Resume()

**Comment by walbourn** [comment]
There's already support for 'silent' mode that should avoid the need to load all the wave data again.

Do you have an example of software that grabs the exclusive ownership?

**Comment by walbourn** [comment]
Note the bug here is that **Resume** assumes the device is still there. That's not necessarily true as you've noted.

**Comment by star69rem** [comment]
Foobar, MAME with port audio in exclusive/low latency mode, any WASAPI software using exclusive mode, etc.

I had the understanding that if you created the audio engine in silent mode that you wouldn't get any sounds. Are you saying if you start it in silent mode, then you can reset it, and then on future failures it will be able to reset itself without reloading the data?

**Comment by star69rem** [comment]
After more testing, this also impacts initializing as well as resume. If you already started a program that is taking exclusive control of an audio device, the instantiation bombs out. I worked around it by adding this:

else if (hr == AUDCLNT_E_DEVICE_IN_USE)
        {
            DebugTrace("ERROR: AudioEngine failed (%08X) to initialize using device [%ls] because it was already in use.");
        }

**Comment by walbourn** [comment]
Makes sense. Thanks for digging. I'll add both the explicit checking of ``AUDCLNT_E_DEVICE_IN_USE`` as well as improving the **Resume** method later this week.

**Comment by walbourn** [comment]
If you can, please try out the code in the PR for [DX11](https://github.com/microsoft/DirectXTK/pull/367) or [DX12](https://github.com/microsoft/DirectXTK12/pull/160) and let me know if it works for you. I'll do some testing as well.

**Comment by walbourn** [comment]
The ``PKEY_AudioEngine_DeviceFormat`` doesn't seem entirely reliable. On my system it reports "32" which I know it's right.

If I use ``PKEY_AudioEngine_OEMFormat`` I get "16".

What values are you seeing for your audio part?

**Comment by walbourn** [comment]
It looks like `PKEY_AudioEngine_DeviceFormat` just reports the information set in the Sound Settings dialog for the end-point. It was set to '32' for my speakers, but that's not at all what the DAC actually supports.

Is that information useful?

**Comment by walbourn** [comment]
Please open a new issue for the reporting of the bit-depth, and I'll look into it.

**Comment by walbourn** [comment]
For the bit-depth issue, see:

https://github.com/microsoft/DirectXTK/pull/370

https://github.com/microsoft/DirectXTK12/pull/162

**Comment by star69rem** [comment]
Thanks. Is it useful to get WAVEFORMATEXTENSIBLE instead of WAVEFORMATEX? 

The WAVEFORMATEXTENSIBLE structure defines the format of waveform-audio data for formats having more than two channels or higher sample resolutions than allowed by WAVEFORMATEX. It can also be used to define any format that can be defined by WAVEFORMATEX.

Also, would it make sense to also get the sample rate from the waveformat returned from this property, too?

**Comment by star69rem** [comment]
This was what I was doing in my hacked up version:

if (SUCCEEDED(props->GetValue(PKEY_AudioEngine_DeviceFormat, &var)))
                    {
                        if (var.vt == VT_BLOB && var.blob.cbSize >= sizeof(WAVEFORMATEX))
                        {
                            const WAVEFORMATEXTENSIBLE* deviceFormatProperties = reinterpret_cast<const WAVEFORMATEXTENSIBLE*>(var.blob.pBlobData);
                            device.sampleRate = deviceFormatProperties->Format.nSamplesPerSec;
                            device.bitDepth = deviceFormatProperties->Format.wBitsPerSample;

                            PropVariantClear(&var);

                            return true;
                        }

                        PropVariantClear(&var);
                    }

**Comment by walbourn** [comment]
There's no difference at all between:

```
auto deviceFormatProperties = reinterpret_cast<const WAVEFORMATEXTENSIBLE*>(var.blob.pBlobData);
device.sampleRate = deviceFormatProperties->Format.nSamplesPerSec;
device.bitDepth = deviceFormatProperties->Format.wBitsPerSample;
```

and 

```
auto deviceFormatProperties = reinterpret_cast<const WAVEFORMATEX*>(var.blob.pBlobData);
device.sampleRate = deviceFormatProperties->nSamplesPerSec;
device.bitDepth = deviceFormatProperties->wBitsPerSample;
```
