### ISSUE TITLE
`MapGuard` undefined behavior after move

### ISSUE THREAD

**Issue by tkausl** [microsoft/DirectXTK#376]
`DirectX::MapGuard` defaults both move-constructor and move-assignment operator, which - correct me if I'm wrong - just copy over the member variables. The second destructor double-unmaps ("double frees") the mapping and - even worse - once one instance is gone, the mapping is gone aswell, so writing to that memory through the second instance causes undefined behavior.

Also, move-assignment doesn't unmap the previous mapping.

**Comment by walbourn** [comment]
I'll look at the behavior, but I honestly didn't expect it to be moved with an active Map.

**Comment by tkausl** [comment]
> but I honestly didn't expect it to be moved with an active Map.

 I didn't either, I just noticed those two to _explicitly_ declared as default, might as well just delete them if this is not intended.

**Comment by walbourn** [comment]
Fair point. Probably best to make those ``=delete``.
