### ISSUE TITLE
Mesh Outline Effect

### ISSUE THREAD

**Issue by pavledev** [microsoft/DirectXTK#384]
Can outline effect be created for mesh like in Blender?

**Comment by NicusorN5** [comment]
Yes This is a method on how to do so:
1.) Write a shader that returns the outline color in the pixel shader.
2.) Modify the stencil state so the stencil buffer is not used. (The outline will be visible trough other objects in this case)
3.) Draw the coloured model with a bigger scale.
4.) Reset the stencil state.
5.) Draw the initial model.

**Comment by pavledev** [comment]
> Yes This is a method on how to do so: 1.) Write a shader that returns the outline color in the pixel shader. 2.) Modify the stencil state so the stencil buffer is not used. (The outline will be visible trough other objects in this case) 3.) Draw the coloured model with a bigger scale. 4.) Reset the stencil state. 5.) Draw the initial model.

Can you help me to implement code for that?
