### ISSUE TITLE
darker images loading

### ISSUE THREAD

**Issue by aDioS786** [microsoft/DirectXTK#407]
Hi,
ID3D11ShaderResourceView** out_srv
I am trying to use hr = DirectX::CreateWICTextureFromFile(g_pd3dDevice,filename, nullptr, out_srv);

Images loads perfect, but only issue is they are darker as compared to image when viewed, so not loading with normal brightness.

**Comment by walbourn** [comment]
This is almost certainly due to sRGB. See https://github.com/microsoft/DirectXTK/wiki/WICTextureLoader#srgb
