### ISSUE TITLE
Reproducible crash in the 3D Audio System

### ISSUE THREAD

**Issue by HSNB** [microsoft/DirectXTK#460]
If you set Audio Listener's velocity to NAN (X, Y or Z any or all). An internal crash occurs inside XAudio2_9.dll

**Comment by walbourn** [comment]
XAudio2 expects that you don't pass invalid data to it. I know that the DEBUG functionality will emit ETW warnings for these scenarios.

Per the header in x3daudio.h:

```
    4.  Only real values are permissible with functions using 32-bit
        float parameters -- NAN and infinite values are not accepted.
        All computation occurs in 32-bit precision mode.    
```

**Comment by walbourn** [comment]
Where is NaN coming from in the first place in your case?

**Comment by walbourn** [comment]
XAudio2 was originally written for Xbox 360 (PowerPC) where "floating-point specials" were extremely slow, and as such the design assumes you never provide specials and will make sure that is always the case. For games, specials are avoided for many reasons.

I think the only thing I can really offer here is some extra asserts in the helper methods that warn about specials. I'm not sure that forcing them to be 0 is necessarily a desired behavior...
