### ISSUE TITLE
SpriteFont DrawString issue making text into black boxes

### ISSUE THREAD

**Issue by Zoardedz** [microsoft/DirectXTK#463]
I'm trying to make a GUI SpriteBatch that'll render a rectangle and an FPS counter as a test, I'm using your vs-templates (Win32 no device resources) with a few changes just making it more polymorphic, that aside there's a bug in my code that turns the text into black boxes if layered above the drawn rectangle, I assume this is because it's trying to reference the texture I used for the rectangle (images below)
![image](https://github.com/user-attachments/assets/e03c2158-d7b9-4891-91b3-e6cd31406204)
![image](https://github.com/user-attachments/assets/707f2750-70b9-42b1-b83e-b088e4e75ce2)
I made a different SpriteBatch instance for the FPS counter but it also gave me the same result (surprisingly??)
I assume it could be as I said, trying to reference the image I used for the rectangle instead of the SpriteFont textures or an unrelated issue relating to blendstates or something else.

**Comment by Zoardedz** [comment]
-I also used RenderDoc to check if the FPS text displays correctly when layered under the rectangle and it displayed the text like normal

**Comment by Zoardedz** [comment]
If it helps, this is practically the draw function every IElement2D uses.
![image](https://github.com/user-attachments/assets/52009d05-d5d8-4cd1-9222-3f166adb3fca)

**Comment by walbourn** [comment]
Is the render target here alpha-blended?  Note that SpriteBatch defaults to using Premultiplied alpha, and if you are using straight-alpha with the rectangle it will be 'wrong' here.
