### ISSUE TITLE
Retire Windows 8.1 Store, Windows phone 8.1, and VS 2013 projects

### ISSUE THREAD

**Issue by walbourn** [Microsoft/DirectXTK#47]
At some point we should remove support for these older versions in favor of UWP apps

`DirectXTK_Windows81.vcxproj`
`DirectXTK_WindowsPhone81.vcxproj`
`DirectXTK_XAMLSilverlight_WindowsPhone81.vcxproj`

This would also be a good time to drop VS 2013 entirely:

`DirectXTK_Desktop_2013.vcxproj`
`DirectXTK_Desktop_2013_DXSDK`

Please put any requests for continued support for one or more of these here.

**Comment by yaocatez** [comment]
Please continue support for DirectXTK_Windows81.vcxproj. If the NuGet Package of those are removed, please give a link for project to project references. Thanks.

**Comment by walbourn** [comment]
Why are you targeting Windows 8.1 Store rather than Windows 10 UWP? For games, for example, Windows 10 is at 43% (not including any Xbox One devices), while Windows 8.1 is at 11%.

In any case, when we retire support for older platforms the existing NuGet packages and [older releases](https://github.com/Microsoft/DirectXTK/releases) will still be available. it just means future updates won't include those older platforms. For example, the [Windows phone 8.0 NuGet](https://www.nuget.org/packages/directxtk_windowsphone_8/2016.2.23.1) is still online.

**Comment by yaocatez** [comment]
Yes, eventually we will upgrade to it. FYI, we are now converting DirectX 9 codes to DirectX 11 (Win32), mostly done. It would be hard for us to migrate from DirectX 9 to DirectX 11 (Windows 10) straight away. This transition is required in order to finally upgrade to Windows 10 UWP. We just need more time. Glad to hear that the existing NuGet packages will still be there.

You had provided me an useful statistic which I could propose for our next transition phase for next year. Thanks Chuck for the prompt reply!

**Comment by walbourn** [comment]
Note the data is from the Steam hardware survey.

**Comment by walbourn** [comment]
Based on NuGet telemetry, Windows Store 8.1 and Windows phone 8.1 packages are still getting picked up, so I'll likely keep VS 2013 around until whatever VS after 2017 comes out.

**Comment by walbourn** [comment]
Note that according to the [Microsoft lifecycle](https://support.microsoft.com/en-in/lifecycle/search?alpha=windows%20phone%208.1), mainstream support for Windows phone 8.1 ended July 11, 2017.

**Comment by walbourn** [comment]
I can also remove the adapter ``DIRECTX_NOEXCEPT`` from the code that I only need because VS 2013 doesn't support C++11 ``noexcept``.

**Comment by walbourn** [comment]
I can also replace the ``throw()`` usage with ``noexcept`` added in [this commit](https://github.com/Microsoft/DirectXTK/commit/43df3f97f1e24869688ac0c3aa73fb4fefcdab0e) when VS 2013 support is removed.

> In C++17, ``throw(...)`` and ``throw(x,y,z)`` usage have been removed (they were deprecated in C++14 in favor of ``noexcept``). The standard still requires ``throw()`` to be considered an alias of ``noexcept``. Since ``noexcept`` is not supported until VS 2015, using ``throw()`` solves the issue.

**Comment by walbourn** [comment]
See [this blog post](https://blogs.msdn.microsoft.com/chuckw/2018/04/30/github-nuget-and-vso/)

**Comment by walbourn** [comment]
Can use ``%zu`` instead of ``%Iu`` for printf format strings as well with the VS 2015 minimum.

**Comment by walbourn** [comment]
See this [pull request](https://github.com/Microsoft/DirectXTK/pull/132)
