### ISSUE TITLE
WICTextureLoader.cpp global arrays not initialized in release mode

### ISSUE THREAD

**Issue by halimacc** [Microsoft/DirectXTK#49]
When compile in VS2013, x64, **release** mode, the global arrays **g_WICFormats** and **g_WICConvert** will not be initialized (all zeros) when visited in function **_WICToDXGI** and function **CreateTextureFromWIC**.

**Comment by walbourn** [comment]
That really sounds like a compiler or debugger bug. Which VS 2013 Update are you using?

**Comment by halimacc** [comment]
@walbourn, it's Update 4, and you are right. I tested it with VS 2015 and this issue doesn't occur.

**Comment by walbourn** [comment]
You can try moving to [Update 5](https://www.visualstudio.com/en-us/news/vs2013-update5-vs.aspx) if you need to stick with VS 2013.

I also realized looking at this section of the code that I forgot to mark those arrays as 'const' at some point. I commited that change to the master branch last night.
