### ISSUE TITLE
Input lag when using a high report rate mouse

### ISSUE THREAD

**Issue by DDKK64** [microsoft/DirectXTK#493]
I'm building a win32 desktop application and uses Mouse.h to handle input. With a 1000hz report rate, when the mouse moves fast, the input queue seems jammed and responsiveness declines severely.

My guess is that the message queue handler is not fast enough so the message is blocked? Is it possible to utilize multithreading or make the handler simpler to speed it up?

PS: The lag is gone if `mouse->SetWindow(hWnd);` is removed.

**Comment by walbourn** [comment]
The `SetWindow` is needed to support "RawInput" which is used for relative mode high-resolution mouse.

The speed of polling is controlled by how often you are calling ``GetState``.
