### ISSUE TITLE
ComputeLights specular falloff improvement

### ISSUE THREAD

**Issue by justinsaunders** [Microsoft/DirectXTK#51]
In Lighting.fxh::ComputeLights(), the specular intensity currently falls of only as a term of dotH and a step() of dotL (diffuse "angle"). While correct, this results in sudden drop when dotL > 90. 
![image](https://cloud.githubusercontent.com/assets/876026/16967722/6846e364-4dbf-11e6-87fd-bbd3fb464c44.png)

A solution is to modulate the specular term further by dotL so we don't see the sharp edge

```
    float3 zeroL = step(0, dotL);
    float3 diffuse  = zeroL * dotL;
    float3 specular = pow(max(dotH, 0) * zeroL, SpecularPower) * dotL;
                                                              ^^^^^^^^
```

Output:
![image](https://cloud.githubusercontent.com/assets/876026/16967902/767fa1fe-4dc0-11e6-8186-d66aa01e45ad.png)

**Comment by walbourn** [comment]
Fix submitted to DirectXTK and DirectXTK12
