### ISSUE TITLE
AsyncStatus ambiguous symbol when using DirectXTK with "DirectX 11 and XAML app" template

### ISSUE THREAD

**Issue by johanlindfors** [Microsoft/DirectXTK#52]
Installing the latest version of DirectXTK from Nuget (2016.8.4.1) into a project based on the "DirectX 11 and XAML app" Visual Studio template is causing build errors since AsyncState is an ambiguous symbol. 

Well honestly, it only breaks when I add an include of SimpleMath.h in the pch.h.

But this worked earlier, any ideas on how to solve easiest?

This is on Windows 10 Anniversary Update, with Visual Studio 2015 Update 2

**Comment by johanlindfors** [comment]
If I add #define DIRECTX_NO_WFRECT before any references of including SimpleMath.h the build works, but is that as planned or am I missing something else?

**Comment by walbourn** [comment]
It seems ``Windows.Foundation.h`` conflicts with XAML headers. Maybe I'll make the ``Windows::Foundation::Rect`` interop opt-in rather than opt-out.

**Comment by walbourn** [comment]
Just removed the ABI::Windows::Foundation::Rect, so we don't need the #Include at all.
