### ISSUE TITLE
CreateMasteringVoice with default channels creates a Mastering Voice with incorrect number of channels

### ISSUE THREAD

**Issue by HSNB** [microsoft/DirectXTK#522]
CreateMasteringVoice with 0 as the number of channels, which makes XAudio2 choose the number of channels by itself, incorrectly chooses 8 channels even in a simple 2 speaker Stereo configuration.

Note also that [PKEY_AudioEndpoint_PhysicalSpeakers](https://learn.microsoft.com/en-us/windows/win32/coreaudio/pkey-audioendpoint-physicalspeakers) returns KSAUDIO_SPEAKER_STEREO, which is correct. So I'm not sure how XAudio2 just decides to randomly choose 8 output channels.

In my Windows settings I've set the Speaker setup as Stereo, so I'm not sure if this is my fault. The only thing I can think of is Windows thinks "Speakers" is a generic speaker setup that can be anything so XAudio2 just chooses 8 output channels.

**Comment by walbourn** [comment]
Did you pass both `XAUDIO2_DEFAULT_CHANNELS` and `XAUDIO2_DEFAULT_SAMPLERATE` and a `nullptr` specific device, or did you choose a specific device and pass 0 for the channels?
