### ISSUE TITLE
DXTK Collisions

### ISSUE THREAD

**Issue by Tonyx97** [Microsoft/DirectXTK#53]
I just wanted to ask if it's possible to edit the actual code and get the point of collision for example of a triangle-ray test, I've been messing with the code but I couldn't get it, I'm a bit lost to find this...

**Comment by walbourn** [comment]
I'm not sure what it is you are doing here. For most games, the best solution for collision is to use tests with bounding volumes (spheres, bounding boxes, oriented bounding boxes) as supported by [DirectXMath](https://msdn.microsoft.com/en-us/library/windows/desktop/hh449490.aspx).

Face-by-face triangle-level tests are very expensive, so it should be avoided as much as possible or at least have first-level collision using bounding volumes.

The main feature that is missing from DirectX Tool Kit to support triangle-level collision testing is that Model only puts the geometry data into GPU IBs/VBs. To support this kind of collision, it would need to return a std::vector of indices as well as a std::vector of positions (i.e. a collision mesh per [this work item](https://github.com/Microsoft/DirectXTK/issues/5)).
