### ISSUE TITLE
GeometricPrimitive support for tangents

### ISSUE THREAD

**Issue by walbourn** [Microsoft/DirectXTK#54]
Currently `GeometricPrimitive` only generates vertices with `VertexPositionNormalTexture` vertices. It should at a minimum support a way of generating and drawing with tangents as those are required for `NormalMapEffect`.

**Comment by walbourn** [comment]
Another option I'm exploring is to just make ``NormalMapEffect`` and ``PBREffect`` work _without_ precomputed tangents per this article (and [this followup blog post](http://www.thetenthplanet.de/archives/1180)):

Chris­t­ian Schüler, “Normal Mapping without Precomputed Tangents”, ShaderX 5, Chap­ter 2.6, pp. 131 – 140

**Comment by matt77hias** [comment]
Tangent-space normal mapping without precomputing tangents (and bitangents) and thus polluting the vertex structures at the expense of some extra calculations in the pixel shader is really worth it! 
[HLSL code](https://github.com/matt77hias/MAGE/blob/master/MAGE/MAGE/shaders/normal_mapping.hlsli) or [HLSL code](https://github.com/turanszkij/WickedEngine/blob/master/WickedEngine/tangentComputeHF.hlsli)
