### ISSUE TITLE
Desktop 2013 not working 

### ISSUE THREAD

**Issue by ExtasyHosting** [Microsoft/DirectXTK#56]
Hi, im trying with my renderer to make it working with version desktop 2013 on visual studio 2015 (but with v120). The renderer working find with version desktop 2015. I don't understand why is shouldn't on desktop 2013. They added new function on 2015 ?

**Comment by walbourn** [comment]
If you using the VS 2013 toolset (``v120``) then you need to use the desktop_2013 version of the static library. Generally static libraries are not compatible from version to version, and in the case of VS 2013 to VS 2015 there was a [major change](https://blogs.msdn.microsoft.com/vcblog/2015/03/03/introducing-the-universal-crt/) in the C/C++ Runtime Library implementation as well.

Why if you have VS 2015 installed are you not using ``v140``?

**Comment by ExtasyHosting** [comment]
Nvm, i resolve my problem. Thanks :)
