### ISSUE TITLE
Keyboard - Platform Notes section of the wiki is misworded

### ISSUE THREAD

**Issue by akbyrd** [Microsoft/DirectXTK#57]
Unless I'm being dense, this section appears to be gibberish: https://github.com/Microsoft/DirectXTK/wiki/Keyboard#platform-notes

**Comment by justinsaunders** [comment]
Thank you, edited that section, hopefully makes more sense.

**Comment by walbourn** [comment]
Made one more round of edits which hopefully is clearer.
