### ISSUE TITLE
Chinese characters with makespritefont

### ISSUE THREAD

**Issue by Tonyx97** [Microsoft/DirectXTK#62]
I've been struggling these last 2 days with making a chinese spritefont using makespritefont program but I'm not success... I'm converting Microsoft MHei font using this command 
`C:\msf.exe "Microsoft MHei" C:\arial.spritefont /FontSize:32 /characterregion:0x0-0xFF /characterregion:0xA373-0xB000` (in 0xA373 it's supposed to start traditional chinese characters). I've tried several commands but it's not working when I try to render Unicode text using the spritebatch in DX11. Any ideas?

**Comment by walbourn** [comment]
I have no idea what ``msf.exe``. The tool build for DirectX Tool Kit is ``makespritefont.exe``. Did you rename it?

**Comment by Tonyx97** [comment]
```
void DX11Renderer::DrawDXText(float x, float y, float scale, bool center, float rot, Color color, bool shadow, const char* Format, ...)
{
	if (!Initialized) return;

	char Buf[1024] = { '\0' };
	va_list VAL;
	va_start(VAL, Format);
	vsprintf_s(Buf, Format, VAL);
	va_end(VAL);
	std::wstring text = ConvertToWStr(Buf);

	XMFLOAT2 pos = { x, y };
	XMFLOAT2 posShadow[4];
	XMVECTOR colora = { color.R() / 255, color.G() / 255, color.B() / 255, color.A() / 255 };
	XMVECTOR coloraShadow = { 0.f, 0.f, 0.f, 0.7f };

	posShadow[0] = { x + 1.f, y + 1.f };
	posShadow[1] = { x - 1.f, y + 1.f };
	posShadow[2] = { x - 1.f, y - 1.f };
	posShadow[3] = { x + 1.f, y - 1.f };

	XMFLOAT2 origin(0, 0);
	if (center)
	{
		XMVECTOR size = DX11Purista->MeasureString(text.c_str());
		float sizeX = XMVectorGetX(size);
		float sizeY = XMVectorGetY(size);
		origin = XMFLOAT2(sizeX / 2, sizeY / 2);
	}

	if (shadow && color.A() / 255.f > 0.f)
	{
		for (unsigned short i = 0; i < 4; i++)
			DX11Purista->DrawString(DX11SpriteBatch.get(), text.c_str(), posShadow[i], coloraShadow, rot, origin, scale * 0.64f, SpriteEffects_None, 0);
	}
	DX11Purista->DrawString(DX11SpriteBatch.get(), text.c_str(), pos, colora, rot, origin, scale * 0.64f, SpriteEffects_None, 0);
}
```
This code is for not unicode strings and when I try to render for any chinese or unicode character shows a '?' instead of the correct character. I've used your command but still I can't get it working, it's working with ascii chars but not with unicode ones. 

`DX11Purista->DrawString(DX11SpriteBatch.get(), Format.c_str(), pos, colora, rot, origin, scale * 0.64f, SpriteEffects_None, 0);`
Using this which is for unicode without any conversions will stop the render and this line will make that anything in the renderer shows, it's very weird...

**Comment by walbourn** [comment]
First of all, I'd highly recommend using Unicode and not ANSI/Multibyte in your code if possible. This kind of conversion is expensive and error prone.

That said, ``ConvertToWStr`` isn't a standard function. Are you using ``MultiByteToWideChar``? If so, what codepage are you using?

**Comment by Tonyx97** [comment]
I don't have the code at hand now but I think we can ignore that because the everything should work without any conversions and that's I'm trying to do directly using the SpriteBach with a chinese character but this is causing a render bug or something because it doesn't render.

**Comment by walbourn** [comment]
What is the Chinese string in Unicode?

**Comment by Tonyx97** [comment]
L"⺄" it's the character I'm trying to render using:
DX11Purista->DrawString(DX11SpriteBatch.get(), L"⺄", pos, colora, rot, origin, scale * 0.64f, SpriteEffects_None, 0);
https://i.gyazo.com/e23663349c3635c26ececa57b6321283.png

**Comment by walbourn** [comment]
That character is 11908 (0x2e84). You didn't capture that character region.
