### ISSUE TITLE
Sprites not visible in windowed mode

### ISSUE THREAD

**Issue by wczmich** [Microsoft/DirectXTK#64]
Hi Im using your library to put some overlay text on another Directx 11 application. My problem is that it works when application is in borderless mode but sprites are not visible when application is in windowed mode. Can you suggest what can be the problem ?

**Comment by walbourn** [comment]
Presumably you are using some kind of hooking/injection solution, which is always problematic.

Most likely you are not setting (or clearing) some state required for the render. With injection you'll have to be really careful to restore any state you disturb to avoid impacting the app.

**Comment by wczmich** [comment]
I have solved my problem. For some reason renderview was not correct when I was trying to use sprites in windowed mode. When I set correct renderview before using sprites everything is ok. Thanks for your suggestion.
