### ISSUE TITLE
windows.gaming.input.h: No such file or directory

### ISSUE THREAD

**Issue by herdinstinct** [Microsoft/DirectXTK#67]
I just attempted to build after downloading but am unable to due to a missing windows.gaming.input.h. There is little information on where to find this file when googling. Any advice?

**Comment by walbourn** [comment]
I'm guessing you already solved your issue, but for future reference I'll answer here.

DirectX Tool Kit supports a wide combination of Microsoft platforms. As noted on the [wiki](https://github.com/Microsoft/DirectXTK/wiki/DirectXTK#using-project-to-project-references), there are a number of different projects.

The ``Windows.Gaming.Input.h`` header is used by ``GamePad`` when building for Windows 10, typically for a Universal Windows Platform (UWP) app. The ``DirectXTK_Windows10.vcxproj`` is configured to use VS 2015 and the _Windows 10 Anniversary Update SDK (14393)_ via the latest Windows Tools package for VS 2015, and has ``_WIN32_WINNT`` set to ``0x0A00`` to indicate building for Windows 10.

If you are targeting another platform, then be sure to set ``_WIN32_WINNT`` to the appropriate value: ``0x0601`` for Windows 7, ``0x0603`` for Windows 8.1, etc. This is already configured in the other ``vcxproj`` files.
