### ISSUE TITLE
operator T* ?

### ISSUE THREAD

**Issue by khatharr** [Microsoft/DirectXTK#69]
Just curious as to why there's no operator T* that returns ptr_.

This would allow for idiomatic usage such as:
`d3d11device->CreateDepthStencilView(depthStencilBuffer, 0, &depthStencilView);`

Rather than requiring a call to .Get() on the buffer.

This was present in CComPtrBase and I found it quite useful. Is there a reason that it's not implemented for WRL::ComPtr?

**Comment by walbourn** [comment]
The reason ``ComPtr`` doesn't have a ``operator T*`` is the same reason ``std::unique_ptr`` doesn't. Automatic conversion to raw pointers is highly problematic. See [this blog post](https://herbsutter.com/2012/06/21/reader-qa-why-dont-modern-smart-pointers-implicitly-convert-to/).

See [ComPtr](https://github.com/Microsoft/DirectXTK/wiki/ComPtr)

**Comment by khatharr** [comment]
Thanks for the link. :)
