### ISSUE TITLE
Model needs support for skinned animations

### ISSUE THREAD

**Issue by walbourn** [microsoft/DirectXTK#7]
Both CMO and SDKMESH support skinned animations. These are currently ignored by the Model implementation.

**Comment by walbourn** [comment]
Associated with changeset 31658: DirectXTK: Skinned Model support
◾Updated DGSLEffect with support for skinning 
◾IEffectSkinning interface added 
◾Updated SkinnedEffect to use default texture if no texture set 
◾Updated Model loading to use skinned effects and vertex types

**Comment by trong8820** [comment]
https://github.com/Microsoft/DirectXTK/wiki/Using-skinned-models
When you finish it?
I need it for my game!!!!

**Comment by walbourn** [comment]
One option would be to clean up the original D3DX9 ``ID3DXAnimationController`` / ``ID3DXAnimationSet`` code into a generic open source form. The main challenge is that it would leave loading/saving the animation data as an exercise to the client since the original code was focused on the now deprecated ``x`` file format. Should be fairly easy to use with ``SDKMESH`` or ``CMO`` animation data.

> I would implement the equivalent to ``ID3DXKeyframedAnimationSet``, but likely not ``ID3DXCompressedAnimationSet``

**Comment by walbourn** [comment]
http://metlab.cse.msu.edu/betterskinned.html

**Comment by IgrauBezRuk** [comment]
Hey! Any progress on this?

**Comment by JRicaurte1985** [comment]
I too hope this is in the works. Your tutorials have been very useful and easy to follow.

BTW was hoping to find more info from the link, but the metlab link gives a 404 =(

**Comment by dudedude1234** [comment]
I have a problem with the SkinnedMesh::render() 

`void SkinnedMesh::render() 
{
	_effect->SetTechnique(_hTech);  
	UINT numPasses = 0; 
	_effect->Begin(&numPasses, 0);
	for (UINT i = 0; i < numPasses; ++i) 
	{
		_effect->BeginPass(i);
		// Draw the one and only subset.   _skinnedMesh->DrawSubset(0); 
		_effect->EndPass();
	}  _effect->End();
}`


What should I use for the _effect?

**Comment by dudedude1234** [comment]
This is how far I got:






pch.h
`ID3DXAnimationController^                           _animCtrl;`


ID3DXAnimationController.h
`#pragma once
#include <pch.h>





ref class  ID3DXAnimationController
{
public:

    HRESULT ID3DXAnimationController::AdvanceTime(
        DOUBLE TimeDelta,
        LPD3DXANIMATIONCALLBACKHANDLER pCallbackHandler);

    HRESULT ID3DXAnimationController::SetTrackAnimationSet(
        UINT Track,
        ID3DXCompressedAnimationSet  pAnimSet);

    HRESULT ID3DXAnimationController::GetAnimationSet(
        UINT Index,
        ID3DXCompressedAnimationSet* ppAnimSet);

    HRESULT ID3DXAnimationController::SetTrackEnable(
        UINT Track,
        BOOL Enable // True to enable and false to disable.
    );

    HRESULT ID3DXAnimationController::SetTrackSpeed(
        UINT Track,
        FLOAT Speed);

    HRESULT ID3DXAnimationController::SetTrackWeight(
        UINT Track,
        FLOAT Weight);

    HRESULT ID3DXAnimationController::SetTrackPriority(
        UINT Track,
        PRIORITY_HINT Priority
    );
};`

ID3DXAnimationController.cpp
`#include "ID3DXAnimationController.h"

HRESULT ID3DXAnimationController::AdvanceTime(DOUBLE TimeDelta, LPD3DXANIMATIONCALLBACKHANDLER pCallbackHandler)
{
	return E_NOTIMPL;
}

HRESULT ID3DXAnimationController::SetTrackAnimationSet(UINT Track, LPD3DXANIMATIONSET pAnimSet)
{
	return E_NOTIMPL;
}

HRESULT ID3DXAnimationController::GetAnimationSet(UINT Index, LPD3DXANIMATIONSET* ppAnimSet)
{
	return E_NOTIMPL;
}

HRESULT ID3DXAnimationController::SetTrackEnable(UINT Track, BOOL Enable)
{
	return E_NOTIMPL;
}

HRESULT ID3DXAnimationController::SetTrackSpeed(UINT Track, FLOAT Speed)
{
	return E_NOTIMPL;
}

HRESULT ID3DXAnimationController::SetTrackWeight(UINT Track, FLOAT Weight)
{
	return E_NOTIMPL;
}

HRESULT ID3DXAnimationController::SetTrackPriority(UINT Track, PRIORITY_HINT Priority)
{
	return E_NOTIMPL;
}`



Player.cpp

`void Player::Idle()
{
    ID3DXAnimationSet* idle = 0;
    _animCtrl->GetAnimationSet(Idle_INDEX, &idle);
    _animCtrl->SetTrackAnimationSet(0, idle);
    _animCtrl->ResetTime();
}`

**Comment by walbourn** [comment]
DirectX12 version https://github.com/microsoft/DirectXTK12/pull/104
