### ISSUE TITLE
Loading a model using Meshconvert (.cmo)

### ISSUE THREAD

**Issue by andydeveloper27** [Microsoft/DirectXTK#70]
Trying to understand the tutorial on loading a model. It says use a command prompt and meshconvert. I dont even know where to start with this. Im trying to change my .Obj into a .cmo. Any help out there?

Thanks!

**Comment by walbourn** [comment]
The tutorial uses the DirectXMesh meshconvert command-line utility, but you could use the Visual Studio built-in FBX to CMO pipeline as well. See [Working with 3-D Assets for Games and Apps](https://msdn.microsoft.com/en-us/library/hh315737.aspx)
