### ISSUE TITLE
AudioEngineNoAudioHW on Windows 7

### ISSUE THREAD

**Issue by rcurtis** [Microsoft/DirectXTK#73]
Greetings,

I am currently deploying an app that uses DirectXTK and DirectXTKAudio and getting an exception while initializing the AudioEngine.  I am using the DirectXTK_Desktop_2015 solution with the DirectXTKAudio_Desktop_2015_DXSDK for compatibility with Win7 (32 bit).  I am getting a list of available devices before creation that gives me:

`Speakers (Realtek High Definition Audio)`

The device manager says the following devices are available:

```
NVIDIA High Definition Audio
NVIDIA Virtual Audio Device (Wave Extensible)(WDM)
Realtek High Definition Audio
```

Any ideas on how I can further debug this?

Thanks,
-Rob

**Comment by walbourn** [comment]
What's the detail of the exception you are getting? What line of code is throwing the exception?

**Comment by rcurtis** [comment]
The exception is thrown from

`AudioEngine::AudioEngine( AUDIO_ENGINE_FLAGS flags, const WAVEFORMATEX* wfx, const wchar_t* deviceId, AUDIO_STREAM_CATEGORY category ) `

If I check the output it says `"Error: XAudio 2.7 not installed on system (install the DirectX End-User Runtimes (June 2010))"` - which is installed on the machine.

**Comment by rcurtis** [comment]
Update: the line

`mDLL = LoadLibraryEx( L"XAudioD2_7.DLL", nullptr, 0x00000800 /* LOAD_LIBRARY_SEARCH_SYSTEM32 */ );`

reliably fails to load the DLL, but If I copy the DLL from system32 to sit next to the application and switch to `LoadLibrary(L"XAudioD2_7.dll");` it works.

**Comment by walbourn** [comment]
There may be something wrong with your system install then. Try running the XAudio2 samples from [here](https://github.com/walbourn/directx-sdk-samples).

**Comment by sergiubucur** [comment]
I have the same issue. AudioEngine fails to initialize properly on certain environments (different PCs running Win7 x64), even though XAudio2 is properly installed.

I tried the XAudio2 samples and I get the same result. Changing the line

`mDLL = LoadLibraryEx( L"XAudioD2_7.DLL", nullptr, 0x00000800 /* LOAD_LIBRARY_SEARCH_SYSTEM32 */ );`

to

`mDLL = LoadLibraryEx( L"XAudioD2_7.DLL", nullptr, 0);`

works for me without having to copy the DLL to the application folder.

On the environments I tested (couple of PCs running Win7 and Win10) this works fine, but I'm not sure if switching the LOAD_LIBRARY_SEARCH_SYSTEM32 flag with 0 is going to behave properly on all environments.

**Comment by walbourn** [comment]
That seems very odd, but I suppose there could be some subtle legacy DirectX SDK bug at play here.

Maybe the best solution here woudl be to use the standard load for the DEBUG version of the DLL, but use  ``LOAD_LIBRARY_SEARCH_SYSTEM32`` for the RELEASE version which is more likley to be a problem--as to why I'm using this flag at all, see [this](https://technet.microsoft.com/library/security/2269637) article.

Be sure to use the latest DXSETUP (April 2011 refresh) to deploy XAudio 2.7 for end-users. See [this post](https://blogs.msdn.microsoft.com/chuckw/2011/04/19/dxsetup-update/).
