### ISSUE TITLE
Cryptic error message trying to add reference to Desktop 2015 Win10 project

### ISSUE THREAD

**Issue by jjhegedus** [Microsoft/DirectXTK#75]
The error message I get is "A reference to 'DriectXTK_Desktop_2015_Win10' cannot be added because it is incompatible with this project.

I'm developing with Visual Studio 2015, using C+++ and running on Windows 10.  The error message doesn't give many clues.  How can I even find out what the issue is?

**Comment by walbourn** [comment]
What kind of application are you trying to write? If you are creating a UWP app, for example, then you can't use that version and must use ``DirectXTK_WIndows10.vcxproj`` instead.

**Comment by jjhegedus** [comment]
Yep, that was the problem.  It seems obvious now but I just didn't connect the desktop dots.  Thanks.
