### ISSUE TITLE
SpriteBatch VertexPageSize mismatch

### ISSUE THREAD

**Issue by ChrisKing340** [Microsoft/DirectXTK#76]
Noticed in SpriteBatch.cpp Line 357:
mVertexPageSize(sizeof(VertexPositionNormalColorTexture) * MaxBatchSize * VerticesPerSprite), 

Which allocates too much memory, as everywhere else VertexPositionColorTexture is used, so thought this should be:
mVertexPageSize(sizeof(VertexPositionColorTexture) * MaxBatchSize * VerticesPerSprite),

Optimization and not an error.  Although normal support would be awesome!

**Comment by walbourn** [comment]
Ah, this is in [DirectX Tool Kit for DirectX 12](https://github.com/Microsoft/DirectXTK12), not DirectX Tool Kit for DirectX 11.

**Comment by walbourn** [comment]
Fixed in this [commit](https://github.com/Microsoft/DirectXTK12/commit/30cddf1b3d051be58135104f33e16362b4a3d6c4). Thanks!
