### ISSUE TITLE
Keyboard.h IsKeyDown check is out of range

### ISSUE THREAD

**Issue by kudovickij** [Microsoft/DirectXTK#77]
```
bool __cdecl IsKeyDown(Keys key) const
{
    if (key >= 0 && key <= 0xff)
{
```

Is inconsistent with

```
bool __cdecl IsKeyUp(Keys key) const
{
    if (key >= 0 && key <= 0xfe)
{
```

Last value in Keys is defined as 0xfe.

**Comment by walbourn** [comment]
Thanks. The first one was probably supposed to be ``key < 0xff``. I'll make them both consistent with the second to be clear.

**Comment by walbourn** [comment]
Fixed for next release.
