### ISSUE TITLE
Drawing ellipse

### ISSUE THREAD

**Issue by kreuzerkrieg** [Microsoft/DirectXTK#79]
Is there a way to draw ellipse using DirectXTK?

**Comment by walbourn** [comment]
Drawing ellipse and other vector-graphics shapes is a job best done with Direct2D which is explicitly designed for this kind of 'presentation graphics'. In games, typically such shapes are just drawn by an artist into a bitmap and then rendered as a texture sprite.

On DirectX 11.1 or later, Direct2D interop with Direct3D 11 is very easy so you shouldn't have a lot of trouble getting it to work. If you are on Windows 7, see [DirectX 11.1 and Windows 7 Update](https://blogs.msdn.microsoft.com/chuckw/2013/02/26/directx-11-1-and-windows-7-update/).

> If you are developing an Universal Windows Platform (UWP) app, then you should consider using [Win2D](https://github.com/Microsoft/Win2D) as a wrapper for Direct2D.

**Comment by kreuzerkrieg** [comment]
Thanks Chuck!
