### ISSUE TITLE
MediaStream class for playing compressed audio

### ISSUE THREAD

**Issue by walbourn** [microsoft/DirectXTK#8]
This work item is for implementing a version of  XAudio2MFStream as part of DirectXTK for Audio using Media Foundation's SourceReader which supports a number of built-in codecs including WMA.

Note this is specifically for the case of wanting to apply some effect using XAudio2. Direct playback of a streaming file in the background is more efficiently implemented by using Media Session directly. See  Media Session Playback Example.

The original XNA GS library included a  DynamicSoundEffectIstance class primarily as a way to implement streaming. With DirectXTK for Audio, it generally makes more sense to implement a streamer directly against the XAudio2 API to more efficient handle events, callbacks, etc.

**Comment by AlvisDEV** [comment]
This is what we really need. When will this great feature be published? Is there any plan to make a video renderer?

**Comment by walbourn** [comment]
What is it exactly you are wanting to achieve here?

The XAudio2MFStream and XAudio2AsyncStream samples on [GitHub](https://github.com/walbourn/directx-sdk-samples/) already implement basic streaming, but this work item is for having some kind of helper that does the XAudio2MFStream thing in a portable way across Xbox One, PC, and UWP. If you are just looking for a PC solution, see the sample.

Video is problematic because there's really no Microsoft solution that is portable across Xbox One, PC, and UWP: each has a slightly different solution especially if you want 'down-level' support for Windows 7. The vast majority of games just use something like Bink.

**Comment by AlvisDEV** [comment]
I do work on UWP and windows 7 desktop. So stream audio helper for both UWP and Desktop is needed.
For video, I don't need "down-level" support, basic video playback is fine. I am now focus on media foundation to check is there any solution for both windows 7 and UWP.

**Comment by walbourn** [comment]
What do you mean by 'basic video playback' exactly? Full-screen cut-scene like rendering or render-to-texture that you then put onto objects?

Windows 7 desktop *is* down-level support these days :)

**Comment by AlvisDEV** [comment]
Full-screen or windowed rendering

**Comment by walbourn** [comment]
With XAudio 2.9 already supporting xWMA compression, and the XAudio2Redist providing xWMA support for Windows 7 and Windows 8.1, the work I did on [SoundStreamInstance](https://github.com/microsoft/DirectXTK/wiki/SoundStreamInstance) this work is no longer that compelling.

Video was always a bit out of scope for DirectX Tool Kit, but there are some samples available for some of those scenarios:
