### ISSUE TITLE
Finish audio tutorials

### ISSUE THREAD

**Issue by walbourn** [microsoft/DirectXTK#82]
The section of on using positional audio is UNDER CONSTRUCTION.

Also add section on using SoundStreamInstance to Playing sounds tutorial

**Comment by PeteHuf** [comment]
In addition to positional audio, I haven't found anything about streaming audio. It looks like all the normal ways of playing the sound from the WaveBank only work for in-memory.

**Comment by walbourn** [comment]
I've not implemented a streamer as of yet. You can find some code for doing async streaming from XACT wave banks in PCM format [here](https://github.com/walbourn/directx-sdk-samples/blob/master/XAudio2/XAudio2AsyncStream/XAudio2AsyncStream.cpp). ADPCM and xWMA streaming are trickier to implement.

**Comment by PeteHuf** [comment]
Thanks for the info! I'd missed that other task. I don't have a pressing need, but I'd like to stream ADPCM before I release (which realistically, is probably a few years out). Any chance DirectX Tool Kit will support ADPCM streaming in that time frame?

**Comment by amerkoleci** [comment]
Dunno if this is the correct topic, did you even thought on replacing the XAudio backend with WASAPI? What are the performance tho on XAudio?

**Comment by walbourn** [comment]
WASAPI is appropriate if you have your own mixer and can provide whatever source-rate that WASAPI requires, and is often used by game audio middleware like FMOD, MSS, WWise, etc. because their software does all the real-time mixing, source-rate conversion, etc. XAudio2 in fact uses WASAPI for output of the final mix too.

XAudio2 does the source-rate conversion, real-time mixing, and optionally applies digital signal processing before submitting it to WASAPI for play. They are solving different problems.

The _DirectX Tool Kit for Audio_ is just a collection of management classes to simplify using XAudio2.

**Comment by amerkoleci** [comment]
I see, thanks for explanation.

**Comment by walbourn** [comment]
@PeteHuf I'm working on a update to *DirectX Tool Kit for Audio* with support for streaming from XACT3-style WaveBanks. See [this PR](https://github.com/microsoft/DirectXTK/pull/217).

**Comment by PeteHuf** [comment]
@walbourn thanks for keeping me posted! I've switched over to WWise for now, but if that ends up no longer suiting my needs I'll be sure to take another look at DXTK's audio.

**Comment by walbourn** [comment]
split playing sounds & wavebank tutorial pages, and added streaming to the wavebank page.

**Comment by walbourn** [comment]
Added tutorial on positional audio [here](https://github.com/microsoft/DirectXTK/wiki/Using-positional-audio)
