### ISSUE TITLE
Visual Studio 2017 support ETA

### ISSUE THREAD

**Issue by sbd1138** [Microsoft/DirectXTK#83]
Just checking in to see what the ETA is for adding in Visual Studio 2017 support, as it officially released a few days ago.  Am looking to plan out my own migration to 2017 (from 2010), which of course is predicated on my required 3rd party SDKs supporting it as well.

**Comment by walbourn** [comment]
Already supported in the latest release as the existing "RC" versions of the projects work fine. See [Visual Studio 2017](https://blogs.msdn.microsoft.com/chuckw/2017/03/07/visual-studio-2017/).

The main thing I'm still working on is getting VS 2017 versions of my [Direct3D game templates](https://github.com/walbourn/directx-vs-templates) Should be next week.

**Comment by sbd1138** [comment]
Thanks for the quick response Chuck.  Wasn't sure if there were any changes between RC and the official release that necessitated further inspection on your guys' side.  Sounds like it's goood-to-go...thanks!

**Comment by walbourn** [comment]
The only thing that I really tracked between VS 2017 RC.1 and the VS 2017 RTM of note was a few changes to ``/permissive-`` errors. Given that the Windows 10 SDK (14393) isn't actually compatible with ``/permissive-``, I had to use a Windows 10 Creators Update SDK preview. I plan to do another release when that new SDK is finalized.
