### ISSUE TITLE
Does Xinput and GamePad supported on WP8.1?

### ISSUE THREAD

**Issue by sensboston** [Microsoft/DirectXTK#84]
Hello guys, I'm very confusing: some documents said that Xbox controllers are supported on WP 8.1 but source code, even for old releases, has only null stub :(
```
//====================================================================
// Null device for Windows Phone
//====================================================================
```
I do have "DOSBox" app for WP8.1 (for some reasons I don't want to migrate to W10M and abandon my WP 8.1 customers) and want to add Xbox controllers support to my app.

Actually I already added a GamePad integration to my solution but found that nothing works (I built DirectXTL project from sources, nuget version makes some issues with the build) :(

**Comment by walbourn** [comment]
Neither XINPUT nor ``Windows.Gaming.Input`` are supported by Windows phone 8.x, which is why it uses a null device.

Where are you seeing support for Xbox controllers on WP8?

**Comment by sensboston** [comment]
Yeah, thanks for the response but I already figured out by myself. I'm going to add Xbox controllers support top my ["DOSBox" port app](https://www.microsoft.com/en-us/store/p/dosbox/9nblggh4q6j8); fortunately porting WP8.1 code to W10M not too hard, last weekend time covered about 90% of coding :) However new W10M version will get an additional advantages (not counting Xbox controllers support) like direct access to DOSBox home folder on sd-card, Continuum support and a couple more things. So, finally I can say that the idea of porting app to W10M was a good idea :) However I'll continue WP8.1 support 'cause I still have about 20% WP8.1 customers.
