### ISSUE TITLE
VS2017 Templates

### ISSUE THREAD

**Issue by garydstewart** [Microsoft/DirectXTK#85]
I am unable to use the templates from the Getting Started Guide  [VS 2013 / VS 2015 / VS 2017 VSIX ](https://github.com/walbourn/directx-vs-templates/raw/master/VSIX/Direct3DUWPGame.vsix)

When attempting to create a new project using the templates I get an error dialog:

Error: this template attempted to load component assembly 
'Microsoft.VisualStudio.WinRT.TemplateWizards, Version=14.0.0.0,
Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. For more 
information on this problem and how to enable this template, 
please see documentation on Customizing Project Templates.

I assume it's simply just looking for a certain version of the component assembly, I think Version 15 would be for 2017. I'm not sure how to get in there and actually edit the template by hand myself.

**Comment by walbourn** [comment]
Do you have VS 2015 installed on that machine or only VS 2017?

What Workloads did you install on the VS 2017 system?

**Comment by walbourn** [comment]
Moved this issue to [directx-vs-templates](https://github.com/walbourn/directx-vs-templates/issues/7)
