### ISSUE TITLE
Unable to specify model's texture path when using Model::CreateFromCMO

### ISSUE THREAD

**Issue by ajweeks** [Microsoft/DirectXTK#86]
Why is there no option to specify where the texture for a .cmo file is? I don't want to store the texture in my root directory, but it looks like CreateFromCMO just uses the mesh name as a filepath.

**Comment by walbourn** [comment]
The path logic is handled by the ``IEffectFactory`` you provide. The default ``EffectFactory`` implementation has a method for setting the path to look for when loading textures. See the [wiki](https://github.com/Microsoft/DirectXTK/wiki/EffectFactory#directories)
