### ISSUE TITLE
pMatrixCoefficients is pointed to uninitialized memory

### ISSUE THREAD

**Issue by PeteHuf** [Microsoft/DirectXTK#89]
pMatrixCoefficients is pointed to uninitialized memory. I was hearing horrible audio clipping and glitches and traced it down to the `matrix` below:
```c++
float matrix[ XAUDIO2_MAX_AUDIO_CHANNELS * 8 ];
assert( mDSPSettings.SrcChannelCount <= XAUDIO2_MAX_AUDIO_CHANNELS );
assert( mDSPSettings.DstChannelCount <= 8 );
mDSPSettings.pMatrixCoefficients = matrix;
```
`float matrix[ XAUDIO2_MAX_AUDIO_CHANNELS * 8 ]{};` should fix this.

**Comment by walbourn** [comment]
Thanks. Good fix.

If you want to submit this as a pull request for DirectXTK and/or DirectXTK12, please do. I'd probably go with ``float matrix[XAUDIO2_MAX_AUDIO_CHANNELS * 8] = {};`` to make it a little more obvious (it's easy to lose sight of the little braces next to the brackets).

If you don't want to the PR, I'll take care of it before the next release.

**Comment by PeteHuf** [comment]
I'm not that familiar with submitting a PR, and took my copy of DXTK as a zip file, so I'll let you take care of it for next release.

**Comment by walbourn** [comment]
No problem. [Done](https://github.com/Microsoft/DirectXTK/commit/b54955b59784a38eaccc6169c3e23ea7f5026c8d) and [done](https://github.com/Microsoft/DirectXTK12/commit/a0893aeff9bfbb8063cfd3cb6575110c9a9da8a0).
