### ISSUE TITLE
XAUDIO2: ERROR: SourceChannels = 1 but this voice produces 2-channel audio

### ISSUE THREAD

**Issue by PeteHuf** [Microsoft/DirectXTK#90]
It looks like a problem in SoundCommon.cpp when using reverb on a two channel sample:
```c++
if ( reverb )
{
    (void)voice->SetOutputMatrix( reverb, 1, 1, &mDSPSettings.ReverbLevel );
}
```
Changing the line to the following seems to fix the issue:
```c++
(void)voice->SetOutputMatrix( reverb, mDSPSettings.SrcChannelCount, 1, &mDSPSettings.ReverbLevel );
```
I don't understand the API well enough to know if this is correct. Changing the dest channel count to `mDSPSettings.DstChannelCount` causes an error:
`XAUDIO2: ERROR: DestinationChannels = 2 but the given destination voice accepts 1-channel audio`
I guess the reverb effect can't handle multiple channels? (I wouldn't blame it.)

**Comment by walbourn** [comment]
The reverb effect itself is running on a submix voice that is set up as mono for performance. The output matrix is supposed to be mapping the output of the source voice to the submix voice. I suspect the correct fix is actually:

    for(size_t j = 0; j < mDSPSettings.SrcChannelCount; ++j)
        matrix[j] = mDSPSettings.ReverbLevel, mDSPSettings.ReverbLevel;
    (void)voice->SetOutputMatrix( reverb, mDSPSettings.SrcChannelCount, 1, matrix );

**Comment by PeteHuf** [comment]
I gave your change a try and everything seems to be working.

**Comment by walbourn** [comment]
Cool. Fixed [here](https://github.com/Microsoft/DirectXTK/commit/f831a1b82570d9fbd22dfb7909f9882a5ed72378) and [here](https://github.com/Microsoft/DirectXTK12/commit/2b47718e50f74c824fa5e68356332b9e0f42245e)
