### ISSUE TITLE
Static Build Target doesn't work with Nuget Package

### ISSUE THREAD

**Issue by tylergibson** [Microsoft/DirectXTK#91]
The nuget packages only include the dynamically linked libs for each build configuration.  Even though the target files support static or dynamic, this is ignored for some reason - it appears the targets are actually empty.

We are currently forced to manually build static libs and package them ourselves.  Please update the nuget package with static linked lib targets and update the targets config so we can use the official nuget package.

**Comment by shawnhar** [comment]
Distributing static C++ libs via NuGet does not generally work very well, as these are only compatible with a specific version of the compiler, C runtime, choice of compiler settings, etc.

**Comment by walbourn** [comment]
Note that the NuGet packages of DirectXTK actually contain static link libraries and not DLLs, so I'm not sure what the issue is here exactly. Let me look into it.

**Comment by walbourn** [comment]
The NuGet packages definitely use static libraries. Did you perhaps mean VSPkg?
