### ISSUE TITLE
Mastering limiter boosting quiet sounds

### ISSUE THREAD

**Issue by PeteHuf** [Microsoft/DirectXTK#95]
Thanks to Chuck I was able to get the AUDIO_ENGINE_FLAGS::AudioEngine_UseMasteringLimiter working. It is doing a good job of preventing clipping for loud sounds, but it also has an unexpected (and unwanted) effect: it seems to be boosting the volume of quiet sounds.

I have a weapon sound effect which starts loud and has a soft trail-off finish. When using the mastering limiter, the initial loud sound is the same volume as without the limiter (this sound doesn't clip even without the limiter), but the trail-off finish is louder. I expected the limiter to only make loud sounds quieter, not soft sounds louder.

I've noticed this with other sounds too. I have a consistently quiet wind sound which is boosted to be too loud when the limiter is on. I suspect something isn't configured properly, but I have no idea where to look. A Bing search hasn't given me any clues,--just people lamenting how little documentation there is about XAudio. :)

I'm using XAudio2_7.dll and XAPOFX1_5.dll.

**Comment by walbourn** [comment]
The code is using the following parameters:

        FXMASTERINGLIMITER_PARAMETERS params = {};
        params.Release = FXMASTERINGLIMITER_DEFAULT_RELEASE;
        params.Loudness = FXMASTERINGLIMITER_DEFAULT_LOUDNESS;

Do I need to expose a way to modify these?

**Comment by PeteHuf** [comment]
Was this closed due to age? If I put together a solution which repros the issue would you be interested?

**Comment by walbourn** [comment]
If you have a repro or more details, please feel free to reopen. If it's really an XAudio2 bug instead of the _DirectX Tool Kit for Audio_, and there's no workaround, I'm not sure what to do about it.

**Comment by PeteHuf** [comment]
Thanks Chuck, I put together this a little demo project which demonstrates the issue:  [https://1drv.ms/u/s!AhmO0u3HJ7RHjoFUNArr6hFd9K_Epg](https://1drv.ms/u/s!AhmO0u3HJ7RHjoFUNArr6hFd9K_Epg)

The demo runs the wind sound and a sci-fi weapon firing sound. It starts with the limiter off. Clicking the mouse toggles the limiter. When the limiter is on, the wind is louder and the firing sound gets a little quieter.
