### ISSUE TITLE
how to save mipmap

### ISSUE THREAD

**Issue by zhidongqing** [Microsoft/DirectXTK#97]
i want to save mipmap

**Comment by zhidongqing** [comment]
i want save dds mipmap

**Comment by walbourn** [comment]
The [ScreenGrab](https://github.com/Microsoft/DirectXTK/wiki/ScreenGrab) module in DirectX Tool Kit is optimized for capturing screenshots, which would not include mipmaps. It also doesn't support 1D, 2D Array, Cubemaps, or 3D textures for writing.

If you want code for writing the complete range of formats and resource types supported, see [DirectXTex](https://github.com/Microsoft/DirectXTex)
