### ISSUE TITLE
ScreenGrab example?

### ISSUE THREAD

**Issue by JustMeDaFaq** [Microsoft/DirectXTK#98]
Is there any ScreenGrab example?
Im actually new to the whole directx stuff and just wanted to test performance by capturing one of my desktops as many times as possible. (1920*1080) 

Which performance could i expect?

Thanks in advance!

**Comment by walbourn** [comment]
See [ScreenGrab](https://github.com/Microsoft/DirectXTK/wiki/ScreenGrab) in the [wiki](https://github.com/Microsoft/DirectXTK/wiki).
