### ISSUE TITLE
CreateFromCMO fails if no materials in file

### ISSUE THREAD

**Issue by Petrotheos** [Microsoft/DirectXTK#99]
std::unique_ptr\<IEffectFactory> mEffectFactory = std::unique_ptr\<DGSLEffectFactory>(new DGSLEffectFactory(mD3DDevice));
std::unique_ptr\<CommonStates> mCommonStates = std::unique_ptr\<CommonStates>(new CommonStates(mD3DDevice));
mModelPlayer = Model::CreateFromCMO(mD3DDevice, L"a.cmo", *mEffectFactory);
![default](https://user-images.githubusercontent.com/18349931/28963480-e826591a-7911-11e7-889e-c8e8c218ebf2.jpg)
Unhandled exception on 2nd breakpoint: An invalid parameter was passed to a function that considers invalid parameters fatal.
File is read and dataSize has bigger value than usedSize. Why it fails?
Is it possible the .cmo file is in bad format?
I tested it with different cmo and it fails but on different locations.

**Comment by walbourn** [comment]
Please attach the ``cmo``.

Alternatively, you can build & run the [cmodump](https://raw.githubusercontent.com/wiki/Microsoft/DirectXMesh/cmodump.cpp) tool on that file and post the output.

**Comment by Petrotheos** [comment]
CMO C:\Users\???????\Documents\Visual Studio 2017\Projects\App1\x64\Debug\DirectX 11 XAML App\AppX\a.cmo
2 meshes
 Mesh #0 'Torus001'
        Materials (0)
        SubMeshes (1)
                SubMesh #0 - material 0, IB 0, VB 0, start 0, count 576
        IB #0 - 1728 indices (576 faces)
              1:        0, 1, 2
              2:        3, 4, 5
              3:        0, 2, 6
              4:        7, 8, 9
              5:        10, 11, 12
         ...
            572:        1515, 1516, 1517
            573:        1518, 1519, 1520
            574:        1521, 1522, 1523
            575:        1524, 1525, 1526
            576:        1527, 1528, 1529
        VB #0 - 1530 vertices
              1:        P:(-0.000064, 19.996073, -1458.912476)
                        N:(-0.000000, 0.490903, -0.871214)
                        T:(-0.997918, -0.056188, -0.031660, 1.000000)
                        C:(1.000000, 1.000000, 1.000000, 1.000000)
                        TX:(156.722076, 0.366716)
              2:        P:(-0.000064, -0.000064, -1464.270386)
                        N:(-0.000000, 0.000000, -1.000000)
                        T:(-1.000000, -0.000000, 0.000000, 1.000000)
                        C:(1.000000, 1.000000, 1.000000, 1.000000)
                        TX:(156.722076, 0.000000)
              3:        P:(377.594391, 19.996075, -1409.201294)
                        N:(0.225487, 0.490903, -0.841529)
                        T:(-0.972109, 0.056188, -0.227699, 1.000000)
                        C:(1.000000, 1.000000, 1.000000, 1.000000)
                        TX:(150.191986, 0.366716)
              4:        P:(378.981110, -0.000062, -1414.376587)
                        N:(0.258819, 0.000000, -0.965926)
                        T:(-0.965926, -0.000000, -0.258819, 1.000000)
                        C:(1.000000, 1.000000, 1.000000, 1.000000)
                        TX:(150.191986, 0.000000)
              5:        P:(377.594391, 19.996075, -1409.201294)
                        N:(0.225487, 0.490903, -0.841529)
                        T:(-0.972109, 0.056188, -0.227699, 1.000000)
                        C:(1.000000, 1.000000, 1.000000, 1.000000)
                        TX:(150.191986, 0.366716)
         ...
           1526:        P:(-377.594910, -19.996222, -1409.201050)
                        N:(-0.225487, -0.490903, -0.841528)
                        T:(-0.972109, 0.056188, 0.227699, 1.000000)
                        C:(1.000000, 1.000000, 1.000000, 1.000000)
                        TX:(6.530090, 4.033879)
           1527:        P:(-0.000064, -0.000064, -1464.270386)
                        N:(-0.000000, 0.000000, -1.000000)
                        T:(-1.000000, 0.000000, 0.000000, 1.000000)
                        C:(1.000000, 1.000000, 1.000000, 1.000000)
                        TX:(0.000000, 4.400596)
           1528:        P:(-0.000064, -19.996223, -1458.912476)
                        N:(-0.000000, -0.490903, -0.871214)
                        T:(-0.997918, -0.056188, 0.031660, 1.000000)
                        C:(1.000000, 1.000000, 1.000000, 1.000000)
                        TX:(0.000000, 4.033879)
           1529:        P:(-0.000064, -0.000064, -1464.270386)
                        N:(-0.000000, 0.000000, -1.000000)
                        T:(-1.000000, 0.000000, 0.000000, 1.000000)
                        C:(1.000000, 1.000000, 1.000000, 1.000000)
                        TX:(0.000000, 4.400596)
           1530:        P:(-377.594910, -19.996222, -1409.201050)
                        N:(-0.225487, -0.490903, -0.841528)
                        T:(-0.972109, 0.056188, 0.227699, 1.000000)
                        C:(1.000000, 1.000000, 1.000000, 1.000000)
                        TX:(6.530090, 4.033879)
        Extents:
                 Sphere (0.000000, 0.000000, 0.000000) 1464.270508
                 Box (-1464.270386, -39.992332, -1464.270386)
                     (1464.270386, 39.992332, 1464.270386)
        No animation or skinning data present.
 Mesh #1 'Sphere001'
        Materials (0)
        SubMeshes (1)
                SubMesh #0 - material 0, IB 0, VB 0, start 0, count 960
        IB #0 - 2880 indices (960 faces)
              1:        0, 1, 2
              2:        3, 4, 5
              3:        6, 7, 8
              4:        9, 10, 11
              5:        12, 13, 14
         ...
            956:        2308, 2307, 2382
            957:        2383, 2384, 2385
            958:        2386, 2387, 2388
            959:        2324, 2323, 2389
            960:        2330, 2329, 2390
        VB #0 - 2391 vertices
              1:        P:(-40.286495, 1038.154297, -202.533920)
                        N:(-0.039207, 0.979598, -0.197107)
                        T:(-0.994605, -0.019300, 0.101920, 1.000000)
                        C:(1.000000, 1.000000, 1.000000, 1.000000)
                        TX:(8.182466, 122.736984)
              2:        P:(-0.000009, 1038.154297, -206.501801)
                        N:(-0.000000, 0.979598, -0.200969)
                        T:(-0.995378, 0.019300, 0.094077, 1.000000)
                        C:(1.000000, 1.000000, 1.000000, 1.000000)
                        TX:(0.000000, 122.736984)
              3:        P:(0.000000, 1058.493042, -0.000046)
                        N:(-0.000000, 1.000000, -0.000000)
                        T:(-0.995185, -0.000000, 0.098017, 1.000000)
                        C:(1.000000, 1.000000, 1.000000, 1.000000)
                        TX:(0.000000, 130.919449)
              4:        P:(-79.024796, 1038.154297, -190.782806)
                        N:(-0.076907, 0.979598, -0.185671)
                        T:(-0.955611, -0.019300, 0.293999, 1.000000)
                        C:(1.000000, 1.000000, 1.000000, 1.000000)
                        TX:(16.364931, 122.736984)
              5:        P:(-40.286495, 1038.154297, -202.533920)
                        N:(-0.039207, 0.979598, -0.197107)
                        T:(-0.957899, 0.019300, 0.286457, 1.000000)
                        C:(1.000000, 1.000000, 1.000000, 1.000000)
                        TX:(8.182466, 122.736984)
         ...
           2387:        P:(114.725739, -1038.154419, -171.699905)
                        N:(0.111652, -0.979598, -0.167099)
                        T:(-0.879894, -0.019300, -0.474779, 1.000000)
                        C:(1.000000, 1.000000, 1.000000, 1.000000)
                        TX:(237.291550, 8.182458)
           2388:        P:(79.024307, -1038.154419, -190.782623)
                        N:(0.076907, -0.979598, -0.185671)
                        T:(-0.883609, 0.019300, -0.467828, 1.000000)
                        C:(1.000000, 1.000000, 1.000000, 1.000000)
                        TX:(245.474014, 8.182458)
           2389:        P:(0.000000, -1058.493042, 0.000046)
                        N:(-0.000000, -1.000000, 0.000000)
                        T:(-0.881922, -0.000000, -0.471395, 1.000000)
                        C:(1.000000, 1.000000, 1.000000, 1.000000)
                        TX:(237.291550, -0.000016)
           2390:        P:(0.000000, -1058.493042, 0.000046)
                        N:(-0.000000, -1.000000, 0.000000)
                        T:(-0.956941, 0.000000, -0.290282, 1.000000)
                        C:(1.000000, 1.000000, 1.000000, 1.000000)
                        TX:(245.474014, -0.000016)
           2391:        P:(0.000000, -1058.493042, 0.000046)
                        N:(-0.000000, -1.000000, 0.000000)
                        T:(-0.995185, 0.000000, -0.098016, 1.000000)
                        C:(1.000000, 1.000000, 1.000000, 1.000000)
                        TX:(253.656479, -0.000016)
        Extents:
                 Sphere (0.000000, 0.000000, 0.000000) 1058.493164
                 Box (-1058.493042, -1058.493042, -1058.493042)
                     (1058.493042, 1058.493042, 1058.493042)
        No animation or skinning data present.

**Comment by walbourn** [comment]
It looks like a valid ``cmo``, and that line should only throw if it's missing data. Which release of DXTK are you using? Are you using the Debug build?

**Comment by Petrotheos** [comment]
Windows 10 uwp debug. But it crashes on release too. I downloaded it twice just in case.
One file I downloaded from a site worked but the rest fail.

**Comment by walbourn** [comment]
Can you attach ``a.cmo`` to this issue?

**Comment by Petrotheos** [comment]
It accepts images only.

**Comment by Petrotheos** [comment]
[only tree is working.zip](https://github.com/Microsoft/DirectXTK/files/1204105/only.tree.is.working.zip)

**Comment by walbourn** [comment]
I'll keep digging, but change this line:

    mModelPlayer = Model::CreateFromCMO(mD3DDevice, L"a.cmo", *mEffectFactory);

To

    mModelPlayer = Model::CreateFromCMO(mD3DDevice, L"a.cmo", mEffectFactory.get());

**Comment by walbourn** [comment]
These ``CMO`` files are being created without any materials (materials count is 0) which ends up throwing in the code as the loader doesn't know what to do about the materials with nothing defined. It looks like I need to update the CMO reader to handle a CMO without any materials defined.

**Comment by Petrotheos** [comment]
Visual Studio mesh content pipeline creates .cmo without materials? How can I use materials?

**Comment by walbourn** [comment]
The fix is in [this commit](https://github.com/Microsoft/DirectXTK/commit/730b2b98e52b42c5029debb319dc370628f39c0c). 

> Note, however, that this really only works when all the meshes in ``CMO`` are missing materials. If only _some_ of the meshes are missing material definitions, then they will end up using some other material because the ``CMO`` format itself doesn't have a way to express a 'default material'. As such, it's probably not a good idea to rely on this and instead you should make sure all your objects in the source ``FBX`` or ``OBJ`` converted to ``CMO`` have a material.
